### ISSUE TITLE
"become a sponsor" button not aligned

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1017]
![](https://www.dropbox.com/s/qlq025f0rz8295i/Screenshot%202016-04-25%2016.34.18.png?dl=1) or is that my imagination?

**Comment by tansaku** [comment]
ah, not my imagination: 

![](https://www.dropbox.com/s/qn2x3zk9ezpd3x3/Screenshot%202016-04-25%2016.37.12.png?dl=1)

**Comment by diraulo** [comment]
@tansaku I'll take another pass at this
