### ISSUE TITLE
Fix Craft Academy image size

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1048]
<img width="217" alt="screenshot 2016-05-21 09 18 30" src="https://cloud.githubusercontent.com/assets/4028374/15447102/b9a8887e-1f35-11e6-93ba-6253855b2483.png">

**Comment by tansaku** [comment]
@diraulo still an issue? is the width wrong?

**Comment by mattlindsey** [comment]
Looks ok now.
