### ISSUE TITLE
google calendar integration

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1058]
```
As a member
So that I can ensure I will attend an event
I would like to be able to add to my calendar
```

a few users (@kenshinji, @touchps?) have mentioned having google calendar integration - some link to click that adds an AV event to google calendar or similar?

I'm not quite sure how that would work, but something to look into perhaps ...

**Comment by weedySeaDragon** [comment]
+1 for this.  Would be helpful to have the automatically generated entries for iCal, Google, and outlook.  Then people can just click on whatever one they'd like and download it and, depending on their browser set up of course, have it automatically entered into their calendar.
Surely there's a gem out there that already does it. :-)

**Comment by AmberWilkie** [comment]
+1 I would be willing to work on this... you know, sometime....

**Comment by tansaku** [comment]
@AmberWilkie that would be super cool - just let me know if you ever need help getting set up :-)

**Comment by tansaku** [comment]
meetup has this export function:

![](https://www.dropbox.com/s/rbe8ri8hc6bu5h8/Screenshot%202017-03-17%2016.13.53.png?dl=1)

**Comment by tansaku** [comment]
for reference https://en.wikipedia.org/wiki/ICalendar

**Comment by tansaku** [comment]
example url from meetup.com

```
https://calendar.google.com/calendar/render?action=TEMPLATE&dates=20170322T154500Z/20170322T184500Z&sprop=website:https://www.meetup.com/remote-pair-programming/events/238468038/&text=%22Kent+Beck%22+Scrum+and+Pair+Hookup&location=Online+-+http://www.agileventures.org/events/kent-beck-scrum-and-pair-hookup+-+Everyplace,+United+Kingdom&sprop=name:Remote+Pair+Programming&details=For+full+details,+including+the+address,+and+to+RSVP+see:%0Ahttps://www.meetup.com/remote-pair-programming/events/238468038/%0ARemote+Pair+Programming%0AQuickly+go+round+talking+about+what+projects+we%27re+working+on+and+then+split+off+into+pairs:+http://www.agileventures.org/events/kent-beck-scrum-and-pa...&sf=true&output=xml#eventpage_6
```
