### ISSUE TITLE
API for AgileVenture events

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1060]
@kenshinji was saying shall we make some APIs open to public? 

Perhaps to support an application to retrieve the upcoming event of projects someone is involved in from AgileVentures.org, and once that app found there will be an event of LocalSupport project in one hour, it will send me an email to notify me of that

**Comment by kenshinji** [comment]
Awesome!!!

**Comment by mattlindsey** [comment]
Closing old issues...
