### ISSUE TITLE
G+ sign up failure

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1063]
I am trying to sign up to your website to be able to enrol into a pairing for a EdEx course, however I'm encountering several errors that makes it impossible for me to Sign Up or Log In.

As you have Signin UP limited for the time being, I'm trying to do so wiht the Github account. However, after trying to log in I get the following error message: "Your Github account needs to have a public email address for sign up"
I have checked my Github account and the e-mail listed there is clearly noted as public. Please see screenshot for verification.

![](https://www.dropbox.com/s/qgrnp3336uoq7q3/Screenshot%202016-05-25%2010.02.42.png?dl=1)

In addition, when trying to use the Gmail account instead, I also get an error message. Please see the following screenshot:

![](https://www.dropbox.com/s/8u3j6uev4h2ndt1/Screenshot%202016-05-25%2010.01.58.png?dl=1)

**Comment by tansaku** [comment]
that user doesn't have an existing account:

```
→ heroku run rails c -r production
Running rails c on ⬢ websiteone-production... up, run.3456
Loading production environment (Rails 4.2.6)
irb(main):001:0> User.find_by(email: '...')
=> nil
```

**Comment by diraulo** [comment]
@tansaku perhaps it's not so clear what we mean by public address on github.
The following option is available in [user profile settings](https://github.com/settings/profile)

![](https://www.dropbox.com/s/aqd0v7gf3vzpm4r/Screenshot%202016-05-25%2013.03.51.png?dl=1)

I recall a comment from @tochman about the email not returned as part of the auth response When it's set to that.

ask him to check that and try again with github.

**Comment by tansaku** [comment]
thanks @diraulo I'll pass that on ... perhaps we need to adjust our help messages ...

**Comment by diraulo** [comment]
@tansaku yep we surely do.. Let's see if that works for him.

**Comment by fighterii** [comment]
got the same error when trying to login with my gmail account today (couldn`t remember if i used my gmail adress to register or used it via oauth, so i tried oauth first).

![websiteone](https://cloud.githubusercontent.com/assets/16879286/15565365/59f50e0a-231a-11e6-9b53-649fe80d6c2a.png)

**Comment by tansaku** [comment]
thanks for reporting that @fighterii - we'll investigate - however we are gradually moving towards dropping the G+ login.  Would you be able to sign up via github?

**Comment by tansaku** [comment]
@nitishmadhukar suggesting we need to change redirect_url - so maybe @diraulo or @tansaku will need to look at

**Comment by nitishmadhukar** [comment]
@tansaku @diraulo : Adding screenshot of google developer console redirect url setting. Please check if this is the setting for redirect uri issue. It is on the credentials page.
![google redirect settings screenshot](https://cloud.githubusercontent.com/assets/7777038/15626171/a81356ce-24db-11e6-877e-42ecb7f3282f.png)

**Comment by diraulo** [comment]
Thanks @nitishmadhukar, @tansaku will have a look at that on Monday. I do not have access to WebsiteOne profile to check it 🙂

**Comment by tansaku** [comment]
thanks @nitishmadhukar - this is what we have for our web client credentials settings:

![](https://www.dropbox.com/s/4orawtrb9k1peod/Screenshot%202016-05-30%2008.47.38.png?dl=1)

**Comment by tansaku** [comment]
so we seem to have `http://www.agileventures.org/auth/gplus/callback` as an authorised redirect URL, but perhaps the problem is arising from this `origin=%2Fprojects%2Fwebsiteone`

In the first instance I've added the following explicitly to the list of authorised redirect URLs

http://www.agileventures.org/auth/gplus/callback?origin=%2Fprojects%2Fwebsiteone

**Comment by tansaku** [comment]
there's probably some redirect path addition screwing things up ...

**Comment by nitishmadhukar** [comment]
@tansaku Regarding the github public email. Im trying to embed the github settings page url in the error message. Not sure about the G+ attributes that are returned after signup. Hence, having code that can handle both the authentications is difficult right now.

Another possibility is routing the user to an AV github page that shows the solution for GitHub and G+(future)

**Comment by sriharisahu** [comment]
I have a public github email and I tried both github as well as google+ and failed with both.

What I can say is this "The callback url doesn't exist". Both OAuth 2 app buttons have the call back url as http://www.agileventures.org/auth/github?origin=%2F which ends up in a HTTP 404.

Please fix the call back URLs.

**Comment by tansaku** [comment]
hi @sriharisahu - I can see from your github account that actually you don't have a public email.

I've just checked sign up through github on our site on my backup github account and it's working fine for me.

I think you may, as have many others, mis-understood github's interface for how to make your email public.  To re-iterate; seeing the following:

![](https://www.dropbox.com/s/lh1q3cueu86yu31/Screenshot%202016-06-06%2008.46.43.png?dl=1)

does *not* mean you have a public email address.  You need to see the following in your main profile:

![](https://www.dropbox.com/s/7mecn6am7n99wed/Screenshot%202016-06-06%2008.47.21.png?dl=1)

and you need to ensure that you press the "update profile" button:

![](https://www.dropbox.com/s/s9nma7fuon07654/Screenshot%202016-06-06%2008.47.45.png?dl=1)

if you are changing from one state to another.

The reason I can tell you do not have your email public on your github account is because I cannot see it on your github profile page:

![](https://www.dropbox.com/s/0jzg0kvjs9wbl54/Screenshot%202016-06-06%2008.48.46.png?dl=1)

Note the difference between your profile page, and my test account:

![](https://www.dropbox.com/s/opswywvm9u0a85k/Screenshot%202016-06-06%2008.49.18.png?dl=1)

So I'm guessing our callback urls for github are okay.

We do have some kind of ongoing problem with G+, for which my apologies, but in the meantime I recommend you sign up with Github

**Comment by sriharisahu** [comment]
@tansaku - Thanks for getting back with the correct info. I signed up with github.

**Comment by tansaku** [comment]
partially addressed by hiding G+ signup

**Comment by tansaku** [comment]
1) remove G+ completely XXX
2) keep it and fix it --> two kinds of signup/logins
3) remove the G+ signup/login - but have a "connect to G+" in profile page

like to have GitHub and G+ ids for all users

G+ SignUp Pro
------------------
more flexibility
don't need a github account to sign up


Con
-----
we have users without GitHub accounts?

Michael - people in AV e.g. project managers might not need github accounts


Let's fix it
