### ISSUE TITLE
make instructions related to github email more specific?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1064]
seems like we might not be being specific enough ... see https://github.com/AgileVentures/WebsiteOne/issues/1063

**Comment by tansaku** [comment]
hi @nitishmadhukar - any progress on this?

**Comment by nitishmadhukar** [comment]
hi @tansaku. Added the document for github signup solution in solutions_for_signup_issues.md. Should I provide a link to users in the GitHub public email message to the master branch or develop branch to connect to?

**Comment by tansaku** [comment]
@nitishmadhukar I would say develop
