### ISSUE TITLE
Re-enable email sign-ups?

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1067]
We had to disable this functionality recently due to spam-bots. Perhaps we could bring it back and make use of [Google reCaptcha](https://www.google.com/recaptcha/intro/index.html)

**Comment by tansaku** [comment]
Heroku apparently going to make ssl available more widely which might make this more practical as currently submitted passwords would be insecure

**Comment by tansaku** [comment]
@diraulo I got reCaptcha working well on some other systems - now we have SSL enabled there's no block for this and seems like there is a reCaptcha gem we could use with devise:

https://github.com/ambethia/recaptcha

I'm going to try it out.
