### ISSUE TITLE
Indicate if event is live when the event is actually still in progress

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1073]
It appears the indication of events being live only appears for a moment and then goes away... We should in principle keep that until the event ends.

**Comment by mtc2013** [comment]
Consolidate and investigate.  IE< make sure that the front page and index page are consistent with each other in the first instance.

**Comment by tansaku** [comment]
I saw scrums with live button for 15 mins I thought ...

**Comment by tansaku** [comment]
scrum we were just in appeared to have live button only for first five minutes - code in event_instance is ambiguous about times:

```ruby
  scope :live, -> { where('updated_at > ?', 5.minutes.ago).order('created_at DESC') }
  scope :latest, -> { order('created_at DESC') }
  scope :pp_hangouts, -> { where(category: 'PairProgramming') }

  validate :dont_update_after_finished, on: :update

  def started?
    hangout_url?
  end

  def live?
    started? && hoa_status != 'finished' && updated_at §
  end
```

difference between live and live? unclear

**Comment by tansaku** [comment]
so the logic in the `live?` method actually seems reasonable, but it seems like the polling back from the hangout may  not necessarily update the updated_at attribute on the hangout as expected. 

we may need to explicitly set that in the event_instance_controller `hangout_params` to ensure it always updates.  I'd like to link that in to the acceptance test if possible.

It may also be the case that the JS in the hangout dies - and we should have a review of that code ...

**Comment by tansaku** [comment]
Related: 

* http://stackoverflow.com/questions/5908216/how-do-i-use-capybara-get-show-post-put-in-controller-tests
* http://www.elabs.se/blog/34-capybara-and-testing-apis
