### ISSUE TITLE
possible problem with creating events in your timezone

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1074]
For some reason the Kent Beck scrum event seemed to have disappeared today - I searched through the rails console and could find no trace of it.  Ah looks like some user editing it out of existing: 

http://www.agileventures.org/events/kent-beck-scrum-and-pair-hookup

Anyway, so I repurposed the old atlantic scrum ... but also discovered that there might be a timezone issue updating the time:

![](https://www.dropbox.com/s/3yunh9c674eal7u/Screenshot%202016-06-03%2017.11.42.png?dl=1)

Note that this is the time view in show:

![](https://www.dropbox.com/s/48tw2gko0xaf34d/Screenshot%202016-06-03%2017.26.44.png?dl=1)

and this is the view in edit:

![](https://www.dropbox.com/s/iqvqkna8gb9p49p/Screenshot%202016-06-03%2017.28.35.png?dl=1)

which seems like a mismatch, because the edit page should update the time to BST - at the moment it seems to be sticking on the UTC - although the switch between 24 hour and 12 hour is confusing.

**Comment by mtc2013** [comment]
Investigate daylight savings issues.

**Comment by mtc2013** [comment]
Explore if poltergeist is better.
