### ISSUE TITLE
Investigate test coverage

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1076]
is our test coverage relying entirely on rspecs, or are they connected to the features?

I think it might be more practical if feature coverage was included ... 

We should at least be clear what our test coverage is set up for

**Comment by tansaku** [comment]
@diraulo was seeing some odd effects from rspec/cucumber - coverage reported incorrectly sometimes

**Comment by tansaku** [comment]
weirdness going to coveralls:

 [](https://www.dropbox.com/s/tpvfqmr8w31z5sy/Screenshot%202016-08-26%2014.34.42.png?dl=1)

**Comment by diraulo** [comment]
Regarding this @tansaku (see image). I'm tempted to setup a completely new project for WSO on coveralls. Not sure how to remove/hide those old entries from the time the project was using Travis.

<img width="991" alt="screenshot 2016-09-07 22 01 52" src="https://cloud.githubusercontent.com/assets/4028374/18326598/db8b85d8-7546-11e6-9146-0da2477ac920.png">

**Comment by tansaku** [comment]
makes sense @diraulo

**Comment by tansaku** [comment]
how are things going with this @diraulo ?
