### ISSUE TITLE
Move the new javascript files to an automated management system and out of vendor files

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1080]
Possibly npm, bower, or grunt/gulp.

**Comment by tansaku** [comment]
People prefering npm ...

**Comment by tansaku** [comment]
would need a script to install and then copy to vendor directory ...

**Comment by mtc2013** [comment]
https://github.com/twitter/typeahead.js/ 

This appears to be old enough that it uses bower.  Need to figure out how to install it via npm or some workaround.

**Comment by mtc2013** [comment]
same with bootstrap-tags

**Comment by mtc2013** [comment]
this might work for typeahead https://github.com/corejavascript/typeahead.js
