### ISSUE TITLE
paging backwards and forwards from show to the edit event page can lead to ongoing time jumps

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1082]
This is a real corner case, but it seems like using the back and forward arrows to move back and forward between the show and edit event page (on chrome) can lead to the hour incrementing forward each time the edit page gets reloaded - doesn't happen for a pure reload of the event page without going back to the show page - some kind of stale data issue?

**Comment by mattlindsey** [comment]
Closing old issues...
