### ISSUE TITLE
"Recently Online" check box on members page is in wrong place

### ISSUE THREAD

**Issue by SuperManEver** [AgileVentures/WebsiteOne#1092]
I've noticed that "Recently Online" may be not in place where it intended to

![screenshot_2016-06-10_22-22-08](https://cloud.githubusercontent.com/assets/2178264/15972890/3570a566-2f5a-11e6-8d85-f20948f68425.png)

**Comment by tansaku** [comment]
thanks for reporting that @SuperManEver

**Comment by NickSchimek** [comment]
This seems to have been fixed. @SuperManEver If it's still an issue what browser are you seeing the issue on?

<img width="933" alt="screen shot 2018-05-19 at 12 10 12 am" src="https://user-images.githubusercontent.com/19519317/40266052-2d3a0082-5af9-11e8-9225-83a86da142b0.png">
