### ISSUE TITLE
Skip email as required field for Devise

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1093]
Potentially related to #1063 & #1064

```
As a system owner
In order to avoid having users running into errors while signing up using OAuth
I would like to skip having email as a required field while creating a new user account
```

The process of registering with GitHub causes issues for users that do not have a public email address. In those cases the GH API will not return an email in the response and the registration process will fail.

Email is used by default but there is a way to set another identifier for Devise to use. 

```
# app/models/user.rb

devise :database_authenticatable, authentication_keys: [:full_name]
```

...or whatever attribute we have on the model.

**Comment by tansaku** [comment]
great idea @tochman - I was also wondering, could we just ask the user to enter their email if not visible on github?

**Comment by diraulo** [comment]
@tansaku @tochman reminds me one of the students from CA implemented GitHub signup in his app and after redirecting from Github, he had a form asking for the user's email address on the application.

**Comment by tochman** [comment]
@tansaku If you really need the email for something then yes, asking for it is a way to go. But IF they choose not to disclose their email they should still be allowed to sign up IMO.

**Comment by tansaku** [comment]
@tochman well that would be a new feature, in that every sign up mechanism we've had so far requires an email.  The current flow sends an automated email when they join, and if we don't have an email from them then there is no way for them to reset their password with at least some degree of security, so in the first instance I am going to disagree and say we need an email from someone who wants to sign up to the site.
