### ISSUE TITLE
Update tweet service to check if the event is being recorded before posting a tweet with YT link.

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1094]
```
As a system owner
In order to avoid confusing our Twitter followers
I would like the tweet service to only tweet YouTube links if the event has been recorded
```

Okay, so we have an issue on our Twitter account with users not recording their HOA's and thus, a lot of tweeted YT links are dead. The best scenario is, of course, if all events are being recorded, but that will never be the case so we need to condition this.

**Comment by tansaku** [comment]
I can confirm this is still an issue ...

**Comment by tansaku** [comment]
can we detect dud videos before they go out?

**Comment by tansaku** [comment]
@Arepo I wonder if we could use http://stackoverflow.com/questions/33890144/check-if-a-video-exists-on-youtube-api-v3 to check for this - lots of possible wrappers we could use ... https://www.google.co.uk/search?q=youtube%20api%20gem

**Comment by mattlindsey** [comment]
@Arepo Congrats on your new job!  Will you still be working on this ticket, or do you want me to complete it for you?
