### ISSUE TITLE
Temporarily disable G+ signup

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1095]
Having this on the site causes a lot of confusion when users try to sign up. We should remove this from site at least until #1063 is resolved

**Comment by tansaku** [comment]
we have a draft version of this working.

Also noting this quora post on how we might be able to track who is signing up with what via google analytics ...

https://www.quora.com/How-do-you-track-Facebook-Connect-signup-goals-in-Google-Analytics

Note that we can currently review this kind of flow in google analytics:

![](https://www.dropbox.com/s/ucozlk7tyay2smm/Screenshot%202016-06-13%2014.01.29.png?dl=1)

this was for the weekend of 11th/12th June 2016
