### ISSUE TITLE
Saudi Arabia timezone issue

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1097]
From one of our users

> I'm in Saudi Arabia (UTC+3).
The events listing appears to me in AST (Atlantic Standard Time). If there is an option to change this, I cannot find it. I saw in a video in CS169 that the events could appear in a different time zone than AST.

> 4 notes that might help:
* My profile: http://www.agileventures.org/users/omar-w-kh
* In the dashboard, it appears that there are no users in Saudi Arabia (I'm a user there).
* When I create an event, the site detects my time zone correctly (Asia/Riyadh).
* In the detailed view of an event. I see both AST and UTC. But not my time zone.

> It would be really helpful if I could see event listings in my time zone.

**Comment by OmarWKH** [comment]
My OS: Windows 7 Home Premium Service Pack 1 64-bit
My Browser: Chrome Version 50.0.2661.102 m

**Comment by OmarWKH** [comment]
It occurs to me that Arabia Standard Time (UTC+3) and Atlantic Standard Time (UTC-4) are both abbreviated to AST.

**Comment by tansaku** [comment]
Seems like this might be a problem with the local_time gem we are using under the hood.  Perhaps we could replace with our own js approach using moment ...

**Comment by OmarWKH** [comment]
It's not a bug. I assumed AST is referring to Atlantic after googling it because I wasn't familiar with the abbreviation.
The difference between UTC and AST in a scheduled event is +3, which confirms that it's Arabian.

I'm really sorry for the inconvenience. I'm going to remember this for the rest of my life.

**Comment by tansaku** [comment]
no inconvenience at all @OmarWKH - really appreciate you reporting this and glad it turns out not to be such a serious issue - I think we can look at using a JS library to add more information about the timezone to avoid such confusion in future ...
