### ISSUE TITLE
Link Premium and Premium Plus into site navigation

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1114]
Thinking we might replace articles link in the navbar ...

**Comment by SuperManEver** [comment]
Should we have two links instead of one each pointing to Premium and Premium Plus?  Or we should create a link to page where will Premium and Premium Plus plans and benefits they provided and separate link to each of them (like for example here https://github.com/pricing) ?

**Comment by tansaku** [comment]
@SuperManEver in the pull request I link to pricing I think
