### ISSUE TITLE
Wrong day for local time zone in special cases

### ISSUE THREAD

**Issue by OmarWKH** [AgileVentures/WebsiteOne#1116]
If an event starts at the end of the day by UTC and the start of the next day by the local time zone, the day is shown according to UTC. Even though the time shown is local (in list of events) or both local and UTC with local being prominent (in event details).
Example: http://i.imgur.com/rDOu8HM.png
![](http://i.imgur.com/rDOu8HM.png)
Expected behavior: The day is shown according to the local time zone.

**Comment by tansaku** [comment]
good catch @omarWKH - will work to fix that
