### ISSUE TITLE
Potential issue with local timezone display on "Upcoming Events"

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#1121]
As reported by a CS169.1 student:

https://courses.edx.org/courses/course-v1:BerkeleyX+CS169.1x+3T2015SP/discussion/forum/i4x-edx-templates-course-Empty/threads/57662da87e622b053f0009a5

> When you look at the "upcoming events" page on AgileVentures, you see something like this showing the date and time of the event:
![image](https://cloud.githubusercontent.com/assets/1401069/16177755/c0cc37e0-362d-11e6-89cf-fb85667f4130.png)
> Notice that the time is listed in my local time zone, which is Pacific Time (PDT) in the United States. However, what I just realized is that the date is actually listed in UTC, not my local time zone. What this means is that the event shown above is actually happening on SATURDAY JUNE 18TH in my time zone, even though the date and time shown above seem to say otherwise.

**Comment by diraulo** [comment]
@freeranger this is potentially related to #1116 and it's possible it was solved in #1107. Waiting for @tansaku or @mtc2013 to check merge conflicts on that.

**Comment by freeranger** [comment]
Does sound similar alright...

**Comment by mtc2013** [comment]
@diraulo @freeranger Thanks for forwarding.  This is a bug in code preexisting from @tansaku and my work on WSO.  We're looking into it, but I don't believe it's been addressed yet in the most recent prs.

**Comment by tansaku** [comment]
Reported by another user I think:

> I created an event to do my pair programming piece for the CS169 course, but am running into an issue. I'd like the date to be Wednesday, June 22, which is what I select and press save. However, when I do, it lists the event as occurring a day later, on Thursday, as per below:

![image](https://cloud.githubusercontent.com/assets/30216/16223979/f07a7a68-3797-11e6-9564-c305dbcbe136.png)

> When I changed the date to be June 21 (i.e. Tuesday), then it appeared as I want it to be, which is Wednesday June 22.
