### ISSUE TITLE
user unable to change github user name

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1130]
User reported:

> I changed my Github username after I created my AgileVentures ID, and I don't see a way to update my new Github username on my AgileVentures account page. When I click on "Remove Github" (so that I connect it again to the new one), it gives a red flag that says, "Bad Idea."

**Comment by touchps** [comment]
From the logic in AuthenticationsController#destroy, it seems like unlinking of github account won't be allowed unless you have a backup account strategy, which can be another provider (G+) or setting up password to enable email based authentication. In which case, the error message needs to be more descriptive stating the alternate solution.
