### ISSUE TITLE
Only one date on show event page

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1133]
But there are both UTC and local timezones shown.  Now that we are addressing https://github.com/AgileVentures/WebsiteOne/issues/1116, we have wrong date for utc in certain cases.

**Comment by tansaku** [comment]
maybe remove the UTC display? - I think the space would be much better spent on adding an icon of the user who created the event

**Comment by tansaku** [comment]
should we perhaps say how many hours from now the event would be?

**Comment by tansaku** [comment]
could add moment.js to make countdown dyanmic - if we showed that ...

**Comment by tansaku** [comment]
![what the view looks like](https://www.dropbox.com/s/5ojfeytr9bdsi38/Screenshot%202016-09-02%2017.37.46.png?dl=1)

**Comment by tansaku** [comment]
haven't seen you for a while @touchps - should we unassign you from this and put the ticket back in the backlog?

**Comment by touchps** [comment]
Yes it should be unassigned as i'm not certain on my availability for a while.

**Comment by Maroo-b** [comment]
@tansaku the current production website displays only one date, is it fixed ?

**Comment by tansaku** [comment]
the date can be different depending on which timezone you are in.  When both UTC and another timezone were shown a single date would sometimes be incorrect.

The short term fix was removing UTC time, although I regret that a little now.   It is sometimes handy - I wonder what are the best set of things to display on the event show page ...
