### ISSUE TITLE
Auto-post videos of meetings to notes/slack/mailing lists

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1152]
We already have meeting video automated posting to some slack channels.  Would be nice if the slack channel hookup was more consistent, e.g. betasaaers getting their updates, and the videos would be auto-embedded in the meeting notes, and sent to legacy email lists.

I guess we are posting a lot of these things onto twitter as well, which I don't follow ... would be nice to consolidate all this - check for quality, e.g. not posting videos where hangout never started recording ...

**Comment by tansaku** [comment]
posting video link to slack at end of meeting would also unfurl the play embed etc. ...

**Comment by willnwhite** [comment]
I'd definitely like my project's mob recordings to be posted to the project's Slack channel.

**Comment by tansaku** [comment]
@willnwhite are you posting the youtube link into the event?
