### ISSUE TITLE
Missing Hangout link 

### ISSUE THREAD

**Issue by asanhix** [AgileVentures/WebsiteOne#1158]
Starting today Join hangout link disappeared from events in the upcoming events section. You may create an event but you can not join one.

**Comment by tansaku** [comment]
thanks @asanhix - we adjusted the system so that the hangout link is not visible until five minutes before the event - and also gets removed when the event goes live.  When the hangout is live you should see "Event is live, join now" if you refresh the page

**Comment by tansaku** [comment]
an example of an event that's gone live:

![](https://www.dropbox.com/s/hm1zd1jr0rzmarw/Screenshot%202016-06-27%2014.25.05.png?dl=1)

**Comment by tansaku** [comment]
the orange text "JOIN NOW" is clickable and will take you to the hangout

**Comment by asanhix** [comment]
Thank you for the clear explanation I see now- it is an improvement. I thought maybe there was a glitch when I did not see the start Hangout air button immediately.
