### ISSUE TITLE
display history of event instances on events themselves?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1162]
To allow us to identify repeating events that are really being used ...

**Comment by tansaku** [comment]
for example link to video of previous session with dxate that it ran:

![](https://dl.dropbox.com/s/7zjty4gnzv9511t/Screenshot%202018-04-19%2016.04.38.png?dl=0)

**Comment by NickSchimek** [comment]
@tansaku If an event doesn't have any event instances associated to it would you like there to be a message or just left blank?

**Comment by NickSchimek** [comment]
@tansaku I can display the date and the link, but will not be able to display the running time; because I don't see anywhere we are collecting that data. Is that OK?

**Comment by NickSchimek** [comment]
Yes, we can grab the duration of the video from youtube, but if we're going to be using this data in our page views, then to limit the number of times we call the api and to keep the page load time from increasing, then we should think about storing the duration of the hangout. Perhaps this can be a separate ticket.

**Comment by tansaku** [comment]
@NickSchimek agreed - separate ticket

**Comment by tansaku** [comment]
if no event instances - then we should say something like "no previous instances of this event"
