### ISSUE TITLE
Formatting on members page

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1205]
<img width="923" alt="skarmavbild 2016-07-07 kl 13 45 39" src="https://cloud.githubusercontent.com/assets/5248170/16652217/5cbc8b18-4449-11e6-86e4-ee4b61bbe459.png">
The search part of the page is not displaying correctly on my desktop

**Comment by tansaku** [comment]
hi @tochman I have seen this locally occasionally, but never on production - @mtc2013 and I both see it normally on production in chrome on OSX - which version of chrome/OSX are you on?

**Comment by diraulo** [comment]
I think we just need to give more room to the Project select dropdown. We currently have `col-sm-4` around the select. Change that to `col-sm-6` or `col-sm-8`

```html
<div class="row">
  <div class="col-xs-12 col-sm-8">
    <!-- Projects select here -->
  </div>
  <div class="col-xs-12 col-sm-4">
    <!-- Recently online filter & submit button -->
  </div>
</div>
```
