### ISSUE TITLE
Video link not available

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/WebsiteOne#1237]
There was a strange behavior in the website on the 07/21 when we created a pairing session and recorded it, the website create an entry in the videos section, but it has no link/name.

Example:
http://www.agileventures.org/projects/metplus#video

The Youtube link that should be there is: https://www.youtube.com/watch?v=Kuf1-ikT0Oc but currently nothing is showing

**Comment by diraulo** [comment]
![](https://cl.ly/0M2P3P1V2B2i/download/Image%202016-07-26%20at%202.31.43%20PM.png)

**Comment by tansaku** [comment]
@diraulo - looks like we lost your image :-(
 
@joaopapereira - I guess the video never re-appeared?

**Comment by tansaku** [comment]
it appears to have happened again: 

![](https://www.dropbox.com/s/if6m74ozzkyeprt/Screenshot%202016-08-26%2014.46.06.png?dl=1)

**Comment by mtc2013** [comment]
A similar event instance that doesn't show a link for sam's website one pair programming on 01/09 (9/01 for 'mericans) at 13:01:05 has this value:

 #<EventInstance id: 4748, event_id: nil, title: "PairProgramming on WebsiteOne", hangout_url: "https://talkgadget.google.com/hangouts/_/os2zp7rz2...", created_at: "2016-09-01 13:01:35", updated_at: "2016-09-01 13:01:35", uid: "32130135", category: "PairProgramming", project_id: 2, user_id: 3, yt_video_id: "", participants: {"0"=>{"id"=>"hangoutF3C52D3C_ephemeral.id.google.com^f0a6da4e4c", "hasMicrophone"=>"true", "hasCamera"=>"true", "hasAppEnabled"=>"true", "isBroadcaster"=>"true", "isInBroadcast"=>"true", "displayIndex"=>"0", "person"=>{"id"=>"103524399391704001670", "displayName"=>"Sam Joseph", "image"=>{"url"=>"https://lh3.googleusercontent.com/-Kt12k8aqqTs/AAAAAAAAAAI/AAAAAAAAAAA/TL0ZFPtM2Tc/s96-c/photo.jpg"}, "oa"=>"false"}, "locale"=>"en", "oa"=>"false"}}, hoa_status: "started">

Notice the empty string in the yt_video_id

**Comment by Arepo** [comment]
Had a look in the HangoutConnection code per Michael's suggestion. As far as I can see, the gapi.hangout.onair.getYouTubeLiveId() method passes its return value directly as params to WebsiteOne, and WO seems to be saving it directly. So for some reason it seems to be returning either a null value or an empty string.

**Comment by tansaku** [comment]
thanks for looking at this @Arepo - I think there might be a timing issue here - like sometimes it takes a while for the yt link to become available - I wonder if we need something to check again some time later, or some way to have later pings from the hangout update this value if empty ...?

**Comment by tansaku** [comment]
I wonder if this helps? http://stackoverflow.com/questions/33890144/check-if-a-video-exists-on-youtube-api-v3 maybe more related to https://waffle.io/AgileVentures/WebsiteOne/cards/575d86ffdd201b7a0096fbf9 ...
