### ISSUE TITLE
Getting "Please refresh the page to load the hangouts" instead of hangout button on project page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1238]
getting the below in chrome and safari - maybe my computer needs rebooting ...

![](https://www.dropbox.com/s/6bxrwafm89zbkfi/Screenshot%202016-08-08%2010.24.29.png?dl=1)

**Comment by patmbolger** [comment]
I am seeing the same thing.

**Comment by tansaku** [comment]
that text is our placeholder for our hangout button "Please refresh the page to load the hangouts" implying that the button failed to load ...

**Comment by tansaku** [comment]
I am seeing a js console error:

![](https://www.dropbox.com/s/lcpccvs02gu7l8w/Screenshot%202016-08-09%2008.38.22.png?dl=1)

**Comment by tansaku** [comment]
```Uncaught TypeError: Cannot read property 'render' of undefined```

from ```api.hangout.render(t,{render:"createhangout",topic:i.``` in the application.js ...

**Comment by tansaku** [comment]
I just updated to Chrome Version 52.0.2743.116 (64-bit) on OSX 10.11.5 and I still get the same error and same console message

**Comment by tansaku** [comment]
hmm, so locally I am getting the same issue ...

![](https://www.dropbox.com/s/dgdvfizm68wb0pl/Screenshot%202016-08-09%2008.51.12.png?dl=1)

**Comment by tansaku** [comment]
am checking to see if anything changed for the buttons we use from https://developers.google.com/+/hangouts/button

**Comment by tansaku** [comment]
I would have appeared to have replicated the problem using just the raw hangout on air button, implying that something at google broke :-(

![](https://www.dropbox.com/s/ppxp0ar1ay35mzb/Screenshot%202016-08-09%2008.58.58.png?dl=1)

**Comment by tansaku** [comment]
appears there is an open google issue on this: https://code.google.com/p/google-plus-platform/issues/detail?id=1380

**Comment by patmbolger** [comment]
Update: this appears to have been resolved.  Works for me on Mac using Safari, Chrome and FF.
