### ISSUE TITLE
images and logos (particularly stripe)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1253]
would be nice to have AV logo in our stripe popups

@yggie also notes the AV logo in the stripe emails that we send out is lower resolution than it could be - this ticket would not include fixing that issue in our stripe emails, but we need to make sure that we have the right resolution to go intro the stripe popup - would be great it we had scalable vector graphic, but one thing at at time ...

**Comment by tansaku** [comment]
Would be great to also include our AV logo:

data-image="https://s3.amazonaws.com/stripe-uploads/ ... etc.

see https://stripe.com/docs/checkout

**Comment by tansaku** [comment]
all our art assets are in here: https://github.com/AgileVentures/agileventures-profile

**Comment by nadia39** [comment]
I would like to assist in this issue, could you give me more information on what you need?

**Comment by tansaku** [comment]
hi @nadia39 - sorry for the slow response (I was away last week).  We're looking to add our logo to this stripe popup:

![stripe popup](https://www.dropbox.com/s/x1ijdamgxjmpmwv/Screenshot%202017-02-21%2010.35.51.png?dl=1)

which would involve getting the right size of logo in the right place in our app and then setting the following in the popup:

```data-image="<image url>"```

in the script in `app/views/subscriptions/new.html.erb`

**Comment by ajay2507** [comment]
Can I work on this enhancement?

**Comment by tansaku** [comment]
@ajay2507 you could give it a try - are you in our slack?

Is there anything you need?

**Comment by ajay2507** [comment]
@tansaku Ya, I am there in slack.. can you share your slack URL in slack.
I need the exact image logo needed to add in stripe popup.
Thanks for your response.

**Comment by tansaku** [comment]
@ajay2507 - if you sign up at https://www.agileventures.org you'll get an invite to our Slack.  Let's get you in the #websiteone channel for quick coordination when needed :-)

all our images etc are in https://github.com/AgileVentures/agileventures-profile

**Comment by ajay2507** [comment]
@tansaku  Thanks. I will make this change and I will let you know.

**Comment by ajay2507** [comment]
@tansaku can you check the Logo and position, color of logo. Please let me know if u have any concern.
<img width="277" alt="agile" src="https://cloud.githubusercontent.com/assets/21375014/24786666/437bc1e0-1b31-11e7-9b67-84d7c97e96e2.png">

**Comment by tansaku** [comment]
@ajay2507- thanks for working on this!

I was thinking we would use the logo without the name on it, i.e. just the orange thing: e.g. https://github.com/AgileVentures/agileventures-profile/blob/master/full_logo2.png

**Comment by ajay2507** [comment]
@tansaku  - Thanks for your valuable input.
I will include this icon and will let you know.

**Comment by ajay2507** [comment]
@tansaku  Can you check this one. Is it fine?
<img width="244" alt="agile1" src="https://cloud.githubusercontent.com/assets/21375014/24820431/fbc9771c-1bb6-11e7-803c-8e620f82c7ac.png">

**Comment by tansaku** [comment]
@ajay2507 - that looks great!

**Comment by ajay2507** [comment]
@tansaku  thanks for your response. I will submit the pull request.

**Comment by ajay2507** [comment]
@tansaku  I have included the PR 
[https://github.com/AgileVentures/WebsiteOne/pull/1633](url)
