### ISSUE TITLE
Notify premium users when their card cannot be charged

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1255]
```
As a premium member
I would like to be notified when AV can't charge my card for x reason
In order for me to resolve the issue
```

I recently lost my card and had to block it. Stripe most likely failed to charge me this month but I didn't get any notification. I only remembered now when looking at the story about updating card info 😉

**Comment by tansaku** [comment]
I get an automated notification - we'll need to link user accounts to cards to add another layer of notification - but we're doing that as part of data-migration on the card-update deploy ... although if we are going to reliably support this, we'll need to get emails from users when they sign up ...
