### ISSUE TITLE
Edit premium user page title

### ISSUE THREAD

**Issue by Maroo-b** [AgileVentures/WebsiteOne#1262]
Edit page title for premium users

![selection_010](https://cloud.githubusercontent.com/assets/7128972/18467815/beb25e5a-79a1-11e6-99fa-ef3a244be555.png)
## Expected Behavior

It shouldn't see edit button in premium page
## Possible Solution

the edit action should be enabled to admin only
## Steps to Reproduce (for bugs)

1. Visit premium user page as signed in user

**Comment by mattlindsey** [comment]
Obsolete
