### ISSUE TITLE
Failing Charge Acceptance test

### ISSUE THREAD

**Issue by Maroo-b** [AgileVentures/WebsiteOne#1267]
Error message in cucumber test: features/charge_activity.feature
## Current Behavior

Error message **Unable to find field "Email" (Capybara::ElementNotFound)** in step **When I fill in appropriate card details for premium** (for all steps related to filling stripe popup)

For debugging I used save_and_open_page step and I find the following error in the page:

```
{
  "error": {
    "type": "invalid_request_error",
    "message": "Requested URL not found"
  }
}
```

**Comment by tansaku** [comment]
thanks @Maroo-b feel free to throw in the full stack trace next time :-)  great to see the specific line numbers ... identify the particular scenario that fails - although perhaps all are failing.

Also can you do `git status` and show us what files are being generated?

**Comment by Maroo-b** [comment]
@tansaku here is the full stack

**Scenario: Sign up for premium membership**
`When I fill in appropriate card details for premium     # features/step_definitions/charge_steps.rb:1
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/charge_steps.rb:6:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/charge_steps.rb:5:in `/^I fill in appropriate card details for premium(?: for user with email "([^"]*)")?$/'
`

**Scenario: Sign up for premium plus membership**

`When I fill in appropriate card details for premium plus    # features/step_definitions/charge_steps.rb:29
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/charge_steps.rb:32:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/charge_steps.rb:31:in `/^I fill in appropriate card details for premium plus$/'
      features/charge_activity.feature:32:in `When I fill in appropriate card details for premium plus'
`

**Scenario: User decides to change membership**

`When I fill in updated card details for premium for user with email "tansaku+stripe@gmail.com"                  # features/step_definitions/charge_steps.rb:15
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/charge_steps.rb:20:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/charge_steps.rb:19:in `/^I fill in updated card details for premium(?: for user with email "([^"]*)")?$/'
      features/charge_activity.feature:40:in `When I fill in updated card details for premium for user with email "tansaku+stripe@gmail.com"'
`

--------------- **Git Status results** -------------------

I noted there is changes in VCR cassette file:
features/support/fixtures/cassettes/Charge_Users_Money/Sign_up_for_premium_membership.yml

the new URI is **https://checkout.stripe.com/v3/data/locales/en_au-beTBxEZgmtd8Pb2b5Tg.json** and it generate the following error as content:

`{
  "error": {
    "type": "invalid_request_error",
    "message": "Requested URL not found"
  }
}`

and there is new billy file in /req_cache 
**features/support/fixtures/req_cache/charge_users_money/sign_up_for_premium_membership/get_checkout.stripe.com_05744752451ca0628c01db70c764e673ffa9bca4.yml**

it contains the same URI with the same error msg as content

**Comment by tansaku** [comment]
aha, so we can see that your locale is "en_au" - so what you need to is take the contents of the file for the en_us or en_uk and put that in that file, and then en_au will work - at least that's how I sorted it for @diraulo one time

**Comment by tansaku** [comment]
stubbing and/or changing locale is also an option I guess - although haven't done that myself

**Comment by Maroo-b** [comment]
I copied the content from existent files. Now the test pass the step of filling the form but it fails afterwards when verifying the presence of successful notification for exp: 
**Thanks, you're now an AgileVentures Premium Member!**

failure message for **Scenario: Sign up for premium membership**

```
Then I should see "Thanks, you're now an AgileVentures Premium Member!" # features/step_definitions/basic_steps.rb:178
      expected to find text "Thanks, you're now an AgileVentures Premium Member!" in "Log in Sign up ABOUT PROJECTS MEMBERS PREMIUM EVENTS GETTING STARTED Agile Ventures Premium Membership Further details The price for Premium Membership is £10.00/Month 7 day free trial! No charge for 7 days Sign Me Up For Premium! Learn More About Us Getting Started Dashboard Social Facebook Twitter Our Sponsors Craft Academy AirPair Becoming a sponsor AgileVentures - Crowdsourced Learning Contact us Send a traditional email to info@agileventures.org." (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:180:in `/^I should( not)? see "([^"]*)"$/'
      features/charge_activity.feature:26:in `Then I should see "Thanks, you're now an AgileVentures Premium Member!"'
```

I guess it will be better to work on this ticket first https://github.com/AgileVentures/WebsiteOne/issues/1265 but it requires feedback of active developers on the project to decide which solution to use.

**Comment by Maroo-b** [comment]
@tansaku thanks that sorted the issue for me too. I'll investigate stubbing locale if possible.

**Comment by Maroo-b** [comment]
@tansaku I have been trying different solutions to stub the locale, and I saw on Stripe documentation it's possible to set the locale on the frame ( https://stripe.com/docs/checkout#supported-languages)

I set `data-locale` value  to 'en-US' and the tests pass

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/views/charges/premium.html.erb#L24

**Comment by tansaku** [comment]
@Maroo-b reflecting on this - I'm worried we've hard coded something we shouldn't have here ...

**Comment by Maroo-b** [comment]
@tansaku I agree that extracting it to a constant or using ENV variable is better, but regarding if we should display the checkout in other locale it depends on product owner decision, because in term of UI consistency it will be surprising for a user who is navigating a website in English and see a popup in different language like Spanish for example.

**Comment by tansaku** [comment]
agreed @Maroo-b
