### ISSUE TITLE
failing acceptance test for update job

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1322]
https://travis-ci.org/AgileVentures/projectscope_mvp/builds/165086170

I suspect this will need a step locking down date and time definite ala Timecop or else the metric will be "0.0" because VCR's data is older than three weeks ago at this point.

**Comment by tansaku** [comment]
Issue moved to [AgileVentures/projectscope_mvp #42](https://github.com/AgileVentures/projectscope_mvp/issues/42) via [**ZenHub**](https://www.zenhub.com/)
