### ISSUE TITLE
"Hire me" link is visible on a users profile page when that user is logged in

### ISSUE THREAD

**Issue by c1505** [AgileVentures/WebsiteOne#1324]
## Current Behavior
"Hire me" link is visible on a users profile page when that user is logged in.  The link pops up a form that upon filling out, sends an email to the user.  It appears to me that this feature is meant to allow for people to contact users with job opportunities.  
![image](https://cloud.githubusercontent.com/assets/6599077/19194661/64aaaca8-8c7c-11e6-9afc-b72ef02ef960.png)
## Impact
The presence of the link for a logged in user makes the "Hire me" feature confusing at first glance.  
## Expected Behavior
When the user is logged in, they should not see the "hire me" link on their own profile page.

**Comment by tansaku** [comment]
makes perfect sense @c1505 - let's get this voted on :-)
