### ISSUE TITLE
refactor to allow for "on_my_own_page?" method or similar

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1331]
we'd like to have a clean way to check if the user is viewing their own page - might involve accessing current_user from a presenter of which there is some discussion here: http://stackoverflow.com/questions/6998830/accessing-rails-helpers-from-a-presenter-module

see discussion in https://github.com/AgileVentures/WebsiteOne/pull/1325

**Comment by Arepo** [comment]
There's a very nice Railscast on the topic: https://www.youtube.com/watch?v=QHsq6aFlP0U

**Comment by tansaku** [comment]
thanks @Arepo - this is estimated and ready to go if you're interested to work on it

**Comment by Arepo** [comment]
Yoink.
