### ISSUE TITLE
"Martin Fowler" scrum failed to ping slack today

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1333]
the "Martin Fowler" scrum failed to ping slack today - I see no errors in the agile-bot log - nothing in airbrake on wso production, nothing in production logs on WSO (in the time window I can reach) - so could be slack brown out - something somewhere else in our stack ... guess I'll file as issue on WSO GH

**Comment by mtc2013** [comment]
new hangout i just launched for wso pairing didn't ping slack now either @tansaku

**Comment by NickSchimek** [comment]
hmm This is pretty old. I take it we can probably close this as I'm not aware of any ongoing issues regarding this failure. Please reopen if this is still an issue.
