### ISSUE TITLE
Change dropdown for upcoming events filter to only include projects that have an upcoming event

### ISSUE THREAD

**Issue by c1505** [AgileVentures/WebsiteOne#1336]
Part of #1332 

As a user
On the upcoming events page
I want the dropdown for projects to filter from to only include projects that have an upcoming event
So that I don't see projects that don't have a current event
So that I can find the event I am interested in
#### Current state of the dropdown.   Many projects.

![image](https://cloud.githubusercontent.com/assets/6599077/19354051/625b732c-9133-11e6-8c13-a8102759c458.png)

**Comment by tansaku** [comment]
we might start this by only including active projects rather than worrying about only showing projects that have future events ...?
