### ISSUE TITLE
Refactor view logic into presenter

### ISSUE THREAD

**Issue by Arepo** [AgileVentures/WebsiteOne#1352]
Having introduced the change discussed in [issue 1331](https://github.com/AgileVentures/WebsiteOne/issues/1331), I'd like to refactor the Presenter to receive a view, per Ryan Bates' demo. That way we don't have to include a bunch of mysterious modules in the class itself and/or pass in objects (like current_user) that we first need to ask the view to generate.

Other refactorings on the same theme:
- Can we overwrite #respond_to? and #respond_to_missing? on the BasePresenter class, per [this advice](https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding)
- I think all the calls to 'presenter.user' throughout the app are redundant, since presenter's #method_missing will be passing messages straight to the user anyway - so we should be able save ourselves a few method calls.

**Comment by tansaku** [comment]
sounds good @Arepo
