### ISSUE TITLE
Convert footer view spec to Cucumber acceptance test

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1353]
`spec/views/layouts/layouts_footer.html.erb_spec.rb` should be written as a cucumber acceptance test instead.

**Comment by tansaku** [comment]
https://github.com/AgileVentures/WebsiteOne/blob/develop/spec/views/layouts/layouts_footer.html.erb_spec.rb

```rb

require 'spec_helper'

describe 'layouts/_footer' do
  it 'should render the Craft Academy link' do
    render
    expect(response.body).to have_link('', href: "http://craftacademy.se/english")
  end
end
```
