### ISSUE TITLE
Clean up repeating Events that are not maintained by owner

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1355]
There seems to be a lot events that are set up to repeat but not being run by the owner. I suggest that we create a mechanism to check if the last or 2 last event instances have been run and if not delete the event (or contact the creator and ask "what's up?")

**Comment by tochman** [comment]
We just got an  email with a pledge to clean up our events. 

"Hi, I am currently taking the CS169.2x course and I've been having difficulties finding pair programming partners, and I always see a lot of old events that where created with the repeat weakly option but probably never actually happen because the people who created them is no longer taking the course, please clean the old events that repeat weakly but are no longer active.

Thanks for your help.

Regards,

Cristian Zamora"

**Comment by tansaku** [comment]
thanks @tochman - we have a epic started for that: https://github.com/AgileVentures/WebsiteOne/issues/1339

I was just thinking though a quick fix might be a one off script to remove all repeating events that haven't had a hangout started in the last month.

There's a danger with a regular task given the youtubelive api google hangouts api failure that we've just had, that may require us to take a completely different approach to hangouts and events: 

http://stackoverflow.com/questions/40233393/start-a-hangout-on-air-button-for-youtube-livestreaming-api

**Comment by tochman** [comment]
Closing. Repeated issue.
