### ISSUE TITLE
Set up Docker for development environment

### ISSUE THREAD

**Issue by edmilsonefs** [AgileVentures/WebsiteOne#1368]
**To-do list**:
- [ ] Create Dockerfile .
- [ ] Create .dockerignore .
- [ ] Create docker-compose.yml .
- [ ] Support macOS, Gnu/Linux and maybe Windows.

_Note: The main focus on this ticker is to provide an easy setup allowing newcomers to jump into the code right away._

**Comment by touchps** [comment]
There is a issue that may come up later is the factor of authentication. By default the authentication callback for dev is set to url `http://localhost`

which may not be same when the applications is deployed using docker container.

**Comment by edmilsonefs** [comment]
> @touchps Let's be in touch later so we can work to solve your needs too.

**Current status**:
- I'm reviewing rails installation/configuration and studying docker in a clean install. 
- My next move will be create a docker dev environment for this project, then work on #1369 .

**Comment by tansaku** [comment]
@edmilsonefs any progress on this?

**Comment by edmilsonefs** [comment]
@tansaku Yes, today I will give a try. I read a lot about Docker and I think I'm more confident to make things going forward now.

**Comment by tansaku** [comment]
more or less :-)

**Comment by tansaku** [comment]
how's this going @edmilsonefs - something to be put back on the backlog for the moment?

**Comment by edmilsonefs** [comment]
@tansaku Not yet, if possible. 

I expect to resume the work here and put the progress in a PR so everybody can follow the evolution.

**Comment by tansaku** [comment]
@edmilsonefs looking forward to seeing your PR :-)

**Comment by tansaku** [comment]
@edmilsonefs any progress on this? should we put back into ready to allow someone else to work on it?

**Comment by edmilsonefs** [comment]
So sorry, many things going on. Please change as needed so someone else can work on it.
