### ISSUE TITLE
Paypal recurring payment paragraph display

### ISSUE THREAD

**Issue by sysrex** [AgileVentures/WebsiteOne#1391]
The paypal recurring information displays the paragraph tags

## Expected Behavior
No html tags should be displayed.

## Current Behavior

<img width="684" alt="screen shot 2016-11-11 at 09 44 59" src="https://cloud.githubusercontent.com/assets/769991/20211292/ba865e08-a7f5-11e6-82ef-8693672a6240.png">

**Comment by tansaku** [comment]
I think this is an issue with the paypal system that we don't have control over.  Maybe upgrading to paypal express would fix it ... see #1457
