### ISSUE TITLE
allow users to remove/de-activate their accounts

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1394]
would be good practice

**Comment by tansaku** [comment]
in particular I'd like to see the use of the Paranoiac gem to make this reversible

```
As an admin
So that I can allow users to leave the community
I would like to support account de-activation
```

**Comment by mattlindsey** [comment]
Note: Making things paranoid is the removal thing - so perhaps that's what we should focus on first - deactivation (and re-activation) is a whole separate thing
