### ISSUE TITLE
Add option for users to delete their account

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1421]
As a user
So that I can not use or be seen on the site
I want to be able to delete/deactivate my account

**Comment by tansaku** [comment]
@mattlindsey we do already have an option for the user to hide their profile.  I think we need the user story to reflect the user request which is that they don't want any more comms from AV, e.g.

```
As a member
So that I will not receive any communications from AV or other AV members
I want to be able to delete my account
```

and there is a related story

```
As an admin
So that I can help users who changed their mind or accidentally deleted their accounts
I want to be able to undo deletions
```

**Comment by mattlindsey** [comment]
@tansaku: I'm wondering what "will not receive any communications" means?  Is there anything extra to do, like remove them from a mailing list or slack?

**Comment by tansaku** [comment]
@mattlindsey not at the moment I think
