### ISSUE TITLE
Blank videos in project video list

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1428]
If an event is not recorded, it still shows up in the list.  
Maybe the description should be '[Not Recorded]'?  Opinions?

**Comment by mattlindsey** [comment]
Possibly the *blank?* function below in slack_service.rb is not working and should check for nil?

  def post_hangout_notification(hangout)
    return unless Features.slack.notifications.enabled
    return if hangout.hangout_url.blank?

**Comment by tansaku** [comment]
@mattlindsey I think we have this as an existing bug - @Arepo and I were working on it the other day ...

**Comment by tansaku** [comment]
and I think @diraulo just pushed out the fix
