### ISSUE TITLE
Sort project page by commit date

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1430]
As a user
In order to see which projects have been worked on lately
I would like to order the projects by last worked on date

**Comment by tansaku** [comment]
@mattlindsey there is already a background task pulling in github commit data for all the projects

**Comment by mattlindsey** [comment]
@tansaku Quick question: How and when to background tasks get run?  I see the code in github_commits_job.rb, but don't see where it's called.

**Comment by tansaku** [comment]
you're working on this right @mattlindsey ?  we're using  https://elements.heroku.com/addons/scheduler to run rake tasks every 24 hours

![current WSO jobs](https://www.dropbox.com/s/x2918ft04mwj73v/Screenshot%202016-11-28%2018.01.28.png?dl=1)

**Comment by mattlindsey** [comment]
Note that current method for querying github, Octokit, does not seem to support getting the latest commit.  
So we have to figure out how to call this api function to get the commits, then look at the date for the first one -- which is the latest:
https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

**Comment by mattlindsey** [comment]
I solved the problem above, but unfortunately it uses a deprecated method '#commits' in Octokit.   I submitted a WIP PR anyways, so hopefully we can find another method to get the latest commit.

**Comment by mattlindsey** [comment]
Fixed now. Ready for review.
