### ISSUE TITLE
slack invitations not working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1434]
our slack invitations are definitely not working - I still have manual requests, and I can see from the pending invitations log (35K+ pending!) that there have been no auto-invites since Nov 8th.  

I thought we had set up an error message system to tell us when this was failing, but apparently not ... must look into this ...

**Comment by tansaku** [comment]
as an emergency measure I just invited the last 160 or so people who signed up

**Comment by tansaku** [comment]
this is very much not working as hoped for ...

**Comment by mattlindsey** [comment]
@tansaku:  Could you confirm that the following is set to TRUE in heroku prod:

features:
   slack:
    invites:
      enabled: <%= ENV['SLACK_INVITES_ENABLED'] %>

**Comment by mattlindsey** [comment]
I successfully used my own Slack AUTH token to send an invite email to myself.
Are we sure that the production Slack token (SLACK_AUTH_TOKEN in Heroku) is valid and working?

FYI:  The page to check/generate a new token is https://api.slack.com/web#auth

**Comment by mattlindsey** [comment]
Looks like SLACK_INVITES_ENABLED was not set (to true) in Heroku.
Sam has set it, so this should be fixed.
