### ISSUE TITLE
Hangout videos missing/won't play for #metplus project ("Americas "Dave Thomas" Scrum and Pair Hookup")

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/WebsiteOne#1446]
## Expected Behavior
I expect to be able to see recordings of hangouts in the project page as well as "past events" page, and replay each of those.

## Current Behavior
The video page on the project page shows this:

<img width="462" alt="screen shot 2016-12-05 at 2 38 46 pm" src="https://cloud.githubusercontent.com/assets/9968213/20904406/5f2ec63c-bb0d-11e6-91b1-884568718a24.png">

The links to video (below the empty space where a YT view should be embedded) do not work.

The associated videos in the "past events" page show this error when replay is attempted:

<img width="796" alt="screen shot 2016-12-05 at 5 09 38 pm" src="https://cloud.githubusercontent.com/assets/9968213/20904509/d32ede28-bb0d-11e6-86c8-b5ba278d1d83.png">

Questions from Sam on Slack and my answers:

<img width="834" alt="screen shot 2016-12-05 at 5 12 36 pm" src="https://cloud.githubusercontent.com/assets/9968213/20904549/0b9dcc2e-bb0e-11e6-8dac-fa487175b0c0.png">

## Your Environment
I am on OS X.  Vijaya is running linux in a VM env on windows.

**Comment by tansaku** [comment]
thanks @patmbolger - I notice that it's working again now that the latest video is a working one:

http://www.agileventures.org/projects/metplus#video

![](https://www.dropbox.com/s/vy7opbsw1rll4ss/Screenshot%202016-12-06%2012.16.15.png?dl=1)

so I think this is an issue for when the most recent video is a dud, breaking playback for the others ...

**Comment by patmbolger** [comment]
It still appears broken for me.  Can you check again?

<img width="446" alt="screen shot 2016-12-07 at 5 56 52 pm" src="https://cloud.githubusercontent.com/assets/9968213/20990413/9c1b67f4-bca6-11e6-9f99-e72ae2474916.png">
