### ISSUE TITLE
'Start Hangout on Air' button does not appear in Firefox

### ISSUE THREAD

**Issue by ragesoss** [AgileVentures/WebsiteOne#1477]
## Expected Behavior
The 'Start Hangout on Air' button appears when the time is right on an event page. This works as expected for me in Chrome.

## Current Behavior
In Firefox (45.6.0, on Debian) the button does not appear for me. Just before the start time, for example:

![screenshot from 2017-01-04 10-59-37](https://cloud.githubusercontent.com/assets/848483/21655613/8d5f9530-d26f-11e6-812a-35517cfc4a55.png)

**Comment by c1505** [comment]
Just checked from one windows machine chrome version 53.0.2785.143 and also didn't see the 'Start a Hangout on Air' button.  Both from the website in production and with my local dev version.  I'll check on chrome and firefox on a different machine later today.  

Can you check again to verify that it does work on chrome for you currently?

**Comment by ragesoss** [comment]
It only shows up within 10 mins of the start time, when working. It does work on Chrome; I successfully used it yesterday.

**Comment by c1505** [comment]
Ok.  Just tried it on a mac on Chrome, Firefox, and Safari.  Currently working for all 3.  Chrome version 55.0.2883.95.  Firefox 46.01.  Safari 9.3.1 .  Strange.

**Comment by ragesoss** [comment]
Oooh... I bet it's because of AdBlockPlus. I should have thought to check.

**Comment by c1505** [comment]
I haven't looked into how this button works, but it wasn't working for me on my work network.  No adblock.  Was it on the same network and same computer when you experienced chrome working and firefox not working?  Also curious if you have tried to start a google hangout from firefox before.  Just trying to figure out the potential reasons why it wouldn't show up so we can change it to show a helpful error message or something other than just the silent failure.

**Comment by c1505** [comment]
A little bit more digging around.  The button only shows up with communication with the google api https://developers.google.com/+/hangouts/button.  It uses javascript and the code is here:
hangout_button.js
show.html.erb line 17

I assume we should be able to add some helpful error message.  Still curious why it isn't working for you in particular with firefox.

**Comment by c1505** [comment]
Also I can't currently start a hangout on air from the button.  After hangouts opens up, I get this error message 

![image](https://cloud.githubusercontent.com/assets/6599077/21757539/5a339b06-d5fe-11e6-8c6c-59804d42f211.png)

**Comment by mattlindsey** [comment]
@c1505 I think maybe there's some setup you need to do to enable 'live' events.
Try going to https://www.youtube.com/my_live_events and see if you can start one.
I had the same issue a few months ago.

**Comment by c1505** [comment]
Thanks @mattlindsey .  That did it.  Following this worked https://support.google.com/youtube/answer/7083786?hl=en&ref_topic=6136989 .

**Comment by ragesoss** [comment]
I got a chance today to try it out, and it does indeed work for me on Firefox after disabling AdblockPlus.

I think having a placeholder explaining the 10 minute thing (and perhaps a note about disabling adblockers) would be a good solution.

**Comment by mtc2013** [comment]
so is this relevant still? should this be closed?  perhaps we should figure out how to detect if ad block is installed, or provide a notice of some kind that says "Don't see the hangout link?  Browser plugins such as AdBlock can interfere with google hangouts" if its time to display the button.

I say this since we've had this bug before

**Comment by tansaku** [comment]
@mtc2013: @ragesoss 's suggestion is a good one - we could certainly have a placeholder explaining the 10 minute thing (@tochman was caught out by that the other day) and that we recommend disabling adblockers - could have a failure handling that loads the adblocker explanation if the google hangout button fails to load ...

**Comment by NickSchimek** [comment]
@ragesoss @tansaku Was this fixed? I just tried using FireFox and Ad block plus and had no issues, If this is still an issue what OS, Firefox version, and ABP version are you seeing it on?

**Comment by ragesoss** [comment]
I have tried it for a while, and for several Firefox version bumps. If it
seems fixed, we should close the issue.

**Comment by tansaku** [comment]
@NickSchimek sounds like we can close - thanks @ragesoss
