### ISSUE TITLE
Cannot build puma 3.4.0 gem on Debian sid

### ISSUE THREAD

**Issue by ragesoss** [AgileVentures/WebsiteOne#1479]
Because of recent ssl changes in Debian, the puma version required by this project doesn't build.

There's a fix in the incoming puma 3.7.0, which should be released shortly: https://github.com/puma/puma/pull/1178

Upgrading to the git version of puma fixed the issue for me; I can open a PR as soon as the new gem is out.

**Comment by mattlindsey** [comment]
Closing old issues...
