### ISSUE TITLE
Upgrade to Premium Plus button - what plan does it refer to?

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#1494]
On some members screens, eg. http://www.agileventures.org/users/bryan-yap, I see an "Upgrade to Premium Plus" button.

What membership level does this relate to? 
On the pricing page: http://www.agileventures.org/pricing
I see Free, Premium, Premium Mob and Premium F2F.

I would expect the plan names to be consistent on all pages - so the "Upgrade" plan should refer in this instance to "Premium Mob" or "Premium F2F"

**Comment by tansaku** [comment]
yeah we've got to move over the upgrade pathway to the new plans - that's next on my list

**Comment by freeranger** [comment]
Perhaps store the plan details all in one place so they update automatically everywhere if the change/you add more plans?

DRY!

**Comment by tansaku** [comment]
@freeranger yes, they are all stored in a Plan table in the DB as of a few weeks back
