### ISSUE TITLE
The email link on a members pages results in a 404 error

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#1495]
On a member's page where there is an email link, e.g.
http://www.agileventures.org/users/patrick-bolger

When I click on the email link (http://www.agileventures.org/users/patmbolger@gmail.com) I get a 404 error.

I would expect this link to either cause my email program to open up to send them an email, or that an email form is opened up in the website for me to send them a message.

**Comment by tansaku** [comment]
good catch @freeranger - looks like we need a mailto: link

**Comment by ManuelCostanzo** [comment]
Hello, i fixed this error:

in views/users/profile on line 34 change:
`<%= presenter.email_link %>`
to:
`<%= mail_to presenter.email %>`

I sended pull request #1535 

Bye :)
