### ISSUE TITLE
investigate why these four cukes take so long

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1496]
1 features/events/edit_past_event.feature		
2 features/events/list_repeating_events.feature	
3 features/hookups/hookups_pending.feature		
4 features/hangouts/edit_hangout_url.feature

![](https://dl.dropbox.com/s/0k6dd9ykrxb61bq/Screenshot%202017-01-13%2014.29.17.png?dl=1)

according to semaphore each is taking longer than 40 seconds on average

from https://semaphoreci.com/agileventures/websiteone/insights

**Comment by tansaku** [comment]
Just examining `features/events/edit_past_event.feature` using: 

```
time be cucumber features/events/edit_past_event.feature
```

because (I assume) our time jumping is messing with cucumbers ability to measure the time.

It seems like the background step is expensive here - we could replace with something that creates the events directly via AR for something faster, but less realistic ...

**Comment by tansaku** [comment]
the last two actually run pretty fast for me locally:

```
→ time bec features/hookups/hookups_pending.feature

real	0m11.980s
user	0m9.273s
sys	0m2.204s

→ time bec features/hangouts/edit_hangout_url.feature

real	0m17.007s
user	0m13.384s
sys	0m2.737s
```

**Comment by tansaku** [comment]
the events editing does seem a lot slower locally:

```
→ time bec features/events/edit_past_event.feature

real	0m49.365s
user	0m41.144s
sys	0m5.169s
```

but not list_repeating events ...

```rb
→ time bec features/events/list_repeating_events.feature

real	0m10.841s
user	0m8.461s
sys	0m2.013s
```

I wonder if the semaphore stats are all time and including older versions of the files that had more in them ...

**Comment by tansaku** [comment]
@alexander-kh reviewed and couldn't see a way to reduce the time - maybe we just need to delete some tests ...

**Comment by NickSchimek** [comment]
@tansaku I reviewed this test: `features/events/edit_past_event.feature` and have found a way to improve it by 2x.
Test item 2 and 3 listed above run really fast for me. Less than a second as they only have 1 short scenario to test.
Test item 4 can be improved by implementing the same techniques used in test item 1
