### ISSUE TITLE
[Airbrake] [Production] The action 'show' could not be found for SubscriptionsController

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1498]
**Airbrake error:** [#9531](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/1863679370377819531)
**Airbrake project:** websiteone-production

**Error type:** `AbstractController::ActionNotFound`
**Error message:** `` The action 'show' could not be found for SubscriptionsController ``
**Where:** `subscriptions#show`
**Occurred at:** Jan 15, 2017 09:18:13 UTC
**First seen at:** Jan 15, 2017 09:18:13 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)

**URL:** [http://www.agileventures.org/subscriptions/upgrade](http://www.agileventures.org/subscriptions/upgrade)
**File:** `[GEM_ROOT]/gems/actionpack-4.2.6/lib/abstract_controller/base.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:132:in process
[GEM_ROOT]/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in process
[GEM_ROOT]/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in dispatch
[GEM_ROOT]/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in dispatch
```

**Comment by mattlindsey** [comment]
Sam Joseph [9:55 AM] 
at least some kind of error - whether it should be a 404 is another matter, but in the normal course of things no one would naturally hit that endpoint, unless we've accidentally got a link to it in the site, or there's something else weird with our system ... e.g. strange redirection from some other part of the controller

Matt Lindsey [9:58 AM] 
maybe just somebody fooling around with the site?  maybe as long as it doesn't happen again we are ok?

**Comment by tansaku** [comment]
looks like we could update the route to:

```
  resources :subscriptions, only: [:create, :edit, :update, :new]
```

and maybe create a request spec that hits the show endpoint and checks we get the right error (probably not a 404)
