### ISSUE TITLE
Refactor Event Model

### ISSUE THREAD

**Issue by c1505** [AgileVentures/WebsiteOne#1501]
The class is long and hard to reason about.  It seems to make sense to at least separate the methods that deal with IceCube and recurring events into a separate class.

**Comment by blackknight75** [comment]
@c1505 A good refactor? Sounds fun. Mind if I take a shot at it? Could we talk about how you want this to look. I will take a look at the repo and get some ideas.

**Comment by c1505** [comment]
Please do @blackknight75 !  I haven't looked at it in awhile, but would be happy to talk and/or pair on it.  Here is the fork when I was working on it https://github.com/c1505/WebsiteOne/tree/SPIKE_refactor_events .
