### ISSUE TITLE
Project page layout : http://www.agileventures.org/projects?page=2

### ISSUE THREAD

**Issue by mdautrey** [AgileVentures/WebsiteOne#1504]
## Expected Behavior
Supporters'logo, in the right panel, should all be the same size.
## Current Behavior
Drie's logo is very big. The whole layout is not very good.

## Possible Solution
Add an img width (em) to each logo in the right panel

## Steps to Reproduce (for bugs)
http://www.agileventures.org/projects?page=2

## Context
It doesn't affect me but the layout is unsightly
## Your Environment
OS : Debian 8 IA64
Mozilla Firefox 45.6.0

![pagelayout](https://cloud.githubusercontent.com/assets/6020351/22060991/4c9a92ac-dd73-11e6-80c2-06aec6c19acf.jpg)

**Comment by tansaku** [comment]
thanks for reporting this @mdautrey - looks like a browser issue - that thing is the right size on a lot of other browsers ... wonder if there's a simple fix ...

**Comment by mdautrey** [comment]
You're right, it's neither urgent nor important
