### ISSUE TITLE
github last updated at still not working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1513]
this is still not working as expected.

I was ultimately able to get it to work from the rails console like so:

```rb
Project.all.each {|p| begin p.last_github_update = client.repo("#{p.github_repo_name}/#{p.github_repo_user_name}").pushed_at ; p.save ; rescue ; end }
```

but I'm not sure that the github commits job will do what we hope it will - another round of more rigorous testing required I think ...

**Comment by mattlindsey** [comment]
Yes.  It seems that the 'github commits job' was not a good model to follow.  
Maybe start over with new tests, new 'github interface module' and job?   And probably better to test with some actual data too?
