### ISSUE TITLE
scrums showing live on home page too long after finish

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1517]
Events seem to be staying live on the home page and pop up long after they have finished

![](https://www.dropbox.com/s/c8sq020s1kc2ww9/Screenshot%202017-01-23%2014.38.51.png?dl=1)

![](https://www.dropbox.com/s/r3jnmoeu02yk013/Screenshot%202017-01-23%2014.36.54.png?dl=1)

@c1505 could this be related to the changes you made to have live events stay in the upcoming events page longer?

**Comment by c1505** [comment]
I'll look into.  Probably won't be able to spend too much time until later tonight.

**Comment by tansaku** [comment]
@c1505 if this is what I think it is we'll need a new feature test checking the home page

**Comment by tansaku** [comment]
@c1505 I'm just looking at this code here:

```html
<% if event.present? %>
  <p>
    <%= link_to event['name'], event_path(event['id']) %>
    <% start_time = event.next_occurrence_time_attr.to_datetime %>
    <% if start_time < Time.now %>
      is live!
      <% if event.last_hangout.try!(:live?) %>
        <%= link_to 'Click to join!', event.last_hangout.hangout_url %>
      <% end  %>
    <% elsif start_time - 1.minute < Time.now %>
      about to start...
    <% else %>
      in <%= display_countdown(event) %>
  <% end %>
  </p>
<% end %>
```

in app/views/layouts/_event_link.html.erb

**Comment by tansaku** [comment]
and the ApplicationController has this method which gets the next scrum:

```rb
  def get_next_scrum
    @next_event = Event.next_occurrence(:Scrum)
  end
```

**Comment by tansaku** [comment]
I'm thinking about how your PR https://github.com/AgileVentures/WebsiteOne/pull/1474/files might be affecting `Event.next_occurrence`

```rb
  def self.next_occurrence(event_type, begin_time = COLLECTION_TIME_PAST.ago)
    events_with_times = []
    events_with_times = Event.where(category: event_type).map { |event|
      event.next_event_occurrence_with_time(begin_time)
    }.compact
    return nil if events_with_times.empty?
    events_with_times = events_with_times.sort_by { |e| e[:time] }
    events_with_times[0][:event].next_occurrence_time_attr = events_with_times[0][:time]
    return events_with_times[0][:event]
  end
```

**Comment by tansaku** [comment]
looks like the change to `COLLECTION_TIME_PAST.ago` might have caused this.

I'm thinking about a hotfix because this is kind of a blocker in production, but we should really wrap in a cuke ...

**Comment by c1505** [comment]
yea the quick and dirty thing i think would be to change the application controller method to 
```
def get_next_scrum
    @next_event = Event.next_occurrence(:Scrum, 15.minutes.ago)
end
```
From first glance, the view logic and that next_occurrence method don't really work as expected.  It wasn't problematic before because the method only looked back 15 minutes.  The scrums further apart than that in time.  

I can work on the view logic and the next_occurrence method tonight, but it probably won't be until after you are asleep.  I'll submit a PR for the hotfix change just to check that the all the tests still pass.

**Comment by tansaku** [comment]
@c1505 just thinking about a hotfix of adding an additional constant:

```rb
  COLLECTION_TIME_PAST = 300.minutes
  FRONT_PAGE_COLLECTION_TIME_PAST = 15.minutes

  def self.next_occurrence(event_type, begin_time = FRONT_PAGE_COLLECTION_TIME_PAST.ago)
    events_with_times = []
    events_with_times = Event.where(category: event_type).map { |event|
```

I think the constant being used in two places - one of them affecting the events page and another affecting the front page and popup

**Comment by tansaku** [comment]
I just ran the hotfix through tests locally and they passed - I might try pushing out and rolling back if it's broken.

It seems we don't have a test that checks how long this front-page/pop-up that would have caught this bug ...

**Comment by c1505** [comment]
what is affecting the events page other than the popdown that is across the whole site?  probably does make more sense to make the change where you are making it though since that where it was changed when the problem was introduced.

**Comment by tansaku** [comment]
@c1505 yeah, I'm just thinking about whatever would be the simplest immediate fix, since currently the site is showing the kent beck scum live and that'll block the americas scrum link ... so I'll push this out, and roll back if it causes other problems

if you could separately take a longer slower look at this with tests that would be great - potentially the ultimate fix will be different from my hotfix ...

**Comment by tansaku** [comment]
I'm pushing to staging to get the build green ... hope to roll out the hotfix shortly

**Comment by c1505** [comment]
Sounds good :)  Thanks

**Comment by tansaku** [comment]
@c1505 hotfix deployed and looks like it's working - i'll pull back in the develop branch

**Comment by tansaku** [comment]
I'm concerned that the hotfix might have other side effects - we'all see tomorrow
