### ISSUE TITLE
Convert Sign up links into big, orange buttons

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1523]
```
As an AgileVentures Admin
So that more people ultimately sign up for paid plans
I would like prominent buttons for sign up on the plan description pages
Whereas currently they are simply hyperlinks
```

![](https://www.dropbox.com/s/i3blyqqb38rqd26/premium%20plan%20description.png?dl=1)

**Comment by FedericoEsparza** [comment]
I think the _Sign up_ links in the individual plan description pages should be *huge, orange buttons* and *not* barely visible links

**Comment by tansaku** [comment]
@federicoesparza - agreed! can you post in those assets you put in the slack channel?

**Comment by FedericoEsparza** [comment]
It's just a close up screenshot of the current hyperlink:
![](https://www.dropbox.com/s/tgpqagn6hodkgkx/premium%20sign%20up%20link.png?dl=1)

**Comment by tansaku** [comment]
@lollypop27 maybe we can use the same elements you've used on the premium pricing page?

**Comment by FedericoEsparza** [comment]
![Google-NOT_G+](https://www.dropbox.com/s/sg6m0t9gz8u7sll/Google-NOT_G%2B.png?dl=1)
 
I should probably create another ticket, but since this ticket is being discussed today, and we've discussed both these Sign Up button/hyperlinks at the same time several times, I'll reference it here.
 
**It _might_ be the case that many new visitors aren't signing up** when they go to the regular sign up page. **because they don't have a Google+ account**, although almost **everyone has a gmail/google** account.
 
![users-sign_up](https://www.dropbox.com/s/0zgr7kgpfh1ozaa/users%3Asign_up.png?dl=1)
 
If they sign up, they're invited to Slack, which makes it more likely that they'll sign up for Premium.
 
**We should change the button**, since they'll be prompted for permissions by Google anyway.
 
Here's the svg link to the new icon:
https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/8215f6659adc202403198fef903a447e/sign-in-with-google.svg

**Comment by tansaku** [comment]
@FedericoEsparza - thanks - could you open another ticket for this? I totally agree we should address it, but it is clearly another issue

**Comment by mtc2013** [comment]
@here i've made some edits in mercury editor addressing this issue

**Comment by arun1595** [comment]
I made some quick changes to the button in dev tools. How about the following?

![image](https://cloud.githubusercontent.com/assets/7039523/23565309/0cb82be0-0073-11e7-961f-0985987490eb.png)

**Comment by arun1595** [comment]
Also, I think we can change the CTA text to something along the lines of '**Level up Now!**'

**Comment by tansaku** [comment]
@arun1595 thanks - do you want to share the CSS for the new button?

**Comment by arun1595** [comment]
@tansaku The current styling looks much better. Here's what I came up with(on top of the existing styles)

```
{
    font-size: 1.3em;
    line-height: 2em;
    text-transform: uppercase;
}
```
but there's an issue with the current styling. It breaks when the viewport width is less than 600px.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/7039523/23621563/445f523a-02c1-11e7-974a-8531747a8ca3.png)


It is easy enough to fix. We just gotta bump the width of the button to 80% on device widths less than 700px.

**Comment by tansaku** [comment]
@mtc2013 any thoughts on the above ^^^

**Comment by mtc2013** [comment]
http://www.agileventures.org/premium

I made a quick change to use white-space; normal; which makes it break the text across multiple lines when it's not wide enough.  The font size could be dynamically shrunk.

**Comment by tansaku** [comment]
@mtc2013 cool!

@arun1595 @FedericoEsparza what do you think?

**Comment by FedericoEsparza** [comment]
It works great. Nice job, @mtc2013.
 
Don't forget to add the button to the most important page: http://www.agileventures.org/free
 
`Get Started Now` could work as the button text.

**Comment by mtc2013** [comment]
@FedericoEsparza @tansaku the free page had a button.  shall we close this issue?

**Comment by FedericoEsparza** [comment]
@mtc2013 I would say that we can close it. I noticed you got it done. 

The arrow cursor switches to a pointing hand cursor when you mouse over it, so it's obviously clickable, even though the Mercury Editor inhibits the color change.
 
Thanks for getting it done, Michael. Good work.
