### ISSUE TITLE
Video for "Americas" scrum, Jan 24, 2017, not showing up on AV site

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/WebsiteOne#1527]
In the "past events" view, when I click on the scrum link, this appears:

<img width="803" alt="screen shot 2017-01-24 at 2 25 38 pm" src="https://cloud.githubusercontent.com/assets/9968213/22263020/036ed372-e241-11e6-83c5-3386e7954bd2.png">

**Comment by tansaku** [comment]
@patmbolger we've had this before haven't we?  is the video on your youtube account?  can you paste in the link?

**Comment by patmbolger** [comment]
Yes, we've seen this movie before ..... https://www.youtube.com/watch?v=byi1Go7kd7Q

**Comment by tansaku** [comment]
thanks @patmbolger - hmm ... we are discovering some EventInstance weirdness that might be related to this ...

**Comment by tansaku** [comment]
@patmbolger I was just looking at your page on AV http://www.agileventures.org/users/patrick-bolger

![](https://www.dropbox.com/s/ghuqaacuzj082ff/Screenshot%202017-02-09%2009.55.54.png?dl=1)

and it's odd that some of your videos come through and not others.  I wonder is there some pattern about which browser you are using, or which youtube account that's causing some of these to fail and not others?

I wonder if you have more than one youtube/google account and perhaps one of them is not youtube broadcast enabled?  I know @mattlindsey had a youtube enabling issue before that stopped him broadcasting ...
