### ISSUE TITLE
Should we make the button not display when the user is signed in already?

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1536]
<img width="1341" alt="screen shot 2017-01-30 at 12 13 43 pm" src="https://cloud.githubusercontent.com/assets/3909918/22433411/423a29f4-e6e6-11e6-803c-2806e51db11a.png">

**Comment by mtc2013** [comment]
So per @tansaku let's scope this out as just removing the button or reinserting what was originally there when a user is signed in.

**Comment by tansaku** [comment]
@mtc2013 created #1541 based on our other discussion
