### ISSUE TITLE
Add Tags To Projects 

### ISSUE THREAD

**Issue by hin101** [AgileVentures/WebsiteOne#1539]
We should either add tags to projects or state the tech stack used. This would be handy not only for newcomers but anyone who wants to work on a project for a specific tech stack.

**Comment by weedySeaDragon** [comment]
consider using the [acts-as-taggable-on gem](https://github.com/mbleigh/acts-as-taggable-on)

**Comment by tansaku** [comment]
@patrickbolger - you were thinking of adding a document related to this right?

**Comment by patmbolger** [comment]
Yes, I will add to an existing doc on the wiki.

**Comment by Romusc** [comment]
I'll start working on this

**Comment by tansaku** [comment]
Hi @Romusc - are you in our slack instance?

**Comment by Romusc** [comment]
Hi @tansaku, no I am not. I am trying to get involved in open source and since I saw this issue was up-for-grabs I figured I would have a go at it. I don't think I can claim an issue if I'm not a project owner so I thought I should better comment it. Let me know if that's not the way to go! I would gladly join the Slack.

**Comment by tansaku** [comment]
Hi @Romusc - great stuff - we'd love to get you involved.  If you go to http://www.agileventures.org and sign up you'll get an invite to our slack - or just give me your email.

Getting the project setup can sometimes be a little involved so it's great to be able to get support over slack - but happy to help you through github messages as well :-)

**Comment by Romusc** [comment]
thanks @tansaku I will follow the official AgileVenture getting started guide that makes more sense!

**Comment by sammysgame** [comment]
Hi, this is my first time wanting to contribute to open source projects and I think it will be cool if I get to work on this.

**Comment by tansaku** [comment]
welcome @sammysgame - have you joined our Slack instance? if you sign up at https://www.agileventures.org you'll get an invite and we can do real time text chat in Slack - make sure you're all set up to contribute :-)

**Comment by sammysgame** [comment]
Hi @tansaku Thanks for the comment. Going to join Slack, right away...

**Comment by tansaku** [comment]
@sammysgame did you get the invite?

**Comment by sammysgame** [comment]
Yes, and I have joined...

**Comment by ModdedGamers** [comment]
Hey @tansaku this is my first Github project ever, what should I do?

**Comment by tansaku** [comment]
hi @ModdedGamers - have you programmed in ruby or rails before?  If not, what have you programmed in?  Let's see if we can find you a good starting place :-)

**Comment by ModdedGamers** [comment]
@tansaku I have not in either of those but I have done some basic Bootstrap, HTML, and JS. Thanks!

**Comment by tansaku** [comment]
that's great @ModdedGamers - have you joined the #websiteone slack channel?

**Comment by ModdedGamers** [comment]
Yes I have!
