### ISSUE TITLE
most recent commit for a project is not correct (and so sorting is wrong)

### ISSUE THREAD

**Issue by weedySeaDragon** [AgileVentures/WebsiteOne#1540]
## Expected Behavior
The project sort order is not working correctly:  SHF-Project is very active, and yet it is not showing up near the top of the list of projects.
Ref: #1430, #1458, #763 

## Possible Solution

I think it has to do with this:
https://github.com/AgileVentures/WebsiteOne/blob/419653cfd3168455af479cb6a3681ffc541e071a/app/jobs/github_commits_job.rb#L12

**github_last_updates_job.rb:**
```
 def run
    Project.with_github_url.each do |p|
      begin
        p.last_github_update = client.repo("#{p.github_repo_name}/#{p.github_repo_user_name}").pushed_at
        p.save
      rescue StandardError
        Rails.logger.warn "#{p.github_url} may have caused the issue. Commit terminated for this project!"
      end
    end
  end
```

The last commit looks to me like it's retrieved only for `p.github_repo_user_name`.  
Am I reading this all correctly?  

What we really want is the most recent commit to the default branch by _any user,_ right?

I can help by updating the spec / feature (assuming I'm right).

## Steps to Reproduce (for bugs)

Given:
  -  a project named `Blorf` that was updated by the `p.github_repo_user_name` on January 1, 2017, and
  - a project named `Florb` that was updated by a developer on the project that is != `p.github_repo_user_name` for the `Florb` project on January 2, 2017

Then `Florb` should appear _before_ `Blorf` in the sorted list of projects

**Comment by mattlindsey** [comment]
Unfortunately it seems there is no easy way using the github api to get the most recent commit, so @tansaku and I settled on the last 'push' datetime for the repo. 
I am guessing that maybe people are not 'pushing' to SHF-Project the way they are as collaborators on other repos.
Thus I'm not sure of the solution, except to try again to get the 'last commit datetime' for the repo by scanning the commits.  I'll do some more research...

**Comment by weedySeaDragon** [comment]
I'm not sure it's the _pushing_ as much as it is the specific user you're looking at.  I think we're doing this in a pretty standard way.  But the number in the set of 'standard ways' is large.

You're only checking the commits for `p.github_repo_user_name` .  Who do you think that is, exactly?  The repo owner?    That's the key question for me.  

(It's been a while since I looked at the new GraphQL API that GH is working on.  Does that provide better access to the data we want?  I can imagine reasons why we wouldn't want to use that new, not-yet-released API, of course.)

**Comment by mattlindsey** [comment]
I think it's actually the '-' in 'SHF-Project that's messing up the following regular expressions:
```
 def github_repo
    /github.com\/(.+)/.match(github_url)[1] unless github_url.blank?
  end

  def github_repo_name
    /github.com\/(\w+)\/\w+/.match(github_url)[1] if github_url
  end

  def github_repo_user_name
    /github.com\/\w+\/(\w+)/.match(github_url)[1] if github_url
  end
```

And note that the 'github_repo_name' method looks wrong in that it actually returns the *team* name and 'github_repo_user_name' returns the *repository* name.

The quick solution is to handle '-' correctly, while the long-term solution is to rework the regular expressions names and all of the places they are called.

**Comment by mattlindsey** [comment]
Ignore last comment.  '-' doesn't seem to be the problem.  Sorry.

**Comment by mattlindsey** [comment]
I stepped through the code an, wierd as it seems, the github api is indeed returning *nil* for the last pushed date for the SHFProject repo.
Thus the bug is more subtle than I can determine at the moment.

There are also problems with naming of things, like Project.github_repo_user_name is a regular expression actually returns the repo name -- not a user name!  
Thus the code is very confusing to read, as @weedySeaDragon found out.

**Comment by weedySeaDragon** [comment]
Thanks for looking into this so quickly, @mattlindsey.  Now we know where to dig deeper.

**Comment by tansaku** [comment]
```
As a project manager
So that potential contributors can see that our project is active, so they might join
I'd like our project to appear high up on the projects list
```

**Comment by tansaku** [comment]
```
irb(main):003:0> p.github_repo_name
=> "AgileVentures"
irb(main):004:0> p.github_repo_user_name
=> "shf"
```

looks like we have a problem with extracting repo names that include hyphens:

```rb
  def github_repo_name
    /github.com\/(\w+)\/\w+/.match(github_url)[1] if github_url
  end

  def github_repo_user_name
    /github.com\/\w+\/(\w+)/.match(github_url)[1] if github_url
  end
```

**Comment by tansaku** [comment]
we should drive this with a test ...
