### ISSUE TITLE
CONTRIBUTING.md skips over important development installation steps

### ISSUE THREAD

**Issue by weedySeaDragon** [AgileVentures/WebsiteOne#1547]
The information in CONTRIBUTING.md is really about general workflow and working with GitHub.  But that's not clear -- it seems to describe the steps to install WSO and start development.

Because I'm used to looking in [CONTRIBUTING.md](https://github.com/AgileVentures/WebsiteOne/CONTRIBUTING.md)  (after looking in README), I just followed along what CONTRIBUTING said.  It was only when I ran into a wall with `secrets_key` did I see that later, after a list of things to do, the "Project Setup.md" file is mentioned.

This is confusing -- the overlap isn't clear.  (And for me, it caused problems).

My suggestions for a fix:

1. Put all of the information and steps for setting up development in one document; don't split or overlap the information.  Clearly refer to that 'development set up' document in the README and CONTRIBUTING (and whatever other documents might be appropriate). 
2. Explain how to set up /configure the `secrets_key`  in the 'development set up' document.  Ex:

    You will need to create a `secrets_key` and store it in a file named `.env` (notice the leading dot).  
    The `.env` file needs to be in the project root directory _(explain that)_
    For development, it doesn't matter what the value of the `secret_key` is.
    Here's a quick way to create the `.env` file:
    ```
        echo "SECRET_KEY_BASE=1234" > .env
    ```
   (be sure you're in the project root directory when you do that.)

   _[and a reference to where in the code the system looks for info in .env -- in the code or specs or features or where-ever]_

If that makes sense, I'll do a PR

### Details about what I ran into: (tl;dr)

I am installing WSO on my local machine.
I looked at [CONTRIBUTING.md](https://github.com/AgileVentures/WebsiteOne/CONTRIBUTING.md) and followed along to get it installed.   I'm used to looking for installation and development information first in the README, then in CONTRIBUTING.

CONTRIBUTING.md says:

> To get involved please follow these steps:
> 
> 1. install WSO on your dev environment (laptop or c9)
> 2. get tests passing
> 3. check site can be run manually
> ...

So I did that:  I forked it, cloned it to my local dev machine, ran `db:setup` and then did as step 2 says:  "get tests passing"  -- I ran `rake` to run the tests.

But I immediately got a FAIL for every RSpec test.  Every fail was because it couldn't find the `secrets_key`.  

I looked at CONTRIBUTING.md again and only then did I see that _after_ the list of things to do it says "Please see the[ project setup guide](https://github.com/AgileVentures/WebsiteOne/docs/project_setup.md) to get set up with the project for development."

And so _then_ I looked at Project Setup and saw a bunch of details that need to be done to get the development environment really set up.

 Each failed test said:
```
 Failure/Error: raise "Missing `secret_token` and `secret_key_base` for '#{Rails.env}' environment, set these values in `config/secrets.yml`"
       
       RuntimeError:      Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`...
```

There is no `config/secrets.yml` file.
After a little more digging, I realized that the token is expected to be in `ENV['SECRET_KEY_BASE']` according to `config/secret_token.rb`

**Comment by tansaku** [comment]
great stuff @weedySeaDragon - would be great to have a PR with the suggested changes :-)

**Comment by arreche** [comment]
My two cents to avoid this misunderstanding
- Improving the visibility of `Project Setup` in the `Readme`
- Linking to `Project Setup` from `Contributing`

Regarding to placing environment variables in the `.env` file, I would suggest to complement the `Step 6: Request the .env file` by adding an example.

**Comment by tansaku** [comment]
@arreche that sounds great - very happy to merge pull requests that make those sorts of changes :-)
