### ISSUE TITLE
bug in display of upgrade

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1550]
I already have premium mob since I have a higher tier:

![bug](https://cloud.githubusercontent.com/assets/3909918/22647554/3ab0aaf0-ec40-11e6-8d0b-9013ba912e3e.JPG)

**Comment by tansaku** [comment]
at the moment our local system is showing your membership as Premium, even though you are on PremiumMob

```
irb(main):019:0> u = User.find_by slug: 'michael-c'
irb(main):024:0> u.membership_type
=> "Premium"
irb(main):025:0> u.subscription
=> #<Premium id: 2, type: "Premium", started_at: "2016-10-25 16:46:55", ended_at: nil, user_id: 21, plan_id: 1>
```

**Comment by tansaku** [comment]
which partly reflects our systems lack of representational power in terms of how subscriptions change, but also possibly the way in which you upgraded - taking out a new subscription for Premium Mob ... and then me manipulating it on Stripe to upgrade to Premium F2F. There is now an upgrade path (for Premium Mob at least) that should work better for this, but there's work to do to make sure accurate representations of user status are maintained.

for now I will update your plan manually and hopefully you'll see the correct banner (i.e. none in the first instance ...)

**Comment by tansaku** [comment]
```
irb(main):028:0> p = Plan.find 3
=> #<Plan id: 3, name: "Premium F2F", free_trial_length_days: 0, third_party_identifier: "premiumf2f", amount: 5000, created_at: "2017-01-18 10:58:08", updated_at: "2017-01-18 10:58:08", category: nil>
irb(main):029:0> u.subscription.plan = p
=> #<Plan id: 3, name: "Premium F2F", free_trial_length_days: 0, third_party_identifier: "premiumf2f", amount: 5000, created_at: "2017-01-18 10:58:08", updated_at: "2017-01-18 10:58:08", category: nil>
irb(main):030:0> u.subscription.save
=> true
irb(main):031:0> u.membership_type
=> "Premium F2F"
```

let me know what you see when you next look at the site

**Comment by tansaku** [comment]
I've also followed up and manually updated all the subscriptions and titles until I've got them matching what my records in Paypal and Stripe say - if we're lucky one day we'll be big enough to deserve an admin interface for all this :-)

**Comment by tansaku** [comment]
@mtc2013 so do you see the correct landing page now?  I would have thought you would see no button now - if so, we could close this issue ...

**Comment by tansaku** [comment]
so @mtc2013 still seeing the wrong thing ... hmm

**Comment by tansaku** [comment]
so this is the logic:

```erb
<% if current_user %>
    <% if current_user.membership_type == 'Basic' %>
        <% path = new_subscription_path %>
        <% message = 'Upgrade to Premium for additional support' %>
    <% elsif current_user.membership_type == 'Premium' %>
        <% path = new_subscription_path(plan: 'premiummob') %>
        <% message = 'Upgrade to Premium Mob for group sessions with a Mentor' %>
    <% end %>
<% else %>
    <% path = new_user_registration_path %>
    <% message = 'Sign up now to start coding!' %>
<% end %>
```

which we should remove from the view, but anyway, hmm, seems like my attempted change didn't go through - maybe I didn't save properly ... have done again and after a reload it should work for you now ...

```
irb(main):002:0> u.membership_type
=> "Premium F2F"
```

**Comment by tansaku** [comment]
all the others seem to be updated okay - just you not for some reason - apologies

**Comment by tansaku** [comment]
fixed now right @mtc2013 ?
