### ISSUE TITLE
Pair Programming notification for SHF project - not showing up in project channel

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/WebsiteOne#1552]
The notifications show up in "general" and "pairing_notifications", but not "shf-project".  Please enable that.

**Comment by tansaku** [comment]
@patmbolger sure thing - we need to adjust the agile bot settings to include the shf-project channel

**Comment by tansaku** [comment]
@mtc2013 any interest in seeing if you can make the above adjustment?

**Comment by tansaku** [comment]
@patmbolger hoping this might do the trick: https://github.com/AgileVentures/agile-bot/pull/52

**Comment by tansaku** [comment]
@patmbolger did you see any change after my agile-bot deployment
