### ISSUE TITLE
adjusting how "next scrum" is displayed to new users

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1554]
```
As an AgileVentures Admin,
So that new members are more likely to watch and/or attend scrums and other events
I would like the language in the upcoming event notification to me as welcoming as possible, i.e. not mention things like "scrum" and "kent beck" that may be unfamiliar
Whereas long term members should still see the original format???
```

```
As a new member
So that I can understand better how the community works
I want clear instructions about how to get help and support
```

as we were discussing in the [scrum](https://www.youtube.com/watch?v=eUhIV1c9CpU) we'd like to adjust the messaging on the upcoming scrum for those who are not logged in ...

Currently it says things like:

> "Kent Beck" Scrum & Pair Hookup (Scrum Master: Sam Joseph) in 2 hours 3 minutes

we'd like to change it to something like:

> “Want to learn more?  Listen in during the next projects review meeting, in 2 hours 3 minutes.”

when events are live there is other text, which we might also change to make it more inviting and less intimidating.  In the first instance we're just planning to do this for users that are not logged in.

**Comment by tansaku** [comment]
@patbolger came up with this concept:

> Aside from joining AV, we need another call to action - because right now, if a visitor joins, they still have to independently try to find an appropriate project by wading through the site, and then try to determine when a scrum might occur that involves that project, and then show up at a scrum which dives right into the minutiae of daily activity, etc. - all daunting and even intimidating.

**Comment by tansaku** [comment]
if we were writing acceptance tests for this they'd be interacting with the ones that @c1505 is working on in https://github.com/AgileVentures/WebsiteOne/pull/1519

**Comment by FedericoEsparza** [comment]
This is minor, and I'm not sure that it warrants a whole new ticket, so I'm putting it here: 
 
In _"Want to learn more? Listen in. Next projects review meeting in 2 hours 3 minutes"_ 
 
`projects` should be `project's`
