### ISSUE TITLE
add cuke for #1551

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1558]
this is almost so trivial I am not sure we need a test, but it was reported by a user in #1495 - it's a simple fix in the view - so I'm going with a separate ticket to merge in the fix - and leave it to anyone who's feeling motivated to reflect further on whether a test is necessary or what it should look like

**Comment by sngeth** [comment]
Addressed this missing test coverage in this PR: 

https://github.com/AgileVentures/WebsiteOne/pull/1701
