### ISSUE TITLE
Change out G+ signup button for Google button

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1561]
![Google-NOT_G+](https://www.dropbox.com/s/sg6m0t9gz8u7sll/Google-NOT_G%2B.png?dl=1)

 
**It _might_ be the case that many new visitors aren't signing up** when they go to the regular sign up page. **because they don't have a Google+ account**, although almost **everyone has a gmail/google** account.
 
![users-sign_up](https://www.dropbox.com/s/0zgr7kgpfh1ozaa/users%3Asign_up.png?dl=1)
 
If they sign up, they're invited to Slack, which makes it more likely that they'll sign up for Premium.
 
**We should change the button**, since they'll be prompted for permissions by Google anyway.
 
Here's the svg link to the new icon:
https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/8215f6659adc202403198fef903a447e/sign-in-with-google.svg

**Comment by tansaku** [comment]
```
As a site owner
So that as many people as possible sign up
I would like a clear indication they can sign up with Google 
In contrast to thinking they need G+
```
