### ISSUE TITLE
CONTRIBUTING.md link  = not found

### ISSUE THREAD

**Issue by welleram** [AgileVentures/WebsiteOne#1562]
I was interested in contributing to the project and was browsing the setup page:  https://github.com/AgileVentures/WebsiteOne/blob/develop/docs/project_setup.md

I was trying to go to the CONTRIBUTING.md link, and when I hit the link it is a blank page:
https://github.com/AgileVentures/WebsiteOne/CONTRIBUTING.md

## Expected Behavior

I would expect this link to take me to the CONTRIBUTING.md page

not applicable

## Current Behavior

I was interested in contributing to the project and was browsing the setup page:  https://github.com/AgileVentures/WebsiteOne/blob/develop/docs/project_setup.md

I was trying to go to the CONTRIBUTING.md link, and when I hit the link it is a blank page:
https://github.com/AgileVentures/WebsiteOne/CONTRIBUTING.md

n/a

## Possible Solution

 The href should be updated to point to:  https://github.com/AgileVentures/WebsiteOne/blob/develop/CONTRIBUTING.md

## Steps to Reproduce (for bugs)

1.  Click here:  https://github.com/AgileVentures/WebsiteOne/blob/develop/docs/project_setup.md
2.  Click here:  https://github.com/AgileVentures/WebsiteOne/CONTRIBUTING.md
3.  You will see the blank page which should be CONTRUBTING.md content
4.

## Context

I was trying to learn how I could contribute to the project when I found this error.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):
Win10 OS, Chrome Version 56.0.2924.87

**Comment by tansaku** [comment]
Thanks for catching that @welleram - I think I fixed it
