### ISSUE TITLE
Two missing/broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Romusc** [AgileVentures/WebsiteOne#1577]
## Expected Behavior
When the following link, I expect to get to the waffle dashboard:

![image](https://cloud.githubusercontent.com/assets/20600943/23627112/4c879cca-02a7-11e7-9e01-3a95e4c28976.png)

## Current Behavior
Instead I get to the open PR screen:

![image](https://cloud.githubusercontent.com/assets/20600943/23629612/1f0fbc7e-02b0-11e7-9a04-1231a8a7ea34.png)

## Expected Behavior
When clicking the following link, I expect to get to the page describing how to create a pull request:

![image](https://cloud.githubusercontent.com/assets/20600943/23627138/6ab4b322-02a7-11e7-8227-669af155e6d5.png)

## Current Behavior
Instead I get to a 404:

![image](https://cloud.githubusercontent.com/assets/20600943/23629645/3043fe7e-02b0-11e7-89fd-ee64f279f33c.png)

## Possible Solution
Correct links need to be amended in contributing.md

**Comment by mattlindsey** [comment]
waffle.io company is closed, so remove that
