### ISSUE TITLE
make Premium benefits a "why" instead of a "what"

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1583]
@weedyseadragon suggesting:

> My main reaction is that you need to re-craft some of those items because they are answering the question "what"  but when describing a benefit, you want to answer **"WHY"** as in "Why would I care?  Why would this be helpful to me?"

> Ex:

>   -  **JetBrains Integrated Development Environment (IDE) licence (worth £15 a month)**

> is really answering _what_.  Re-state it to provide the _why this is valuable_ right up front. (Then you can provide the _what_ details in the full description:

>  -  **Free use of the full-powered RubyMine development software on your AgileVenture projects. (A £60/year value)**

> That's a quick, rough example.  ("full-powered" should be replaced by something better.)  But you get the idea.
> I would be happy to brainstorm with others on this if it's helpful. 

in #1565

**Comment by weedySeaDragon** [comment]
I'll connect with AV folks to do quick brainstorms of the benefits (getting to the _why_s), and will draft up the results.

**Comment by tansaku** [comment]
hi @weedySeaDragon - added myself to this as I think it's moving up the list in terms of importance.  

I just came up with the following sets of questions relating to each of the different Premium level benefits:

### Premium

- RubyMine/WebStorm IDE license
- Private support channels (jobs, tech tests, professional develop)
- Professional code review
- Eligibility for paid projects
- Supporting the AV mission
- Support on SO
- CodeSchool NonProfit Discount


* You want to find great developer jobs? Get help on the job search process?
* You want to ace technical tests required to get interviews?
* You want to accelerate your professional development?
* You want to improve your coding and development skills?
* You want to put paid coding projects on your resume?
* You want to make the world the better place?
* You want to feel confident asking technical questions online?

* You want to get discounts on important software and services for developers?


### Premium Mob

- Mob programming sessions with an assigned AV Mentor each week
- Professional Development Planning Support
- Free accesss to Udemy Complete Elixir & Phoenix Bootcamp course (usual price $50)
- Free accesss to Udemy React Redux course (usual price $180)
- 25% discount on "Effective Testing with RSpec 3"
- 10% discount on Upcase membership

* You want to level up on the latest hot technologies like Elixir and React?
* You want to get a personalised professional development plan to achieve your goals?
* You want to master mob programming online?


### Premium F2F

- One hour of pair programming time with an AV Mentor on an AV project each month
- Voting rights in AV general meetings 

* You want personalised individual support to improve your coding and pairing skills?
* You want to influence the future direction of the AgileVentures charity?

--------

totally rough and ready - I like the approach you suggest of connecting with individual members ... I think surveying all the Premium members to find out what they really value might also be a good way to go ...

**Comment by weedySeaDragon** [comment]
Thanks @tansaku .  This is really helpful. 

It's notable to me that you never mention "agile" above.  That is what separates AV from the 10,000 other places people can go to develop their skills, so it should definitely be in there.  (Yes, I realize these are questions you're contributing and not necessarily the final text. :-)  But still, it needs to be in there & in there prominently)


Also -- "surveying all the Premium members"  What is the mechnism you envision for this?  A quick survey monkey survey?  Perhaps there's already a mechanism somewhere in AV?  (One that will gather the results in a form that can be tallied and numerically analyzed -- but still allows for entering additional text to elucidate answers, of course.)

**Comment by tansaku** [comment]
@weedySeaDragon great point about "Agile".  What's interesting is that in breaking out separate items to give support on, we lose sight of the bigger agile picture.  @mtc2013 mentioned that getting quick feedback on pull requests is crucial for Agile, but it's also the case that the main "Agile" things that we offer, such as working with a team, doing scrums, retros, kick-offs, sprints etc. are not something that the premium offering particularly supports - or at least not in its current form.

It makes me think about things like having specific features like Sprint or retrospective support.  Of course that's not as easy to break out as something that can be offered to Premium's on a 121 basis without the associated selection of a project, introduction to the team etc. etc.  I have ideas about people signing up for a one off "sprint support package" at some higher price point, but there's a ways to go there for that to make sense ...

Re surveying, I have google forms that I sent out previously and in coordination with the marketing team will be sending out again, and naturally those forms will have a combination of things for numerical analysis and further elidation.  Here's the form that went out last year:

https://goo.gl/forms/wACQf0jPxThbbSej2

We're in the process of updating the questions

**Comment by tansaku** [comment]
here's another pass at questions for the Premium page:

Want to find great developer jobs? Get help on the job search process?
Want to ace technical tests required to get interviews?
Want to accelerate your professional development?
Want to improve your coding and development skills?
Want to really understand Agile software development?
Want to put paid coding projects on your resume?
Want to make the world the better place?
Want to feel confident asking technical questions online?
Want to get discounts on important software and services for developers?
