### ISSUE TITLE
enable SSL

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1584]
```
As a potential premium member
So that I can feel safe submitting credit card details
I would like to see secure settings
As opposed to currently when we don't have ssl set up on the site
```

All our Stripe interactions are encrypted, but people would probably be reassured by SSL on the entire site

**Comment by FedericoEsparza** [comment]
As requested, screenshot images of Firefox and Chrome, just prior to submitting credit card info via Stripe:
![insecure-AV-premium-signup-firefox](https://www.dropbox.com/s/p467d4wshh3abv2/insecure-AV-premium-signup-firefox.png?dl=1)
 
![insecure-AV-premium-sponsorship-signup-chrome](https://www.dropbox.com/s/a0fv38q41qpvna5/insecure-AV-premium-sponsorship-signup-chrome.png?dl=1)
 
On Chrome, while signed in:
![insecure-AV-premium-signup-chrome-worse-if-signed-in](https://www.dropbox.com/s/bivamrva96cwkxa/insecure-AV-premium-signup-chrome-worse-if-signed-in.png?dl=1)

**Comment by tansaku** [comment]
https://www.google.co.uk/search?q=heroku+enable+ssl

**Comment by tansaku** [comment]
https://blog.heroku.com/ssl-is-now-included-on-all-paid-dynos
