### ISSUE TITLE
[EPIC] StaticPages

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1590]
We should look at a solution that allows for better styling control on the important static pages like premium, pricing etc.

**Comment by weedySeaDragon** [comment]
As a replacement for Mercury editor?  (I'm semi-guessing after only briefly looking thru the code)

Why not CKeditor?  It's kind of been the standard and has lots of capabilities. (And of course you can limit who can use what features/capabilities, etc.)

**Comment by tansaku** [comment]
@weedySeaDragon does CKeditor support markdown?  personally I just want to edit everything in markdown

in the short term we can also just move these pages away from being directly editable wikis in the site - it seems like the days of being able to edit them directly might be over - no one ever joined in very much as no one thought they'd be able to.

And now we have all these pricing pages perhaps they should only be edited via pull request

**Comment by weedySeaDragon** [comment]
There is an add-on for doing markdown in ckeditor, @tansaku : http://ckeditor.com/addon/markdown

But if not many folks are going to be editing them, and most of those folks like mercury, then no need to go changing it.

**Comment by tansaku** [comment]
I'm not sure there's anyone who "likes" mercury - and the mercury project itself is no longer being maintained - but it works for us more or less ...

**Comment by tansaku** [comment]
we've replaced mercury with github editing of AgileVentures/AgileVentures and those pages are pulled into the main AV site ...
