### ISSUE TITLE
Private events for premium members

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1596]
```
As a premium member
So that I can easily work out the time of the next premium event in my timezone
I would like premium events

As an admin
So that we can encourage premium signups
I'd like premium events to be only accessible to premium members (but potentially visible to non-premium members --> call to action to become premium member in order to join)
```

we could do with private events that were only visible to premium, mob, or f2f members as we are currently organizing those on an ad hoc basis

**Comment by tansaku** [comment]
with the google hangout API fail, we sort of have this, i.e. create an event, but then don't manually update the hangout link ...

**Comment by tansaku** [comment]
one good way to support this is to allow premiums and admins to create private events - i.e. a flag that when set would mean that general and other public channels were not notified and private channels were

**Comment by c1505** [comment]
Currently:
All events have a slack notification
All events have a twitter notification
All events are visible on the event show page for any member to join
All past event video is visible to all users

Future:
Premium events will only notify in premium channels on slack
Premium events will not have a twitter notification
Premium events will only be visible to join by premium members on the event show page
Premium event video will only be visible to premium users

Is that what is desired?  Seems like the available video after the fact could go either way.

**Comment by c1505** [comment]
There is also an open PR in a similar area of the codebase as this issue #1793 and an open issue to refactor this area of the codebase #1799

**Comment by tansaku** [comment]
some notes on this feature:

> Allow events to have a privacy flag.  Private events would not ping public channels when they go live - ideally they could specify which channel to ping, e.g. #premium_extra for mobs, and the individual #premium_username channel for F2F events.

> Private events would also not allow access to associated video recordings unless the viewing user had sufficient permissions.

> It would be great if those who don't have permissions are redirected to premium signup, offered a view of a single video if they follow us on twitter or linkedin

**Comment by tansaku** [comment]
in progress in sprint 51

**Comment by tansaku** [comment]
@bcb37 @nisevi you two planning to pair on this this week?

**Comment by tansaku** [comment]
so the next step on this was outlined in the closed PR https://github.com/AgileVentures/WebsiteOne/pull/2270#issuecomment-380089272

where @marianmosley and I reviewed and we think the kind of scenario we'd want is maybe an outline like this:

```gherkin
  Scenario Outline: show mob hangout links to users with correct plans
    Given the I am logged in as a user with "<plan>"
    Given the Hangout for event "Mob" has been started with details:
      | EventInstance link | http://hangout.test |
      | Started at         | 10:25:00 UTC        |
    And the time now is "10:26:00 UTC"
    When I am on the show page for event "Mob"
    Then I <assertion> see link "Join now" with "http://hangout.test"
    Examples:
      | plan       | assertion  |
      | PremiumF2F | should     |
      | PremiumMob | should     |
      | Premium    | should not |
      | Associate  | should not |
      | Free       | should not |
```

although we can start with individual ones if that is easier:

```gherkin
  Scenario: Premium member cannot access live mob event
    Given the I am logged in as a Premium user 
    And the Hangout for event "Mob" has been started with details:
      | EventInstance link | http://hangout.test |
      | Started at         | 10:25:00 UTC        |
    And the time now is "10:26:00 UTC"
    When I am on the show page for event "Mob"
    Then I should not see link "Join now" with "http://hangout.test"
    And I should not see hangout button
```
