### ISSUE TITLE
archive old projects

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1603]
```
As a new member
So that I can join a project
I would like an easily navigable uncluttered list
```

there are a load of totally inactive projects - we should hide on the left side bar them (and make the side list alphabetical) to make things easier to navigate (alphabetical)

**Comment by ecnalyr** [comment]
How should, "totally inactive," be defined?

**Comment by tansaku** [comment]
@ecnalyr at the moment we have an inactive/active flag that can be set by the project manager - in the first instance we'll just use that
