### ISSUE TITLE
Make entire hovered home page circles clickable

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1615]
![AV-home-page-circles](https://dl.dropbox.com/s/hwdv87mcotyghqn/AV-home-page-circles.png?dl=1)
 
To increase clicks on the circles and make them more clickable, have the href link be for the entire circle and not just the "Read more" button.

**Comment by lexcorp16** [comment]
I would like to take this up @FedericoEsparza the attached image link seems to be broken though

**Comment by FedericoEsparza** [comment]
@lexcorp16 Link fixed.
