### ISSUE TITLE
Upcoming events posted to Slack #general

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1617]
In order to increase scrum/pairing session attendance, it might be helpful to post the day's upcoming events (https://www.agileventures.org/events) into the #general Slack channel

**Comment by FedericoEsparza** [comment]
I rarely go to the AV site, unless I need to. I'm *more likely to go to* a project's Github repo page, and, obviously, I (and new members, as well, I suspect) spend the most amount of time on the *Slack* instance/web-page.

**Comment by tansaku** [comment]
great idea @FedericoEsparza - or even staggered reminders before events?  possible to an events_notification channel - upcoming day schedule would be good too.

maybe you could pitch this in a WSO kickoff?

**Comment by mattlindsey** [comment]
+1

**Comment by tansaku** [comment]
I've started doing this manual to get feedback:

```
TODAY'S EVENTS
==============

* 11:00am UTC "Martin Fowler" Scrum and Pair Hookup - https://www.agileventures.org/events/martin-fowler-scrum-and-pair-hookup
* Noon UTC AV Marketing Meeting - https://www.agileventures.org/events/av-marketing-meeting
* 3:15pm UTC "Kent Beck" Scrum and Pair Hookup - https://www.agileventures.org/events/kent-beck-scrum-and-pair-hookup
* 3:30pm UTC LocalSupport Retro/KickOff - https://www.agileventures.org/events/localsupport-kick-off

click on the links above to see event times in your timezone (as automatically detected by your browser)
```

**Comment by tansaku** [comment]
feedback on this is positive

**Comment by tansaku** [comment]
we could set this to be handled by slack reminders ...

**Comment by tansaku** [comment]
slack reminders can't handle multi-line posts :-(

**Comment by mattlindsey** [comment]
This feature seems to have been added to Slack by 'Poppa Nick' using the 'AV Bot', so I'll close this issue.
