### ISSUE TITLE
[Airbrake] [Production] couldn't find file 'moment-timezone-with-data-2010-2020' with type 'application/javascript' Checked in these paths:    /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/app/assets/images   /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/a...

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1624]
**Airbrake error:** [#1162](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/1921979393875901162)
**Airbrake project:** websiteone-production

**Error type:** `Sprockets::FileNotFound`
**Error message:** `` couldn't find file 'moment-timezone-with-data-2010-2020' with type 'application/javascript' Checked in these paths:    /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/app/assets/images   /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/app/assets/javascripts   /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/app/assets/stylesheets   /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/lib/assets/mercury   /tmp/build_d093a6edc8ee672c602c10d44a79dfc3/vendor/assets/javascripts   /tmp/build_d093a6edc8ee672c602c10d44a79dfc ``
**Where:** `rake#assets:precompile`
**Occurred at:** Apr 05, 2017 19:49:56 UTC
**First seen at:** Apr 05, 2017 19:49:56 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)

**URL:** `<no information>`
**File:** `[PROJECT_ROOT]/app/assets/javascripts/application.js`

**Backtrace:**
```
[PROJECT_ROOT]/app/assets/javascripts/application.js:34:in 
[GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in resolve!
[GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in resolve
[GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in process_require_directive
```

**Comment by tansaku** [comment]
this was due to a database query that was over-running - I adjusted the order of the boolean and fixed it
