### ISSUE TITLE
Spelling mistake - membership pricing page

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#1628]
https://www.agileventures.org/pricing

"JetBrains RubyMine/**WebStormg** (IDE) licence" should be "JetBrains RubyMine/**WebStorm** (IDE) licence".

**Comment by tansaku** [comment]
thanks @freeranger - that's fixed 
note all those pages are wikis - so you can fix spelling mistakes yourself if you fancy :-)

**Comment by freeranger** [comment]
@tansaku - sorry, didn't realise!
Do you still need an issue raised for updating a wiki page, or just go ahead and do it?
