### ISSUE TITLE
Self-Explanatory button -> text size

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1629]
![](https://www.dropbox.com/s/71munqhiqr7dowi/Screenshot%202017-04-13%2014.06.06.png?dl=1)
 
No one reads this text, so won't waste time explaining. Screenshot is self-explanatory.

**Comment by tansaku** [comment]
@FedericoEsparza fixed: ![fixed ](https://www.dropbox.com/s/wnc55mgy87klir5/Screenshot%202017-04-25%2020.04.34.png?dl=1)

**Comment by tansaku** [comment]
the change was setting the width of the span from 50% to 60% in the html view in the mercury editor:

```
<span class="btn btn-primary btn-block" style="padding: 5px; width: 60%; border-color: #ee7335; background: #ee7335; display: inline-block; font-size: 1.4em;"><a href="http://www.agileventures.org/subscriptions/new?plan=premiummob"><b><font color="#ffffff">Get Started with Premium Mob</font></b></a></span></div>
```
