### ISSUE TITLE
Commits associated with DSCP Partner Portal not showing up in karma

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1630]
For @freeranger and potentially others.  

I also note that the commit count for the project is still zero.  

Relevant code from GithubCommitsJob:

```
def run
    Project.with_github_url.each do |project|
      begin
        update_total_commit_count_for(project)
        update_user_commit_counts_for(project)
      rescue StandardError
        Rails.logger.warn "#{project.github_url} may have caused the issue. Commit1 update terminated for this project!"
      end
    end
  end
```

If update_total_commit_count_for(project) errors out in Octokit call due to rate limiting then subsequent user commit update will never be run either.

**Comment by freeranger** [comment]
Example project with no commits recorded:
https://www.agileventures.org/projects/dscp-partner-portal#home
https://github.com/st-charles/DSCP-Partner-Portal-API/commits/master

**Comment by mattlindsey** [comment]
Just an idea. Refactor above code using GraphQL:
https://medium.freecodecamp.com/so-whats-this-graphql-thing-i-keep-hearing-about-baf4d36c20cf

**Comment by mattlindsey** [comment]
Remaining issue seems to be that certain project are not getting their commit counts updated because of missing Project table data.  For example, this returns 0 rows:

SELECT "projects".* FROM "projects" WHERE ("projects"."github_url" = 'https://github.com/AgileVentures/WebsiteOne')

**Comment by mattlindsey** [comment]
Appears that a '/' at the end of the URL (https://github.com/AgileVentures/WebsiteOne/) in the table is causing the row not to show up.
We should probably fix the regular expression to allow a '/' at the end.

**Comment by mattlindsey** [comment]
A clue:  Commit counts for 'mattlindsey', project 'WebsiteOne' are in the table, just not showing on screen:
SELECT  * FROM "commit_counts" WHERE ("commit_counts"."user_id" = 30 )

**Comment by mattlindsey** [comment]
I just retested, and I think this is fixed by solution to issue #1632.   Recheck after PR for that issue is moved to production.

**Comment by mattlindsey** [comment]
@freeranger This still wasn't fixed by my PR, so I'm moving this back to In Progress.
Although note that subsequent call issue noted by @mtc2013 in this ticket should be fixed, so it must be a different problem.

**Comment by mattlindsey** [comment]
Error appears to be that the following line (line 49 in github_commits_job.rb) is NOT inserting a row into the COMMIT_COUNT table if a row does not already exist:

 CommitCount.find_or_initialize_by(user: user, project: project).update(commit_count: contributor.total)

**Comment by mattlindsey** [comment]
Appears to be unhandled exception bug in Oktokit:
octokit-4.3.0/lib/octokit/connection.rb line 154:
       @last_response = response = agent.call(method, URI::Parser.new.escape(path.to_s), data, options)

**Comment by mattlindsey** [comment]
Opened Oktokit issue, which we may want to fix ourselves:

https://github.com/octokit/octokit.rb/issues/887

**Comment by mattlindsey** [comment]
Commit counts are now showing up in production, so I deleted the Octokit issue.
Now the remaining issue is that the Karma doesn't appear to be updating.
