### ISSUE TITLE
Paypal upgrade to Premium Mob not working

### ISSUE THREAD

**Issue by kirangp** [AgileVentures/WebsiteOne#1640]
If a user is already enrolled to Premium subscription using Paypal, he/she is not able to upgrade the membership to Premium Mob using Paypal. If the 'Upgrade to Premium Mob' button is clicked, error 'No such customer: 5LERZVNJXBAR8' comes up.

**Comment by mtc2013** [comment]
@alexander-kh has given a better error message for this condition.

this issue is closed by https://github.com/AgileVentures/WebsiteOne/pull/1659
