### ISSUE TITLE
Refactor/remove defensiveness from perform method in karma calculator

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1662]
```
  def perform
    if user.karma
      user.karma.total = 0
    else
      user.karma = Karma.find_or_create_by(user_id: user.id, total: 0)
    end

    return if user.created_at.blank?
    user.karma.total = sum_elements
    # better to have time in pairing sessions, code contributed (related to quality), issues, ...
  end
```

This defensiveness was introduced to guard against users existing without karma.  All users seem to currently have karma, and new users created via registration ought to have karma going forward.

Perhaps we can rid ourselves of this defensiveness?  Do we need QA checks to periodically test for karma being associated with each record as @mattlindsey suggested.  Or perhaps constraints that no user can be saved without karma?

**Comment by NickSchimek** [comment]
@mtc2013 I can't find this method in services/karma_calculator file or anywhere for that matter. Can you provide a link to the method? Otherwise we may be able to close this out if it's not longer an issue.

**Comment by mattwr18** [comment]
hey @NickSchimek so this method was removed by this PR
https://github.com/AgileVentures/WebsiteOne/pull/2547
