### ISSUE TITLE
ensure tests for all three fail paths for subscription controller update method

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1678]
because it bothers me

**Comment by alexander-kh** [comment]
[Stripe recommendations for handling errors](https://stripe.com/docs/api/ruby#error_handling)
We can handle all possible cases, except `Stripe::InvalidRequestError` and  generic `Stripe::StripeError` by
```ruby
rescue StandardError => e
```
Possible scenarios:
- too many requests made to the API too quickly
- authentication with Stripe's API failed
- network communication with Stripe failed

To test we can reproduce, for example, the second one.
