### ISSUE TITLE
Clicking on videos in lists not working

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1679]
For example, see http://localhost:3000/projects/websiteone and the first video appears, but when you click on any video in the list it doesn't appear.

Also see http://localhost:3000/users/sam-joseph and the first video does not appear, nor do the ones in the list which say:
video unavailable ('Start Broadcast' not pressed, or Hangout/YouTube fail)

**Comment by tansaku** [comment]
once we fix the http/https issue we get another issue whith ic :

![](https://www.dropbox.com/s/zw89lgms8wj7fjh/Screenshot%202017-05-26%2016.54.00.png?dl=1)

**Comment by lokeshh** [comment]
`video unavailable ('Start Broadcast' not pressed, or Hangout/YouTube fail)` is because `event_instance.yt_video_id` is nil and that's probably because we lost hangout API.

**Comment by tansaku** [comment]
@lokeshh @mattlindsey so I wonder if this is fixed now ...

**Comment by tansaku** [comment]
fixed now :-)
