### ISSUE TITLE
allow manual addition of videos

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1682]
users often wonder how they can add videos to a project (had that from at least a couple of different sources).  Being able to manually set the video of an event to get round the loss of the Hangout API would be one solution here.

**Comment by roschaefer** [comment]
same same. When I click on Videos I expect a big button with a plus saying "Add video". At the very least, an explanation or quick tutorial how to do so. Up to this point I don't understand and I cannot see an option how to add videos via hangouts (if at all this is the way how to populate the video list)

**Comment by c1505** [comment]
I'll work on this.  From my understanding, it seems that this request is to modify the link to the video and potentially add new links and descriptions to videos rather than a way to upload and host the video ourselves?   

Also, do you know offhand if these missing videos are failures of the API  and/or just what shows up when a planned hangout does not take place?

![image](https://user-images.githubusercontent.com/6599077/28830688-814e411c-76a5-11e7-9284-9067c544a1cf.png)

**Comment by tansaku** [comment]
great to have your input here @c1505 

> From my understanding, it seems that this request is to modify the link to the video and potentially add new links and descriptions to videos rather than a way to upload and host the video ourselves?

I don't think we support video "descriptions" at present.  The request is to give some sort of admin access to videos so that when a video is missing (due to whatever reason), someone who has the link to that video can come in and set the video link.

> Also, do you know offhand if these missing videos are failures of the API and/or just what shows up when a planned hangout does not take place?

If no one starts the hangout, then nothing shows up.  It's API failure - basically because the google hangouts API just doesn't work any more

@lokeshh added new functionality that allows the youtube URL to be set when the event starts, so it can be set manually via the event, while it is running so to speak, but there is currently no functionality to set it later, which is what this ticket is about.

It's possible (in principle) to update the video associated with an event_instance via the rails console, but there are a load of validations in place that make it really hard.

I almost think that the way to approach this issue is to start by creating a show page for individual event_instances so that they can be inspected individually through the web interface and then move on to allow for editing them in various ways ...
