### ISSUE TITLE
our github data is not up to date

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1684]
we update daily, but still some things seem to be out of date, e.g. last update of project, other projects not showing up in people's activity tabs.

We've added extra logging and the next step is to find the cause of failure for some of our github queries

**Comment by tansaku** [comment]
https://gist.github.com/tansaku/8b8bc4e188656037020df37cb2999936

**Comment by mtc2013** [comment]
https://gist.github.com/mtc2013/d05b96e6a4bbfcaa768f90188ffb54f3

**Comment by mtc2013** [comment]
So it looks ike in addition to the nil errors in github_repo_name, there is an error relating to how it's handling the dot in .com at the end of the github repo :

Updating the last update for https://github.com/MatthewDiana/BUCollab.com may have caused the issue!

GET https://api.github.com/repos/MatthewDiana/BUCollab: 404 - Not Found // See: https://developer.github.com/v3

**Comment by mtc2013** [comment]
Also, this repo seems to be no longer there.  So deal more gracefully with repos that have been deleted/moved?  

Updating the last update for https://github.com/pfulara1/OnlineExaminationSystem may have caused the issue!
GET https://api.github.com/repos/pfulara1/OnlineExaminationSystem: 404 - Not Found // See: https://developer.github.com/v3

**Comment by mtc2013** [comment]
And there's rate limiting: 

Updating the last update for https://github.com/BingBites/bingbites may have caused the issue!
GET https://api.github.com/repos/BingBites/bingbites: 403 - API rate limit exceeded for 54.74.31.170. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
/app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:19:in `get'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.7.0/lib/octokit/client/repositories.rb:29:in `repository'
/app/app/jobs/github_last_updates_job.rb:9:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/app/app/jobs/github_last_updates_job.rb:7:in `run'
/app/lib/tasks/scheduler.rake:8:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/airbrake-6.0.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'

**Comment by tansaku** [comment]
thanks @mtc2013 - I set a GITHUB_AUTH_TOKEN in production for heroku - I see that that get's picked up here: https://github.com/AgileVentures/WebsiteOne/blob/develop/config/settings.yml#L57

not sure if that's actually then used by any of these tasks ...

**Comment by tansaku** [comment]
looks like it is pulled in here: 

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/jobs/github_last_updates_job.rb#L19 

but not here:

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/jobs/github_commits_job.rb#L67

**Comment by mtc2013** [comment]
@tansaku so i put the github_auth_token in staging and ran the task and now the errors are:

https://gist.github.com/mtc2013/59c318a9ecbf5c1e944a1ecdba364f79

**Comment by tansaku** [comment]
thanks @mtc2013  - are any of them clear ones that are causing problems and need fixing?
