### ISSUE TITLE
Add missing static pages in development environment

### ISSUE THREAD

**Issue by alexander-kh** [AgileVentures/WebsiteOne#1687]
## Expected Behavior

When the user logs in and clicks on 'Upgrade to Premium for additional support' from the home page, an ActiveRecord error occurs.

It should lead to the corresponding page.

## Current Behavior

`ActiveRecord::RecordNotFound in StaticPagesController#show`
`can't find record with friendly id: "premium"`
```
def show
    return false if redirect_email_blunder
    @page = StaticPage.friendly.find(get_page_id(params[:id]))
    @ancestry = @page.self_and_ancestors.map(&:title).reverse
  end
```

## Possible Solution

Previously, this error did not arise.
As a starting point, it is sensible to inspect recent changes.

## Steps to Reproduce (for bugs)

Add this scenario in `features/premium/upgrade_membership.feature`:
```
  Scenario: Upgrade basic plan to Premium following link on the home page
    Given I am logged in
    And I am on the home page
    When I click "Upgrade to Premium for additional support"
    Then I should see "Agile Ventures Premium Membership gives the following benefits"
```
Error message:
`can't find record with friendly id: "premium" (ActiveRecord::RecordNotFound)`

## Context
The goal is to establish interrelations and solve the problem.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39): Chrome 58
* Operating System and version (desktop or mobile): cloud9, Ubuntu 14.04

**Comment by alexander-kh** [comment]
The changes were introduced by the pull request #1658.
The path was changed from `new_subscription_path` to `'/premium'`(`static_page_path('premium')`)

**Comment by alexander-kh** [comment]
The intention is good.
These pages are not presented in the `develop` branch.

**Comment by tansaku** [comment]
@alexander-kh great work identifying this - strange that we have no test for clicking "Upgrade to Premium for additional support" - sounds like it should be an easy fix?

**Comment by alexander-kh** [comment]
@tansaku, can you add these static pages? I haven't found relevant `rake` task in `develop` branch.

**Comment by tansaku** [comment]
@alexander-kh there never has been a rake task for them - we have them generated on a case by case basis in tests that need them - see https://github.com/AgileVentures/WebsiteOne/blob/develop/features/escalating_call_to_action.feature#L14

that would be the fastest way to make the test you describe pass

there is also the issue here of how developers development systems work in the absence of the pages?  I don't think you need my input to add these static pages to some rake task if that's the way we go ...

and BTW, isn't this the test that you say that we don't have?

https://github.com/AgileVentures/WebsiteOne/blob/develop/features/escalating_call_to_action.feature#L22

seems to me we have the tests we need, but what we are grappling with is that a developers instance set up from scratch will encounter some problems because certain static pages are not created by default no?

**Comment by tansaku** [comment]
as I was saying before, we could add those pages to:

https://github.com/AgileVentures/WebsiteOne/blob/develop/db/seeds.rb

the interesting question is do we want the content on developers machines to match what's on production?  That's difficult as production is currently changing from time to time ... should certain static pages be migrated to live in views/templates?  (potentially slowing down our update cycle)

or we have a task called `create_premium_static_pages` similar to https://github.com/AgileVentures/WebsiteOne/blob/develop/lib/tasks/create_plans.rake ?

Either way I don't think you need me to create things - we need to work out the best option out of the possible solutions to the underlying problem - assuming we've correctly identified it

**Comment by alexander-kh** [comment]
@tansaku, thanks for the clear explanation.
Yes, you're right, the scenario is covered by the above test.
> there is also the issue here of how developers development systems work in the absence of the pages?

This is the essence. With the introduced changes an ActiveRecord error raises in the development environment. 
> the interesting question is do we want the content on developers machines to match what's on production?

I think it's unnecessary. We are not relying on content in tests. But, to eliminate the error, we can add them in `app/views/pages` to create together with other static pages when setting up the database.

**Comment by mtc2013** [comment]
@alexander-kh this bug occurs only in development mode so is a task.

**Comment by alexander-kh** [comment]
@mtc2013, agree.

Summary
In development mode the following static pages are not presented:
* /pricing
* /premium
* /premium_mob
* /premium_f2f
* /premium_plus

I'll add these pages in `app/views/pages`. The content will match to the current versions.
They will be created by the `imprort_pages` rake task upon database setting up or resetting.

`db/seeds.rb`:
```ruby
if StaticPage.count == 0
  Rake::Task['db:import_pages'].invoke
end
```
