### ISSUE TITLE
wiki edu hangout link not working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1691]
Sage Ross [4:04 PM] 
> @tansaku I tried adding that hangout link yesterday, but it did not seem to work. When I saved, it redirected to a random url (like a token) with no content, and didn't seem to change the hangout url that popped up from the other button.

Sam Joseph [10:04 PM] 
> @ragesoss interesting - I wonder if that's because you're using a link tied to a particular use - I often need to snip off the stuff after the "?"

> were you pasting in this precise URL "https://hangouts.google.com/hangouts/_/wikiedu.org/sage?authuser=1" ? if so we'll do some tests ...
 
Sage Ross [10:33 PM] 
> @tansaku yes, that exact url

![sage's report](https://www.dropbox.com/s/66rhqfcqayxajoi/Screenshot%202017-06-19%2013.01.52.png?dl=1)

**Comment by tansaku** [comment]
we replicated on staging and it seemed to work ...?

**Comment by ragesoss** [comment]
I just tried on the site again, and got the same behavior. It redirects to something like `https://www.agileventures.org/hangouts/340800-e7de620a-f096-464b-a0e4-a78ddab9d002` (different string each time) with no content, and doesn't seem to have any other effects.

**Comment by tansaku** [comment]
thanks @ragesoss - can you post the links to where you're seeing that? provide some screen shots ...?

**Comment by tansaku** [comment]
you're pasting the link in here right?

![](https://www.dropbox.com/s/wtzuld9w1x546o6/Screenshot%202017-06-23%2018.29.10.png?dl=1)

**Comment by tansaku** [comment]
if I past it in there I get the following:

![](https://www.dropbox.com/s/xrzbebd1l92bna1/Screenshot%202017-06-23%2018.29.47.png?dl=1)

**Comment by tansaku** [comment]
and join now points to https://hangouts.google.com/hangouts/_/wikiedu.org/sage?authuser=1 as we might expect

**Comment by tansaku** [comment]
and I appear to be able to enter that hangout ... well I would if someone from wikiedu.org was there - I wonder if we are talking about different parts of the interface ...

**Comment by ragesoss** [comment]
Same form for me. Firefox 45 on Debian. Will test on other environments. Or
maybe it's because you own the event?

**Comment by tansaku** [comment]
pinged on slack: ![](https://www.dropbox.com/s/k6je81fydp7eo56/Screenshot%202017-06-23%2018.33.32.png?dl=1)

**Comment by tansaku** [comment]
ah, don't think event ownership affects it, but firefox 45 ...

**Comment by tansaku** [comment]
I'm in chrome on OSX

**Comment by tansaku** [comment]
replicated on firefox: 

![](https://www.dropbox.com/s/gqz0u3f3bmq40gc/Screenshot%202017-06-23%2018.35.42.png?dl=1)

**Comment by tansaku** [comment]
@mattlindsey @mtc2013 @lokeshh looks like a firefox issue

@ragesoss do you have any other browsers?

we'll try to get to the bottom of it - it's redirecting to the event instance URL for some reason - some header processing difference between chrome and firefox I guess ....

**Comment by ragesoss** [comment]
> do you have any other browsers?

Works for me in Chromium, will use that for the time being.
