### ISSUE TITLE
Research Hangout Alternatives (Jitsi Meet)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1697]
e.g. build our own or use jangouts - what will get us a stable meeting space where we can share screens and record and see who is in the meeting and get telemetry on people leaving and joining etc.

**Comment by tansaku** [comment]
you think this is good @lokeshh ? https://meet.jit.si

**Comment by mattlindsey** [comment]
I will try this: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

**Comment by lokeshh** [comment]
Please also note https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md for installation.

**Comment by SherSpock** [comment]
@mattlindsey 
Any thoughts test-driving Jitsi?

**Comment by lokeshh** [comment]
I found a docker image to setup jitsi-meet.

https://github.com/robertoandrade/docker-jitsi-meet

**Comment by SherSpock** [comment]
Awesome

**Comment by mattlindsey** [comment]
Lokesh and I tried a docker deployment of https://jitsi.org/ and it seems like the most full featured open-source solution for us.  It worked great, has screen sharing, stream to youtube, etc.

**Comment by tansaku** [comment]
Jitsi seems awesome - like almost everything we need - I wonder if we can generate buttons like we have for hangouts?

**Comment by mattlindsey** [comment]
Sam asks: What I wonder is if Jitsi has an API (I think it does) https://www.google.co.uk/search?q=jitsi+api and whether we can instrument Jitsi meets (or do something on the server side) so we get telemetry about what's happening (e.g. who joined, is the stream live etc.)

**Comment by mattlindsey** [comment]
Look at https://github.com/jitsi/lib-jitsi-meet It gives low level api to customize jitsi meet and embed to web app
