### ISSUE TITLE
404s on Pricing images

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1700]
Lots of 404 for icons on https://www.agileventures.org/pricing

Javascript console says:
`insecure image 'http://adfdns.co.za/av_img/addCheck.png'. This content should also be served over HTTPS.`

**Comment by alexander-kh** [comment]
@mattlindsey, I also noted that reference to the external server isn't reliable. It's also true for the static page `app/views/pages/pricing.html.erb`.

**Comment by alexander-kh** [comment]
@tansaku, I've added the original image into `app/assets/images` and have updated pull request #1689.
You may also use `check.png` in the production environment, or keep the new image.

**Comment by tansaku** [comment]
we should host the image ourselves
