### ISSUE TITLE
avoid displaying videos in "scrums" when youtube id is null

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1719]
https://www.agileventures.org/scrums shows lots of videos that won't play as it shows scrums when video ids are null (I think)

we have #1385 to try and allow videos to be updated going forward, but ideally scrums without a video id should not appear in this list

**Comment by lokeshh** [comment]
I think there are also videos with nil id showing in projects and users profile page

**Comment by tansaku** [comment]
@lokeshh as we discussed, I think we are handling those nils correctly (displaying an error message), so there's a separate task there to make it possible to upload videos to replace them (or move videos between projects)  - I think we need to take stock and look at priorities - probably the general fix to allow JitSy to submit videos into the site could be the priority, but .... well we can discuss
