### ISSUE TITLE
sign up page should mention member will get slack invite?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1724]
I'm just thinking we might increase the numbers coming into Slack if we let people know on the sign up page that they will get a slack invite (and that it's been sent when they've completed sign up) then they might be more likely to check for in and complete the registration with Slack.

It might also help for those where the email got stuck in their spam/promotions filter ... checking at around the time it was sent might help ...

**Comment by tansaku** [comment]
options include

1. add text to sign up page
2. add popup on page they get redirected to after signup
3. mention directly in getting started pages

**Comment by mattlindsey** [comment]
+1
