### ISSUE TITLE
make it simpler to stream video from Jitsi

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1727]
At the moment it's a little complicated to start a jitsy youtube stream

It would be great to have a button (in the jitsy) to start one, or even some set up that started them automatically - a button probably best in first instance

**Comment by tansaku** [comment]
@lokeshh has a working python script that communicates to YouTube API

one possibility is javascript in jitsy talking to youtube api?

**Comment by lokeshh** [comment]
The Python script to create youtube broadcast and get video URL https://gist.github.com/lokeshh/40eea3608d7af3d2fd1f07671b12bcd9

Most of code is used from here: https://gist.github.com/lokeshh/40eea3608d7af3d2fd1f07671b12bcd9

**Comment by tansaku** [comment]
could have pages like https://www.agileventures.org/event_instances/kent-beck-jul-20-2017/ with embedded jitsy: https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md and then execute a command like:

```
api.executeCommand('startLiveStream', AGILEVENTURES_YOUTUBE_STREAM_TOKEN)
```

and this would be connected up to a button in our page (outside the jitsy)?  or even start automatically and the youtube id could then be grabbed from the Youtube api and automatically added to the event?

**Comment by tansaku** [comment]
even if there was no api (and we were relying on manual live stream start) we could be polling the youtube api for the start of a stream?

repeatedly search for on youtube API for AV video titled the same as the event e.g. "Kent Beck"? Or even create the youtube "event" in advance and set up ready to livestream.

**Comment by tansaku** [comment]
hi @lokeshh since you haven't been around I'm going to un-assign you and put this back in the backlog - hope you're well
