### ISSUE TITLE
send data on jitsi attendees and youtube stream to websiteone from jitsi

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1728]
so websiteone can display who is or has attended a meeting, and the video from that meeting, we would like jitsy to send back data about the meeting to websiteone

**Comment by SherSpock** [comment]
Duplicated from [AgileVentures/Paironauts/issues/14](https://github.com/AgileVentures/Paironauts/issues/1728)
Original source provided by Sam: [Jitsi API documentation](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md)
 
_You can get the number of participants in the conference with the following API function:_ 

```var numberOfParticipants = api.getNumberOfParticipants();```
