### ISSUE TITLE
offer sign in with slack?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1730]
would it make sense to add this? https://api.slack.com/docs/sign-in-with-slack

**Comment by mattlindsey** [comment]
i looked at the link and it isn't quite clear to me (probably since I haven't been added to a slack team recently), but by clicking on the 'Sign In With Slack' could it 1) automatically add you to the AV Slack Team (in addition to getting the email) and 2) maybe pop up a link to Slack?

**Comment by mattlindsey** [comment]
Seems like a good idea, and might allow things in the future like showing the slack feed for a project in the Project screen (on the AV or EventManager site) since the user will/might be authenticated to view and participate in the slack feed.

**Comment by tansaku** [comment]
@arun1595 thanks for starting the research on this :-)
