### ISSUE TITLE
Events beyond set horizon are showing

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1745]
Currently the 'events' page is showing events beyond the horizon of 10 days current set here:
https://github.com/AgileVentures/WebsiteOne/blob/develop/app/models/event.rb#L20

**Comment by mattlindsey** [comment]
Performance is bad too, so infinity scroll might work better, but should probably profile locally first.

**Comment by tansaku** [comment]
I notice we have no indices set on the `event_instances` table - I think adding on against event_id might improve performance - should analyze the query ...

**Comment by tansaku** [comment]
okay, wrong about that - event_instances generally not being loaded ... 

looking more closely at the code, I think the issue relates to this method:

```rb
  def self.upcoming_events(project=nil)
    events = Event.base_events(project).inject([]) do |memo, event|
      memo << event.next_occurrences
    end.flatten.sort_by { |e| e[:time] }
    Event.remove_past_events(events)
  end
```

We've got over 3000 events in the system, and we're calling `next_occurrences` for all of them.  Each call to `next occurrences` only takes on average about 0.3ms, but *3000 means that takes a second and then we sort that list and do other things with it that gives us a base processing time of preparing the events list of about 3 seconds.

So to make it really performant we'd need a different database model where we lay out all the event instances, and update the schedule whenever anyone edits an event - not when they want to look at the event list.  That would be a major refactoring.

A short term thing might be to exclude those events who's end date has already passed ...

**Comment by tansaku** [comment]
```
 Event.where('repeat_ends = false OR repeat_ends_on > ?', Time.now).count
```
gives me 109 events - would that be all the ones we need?

**Comment by tansaku** [comment]
hmm, specs failing - factory girl appears to create some events with nulls in the `repeat_ends` which breaks my change - need to ensure [default: false](https://robots.thoughtbot.com/avoid-the-threestate-boolean-problem) or adjust the factories, or use plain objects ...

* https://semaphoreci.com/blog/2014/01/14/rails-testing-antipatterns-fixtures-and-factories.html
* http://berk.es/2015/02/19/when-factorygirl-leads-to-bad-habits/
* https://robots.thoughtbot.com/getting-sequential-a-look-into-a-factory-girl

**Comment by tansaku** [comment]
or in short term the specs pass with:

```rb
Event.where('repeat_ends = false OR repeat_ends IS NULL OR repeat_ends_on > ?', Time.now)
```
