### ISSUE TITLE
Install jitsi-meet on Azure

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1751]
Install our own jitsi-meet server
https://github.com/jitsi/jitsi-meet/blob/master/README.md

Install 'jibri' for recording to youtube:
https://github.com/jitsi/jibri

**Comment by mattlindsey** [comment]
I think the solution to the Jitsi streaming problem ("Streaming can not be started") may be to NOT detach the Jitsi tab from the other Chrome tabs.  Then the streaming to youtube seems to start OK.

**Comment by mattlindsey** [comment]
Note that I do see a `Handle jibri presence : failed` message in the JavaScript console when the streaming fails to start.

**Comment by tansaku** [comment]
extra steps for the screen sharing: 

https://github.com/jitsi/jitsi-meet/issues/192

also docker image: https://github.com/robertoandrade/docker-jitsi-meet

**Comment by tansaku** [comment]
@sigu and I have basic jitsi running on https://www.jitsi.agileventures.org/ but we need to configure screen sharing and youtube streaming
