### ISSUE TITLE
develop failing on test that previously past

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1754]
So develop was green, but this test starting failing recently:

```
cucumber features/hangouts/edit_youtube_url.feature:33
```

Here's part of the stack trace:

```
    When I am on the "Show" page for project "LS"                                          # features/step_definitions/basic_steps.rb:255
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      pause@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:6480:34
      JV@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:3410:51
      uV@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:3383:182
      bra@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:4146:126
      r1@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:4125:103
      https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:7223:167
      https://www.youtube.com/yts/jsbin/www-embed-player-vfllwwkQI/www-embed-player.js:373:293

```

It looks to me like the caching files for VCR and puffing-billy were not checked in with the original test commit, which makes it seem like something has changed in the way that youtube is responding to the request to embed a video in a project page?

I notice I can remove the error if I remove the ytplayer iframe from the project page - I guess this might be to do with requesting something from a video that doesn't exist.  I say that because when I add that video id to an event associated with a project on the develop server, I get the following error in the js console:

![](https://www.dropbox.com/s/pkorlde2c8ejhdk/Screenshot%202017-07-31%2014.52.05.png?dl=1)

that appears to be a request for the default youtube video image or https://i1.ytimg.com/vi/12341234111/hqdefault.jpg

and I'm not seeing that issue for general project videos on production ...

if I paste that URL into a browser I get: 
 ![](https://www.dropbox.com/s/q6or14smu0ivtu5/Screenshot%202017-07-31%2014.57.42.png?dl=1)

the ytplayer is updated by code in app/assets/javascripts/users.js:

```js
    function selectVideo(event) {
        event.preventDefault();
        player = $('#ytplayer');
        player.attr('src', 'https://www.youtube.com/embed/' + this.id + '?version=3&enablejsapi=1');
        $('#video_contents').text($(this).data('content'));

        $('html, body').animate({
            scrollTop: player.offset().top - 100
        }, 300);
    }
```

**Comment by tansaku** [comment]
I've tried removing the version and enablejsapi from the video player to no avail, and also adjusting to a real youtube ID, which also doesn't help

**Comment by tansaku** [comment]
I just got a couple of errors on the projects video page on my local box:

![](https://www.dropbox.com/s/rnp089v7td2vulg/Screenshot%202017-07-31%2015.21.15.png?dl=1)

![](https://www.dropbox.com/s/mtrugynrmnjrm62/Screenshot%202017-07-31%2015.21.46.png?dl=1)

**Comment by tansaku** [comment]
I get the same 404 error (that I get on the develop) if I use a non-existent video:

![](https://www.dropbox.com/s/rmvo61n5ip9h3bp/Screenshot%202017-07-31%2015.22.25.png?dl=1)

**Comment by lokeshh** [comment]
@tansaku If the problem is just with non existent videos not being displayed then shouldn't we simply fix it by replacing non-existent videos with existent ones.

**Comment by tansaku** [comment]
@lokeshh it did in the site - but not in the tests

**Comment by lokeshh** [comment]
@tansaku What do you meant by "it"?

**Comment by tansaku** [comment]
doing what you said - replacing with an existent video meant that I didn't get the error in the my local rails server when I ran it, but I still got it when I ran the cucumber test, although conceivably it was being cached by puffing billy ... although I was deleting all the cache files ...
