### ISSUE TITLE
Replace mercury editor in rails 4

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1756]
In order to upgrade to rails 5, it may be better to replace mercury with something first.

I imagine that the mercury rails engine is not compatible with Rails 5. Perhaps we might try switching to a simple markdown editor like https://github.com/rderoldan1/md_simple_editor (we saw convoluted test fails all over the place)

**Comment by mattlindsey** [comment]
I'm thinking some steps needed are:
- Remove all traces of mercury editor
- Convert pages from html to markup

**Comment by tansaku** [comment]
@mattlindsey I think this is a great initiative - if we can use the GitHub markup syntax I will be very happy: https://github.com/github/markup

**Comment by tansaku** [comment]
I guess the other way to go would be to offer a medium style editing experience: https://github.com/yabwe/medium-editor

What I'd really love is a medium style editing experience, but then the ability to edit in markdown if necessary ....

**Comment by tansaku** [comment]
oooh, looks like someone extended to add markdown support to the medium editor: https://github.com/yabwe/medium-editor/blob/9b511b2ae12f6481f6645b83d9878039e5ca8d0a/src/js/extensions/README.md#examples-of-custom-built-external-extensions

**Comment by tansaku** [comment]
@mattlindsey I wonder if the medium editor might allow us to leave the pages in html in the first instance ...

**Comment by mattlindsey** [comment]
@tansaku I wonder how hard it is to integrate into a rails app?

**Comment by tansaku** [comment]
@mattlindsey already done by someone: https://github.com/yabwe/medium-editor/wiki/wrappers-and-integration#rails

**Comment by tansaku** [comment]
@mattlindsey did  you want to work together on this on Friday? Let me know :-)
