### ISSUE TITLE
Add User ID code to existing Google Analytics code

### ISSUE THREAD

**Issue by lollypop27** [AgileVentures/WebsiteOne#1760]
Add User ID code to existing Google Analytics code so that the marketing team can filter the traffic on Analytics.

https://support.google.com/analytics/answer/3123666

https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id

**Comment by mattlindsey** [comment]
How to implement the User-ID in your tracking code
Google Analytics cannot generate, assign, or manage the unique IDs that are assigned as User-IDs. To use this feature, you must generate your own IDs and be able to consistently associate them with a set of data. In a typical scenario, these IDs can be generated through your authentication system, passed to an account at sign-in, and then sent to Google Analytics.Add the following line to your tracking code to send User-ID data to Google Analytics:

ga('set', 'userId', {{USER_ID}}); // Set the user ID using signed-in user_id.

Where the value of USER_ID is a string and represents the stable and unique ID retrieved from your system.

**Comment by tansaku** [comment]
thanks @mattlindsey - so I guess we should user @current_user.id or similar for the USER_ID?

**Comment by tansaku** [comment]
@FedericoEsparza @lollypop27 - how is this going?
