### ISSUE TITLE
handle empty github project more gracefully

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1789]
new project has empty github - caused rake task to hang:

> Waiting for Github to calculate project statistics for Lanternn/Unitcom

https://github.com/Lanternn/Unitcom

**Comment by tansaku** [comment]
in the short term I just unlinked that repo from that new project, but we need to handle that more gracefully:

https://www.agileventures.org/projects/unitcom

**Comment by tansaku** [comment]
I just used this to try to restart the scheduler:

> heroku ps:restart scheduler -r production

**Comment by tansaku** [comment]
we have a couple of tasks that run through all the github projects to grab stats from them


they are mentioned here: https://github.com/AgileVentures/WebsiteOne/blob/develop/lib/tasks/scheduler.rake#L3

you can see their details here: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/jobs/github_commits_job.r

we have a heroku scheduler that runs these tasks daily


basically the tasks were stuck (trying to process that info from github about the empty project) - and so all the projects after that one project were not getting updated

**Comment by tansaku** [comment]
https://devcenter.heroku.com/articles/scheduler

**Comment by praveendhawan** [comment]
@tansaku I found an existing issue on octokit for the same thing, and it's still open.
https://github.com/octokit/octokit.rb/issues/912

**Comment by tansaku** [comment]
@praveendhawan good show - see my comments in that issue ...

**Comment by praveendhawan** [comment]
@tansaku Just a question, on the issue explained at octokit, they are saying they need to check for a `non-202, or a 200/204 to return data`. I did not get that part why we only need to check for these statuses? 
One more thing that we can do is fix that issue using `retry_count`, run the loop only `retry_count` times, if the status is still not 200 return nil or zero. Or as you say we can send `retry_timeout` as option to `get_stats`

**Comment by tansaku** [comment]
@praveendhawan so the 200/202/204 stuff is internal to octokit and the way it is interacting with the github API.  *We* don't have to worry about them unless we want to get involved in octokit internals

regarding `retry_count` maybe, ... try it out - it depends on the type of hang that octokit is getting into

**Comment by praveendhawan** [comment]
@tansaku It might take me some time to fix the issue on octokit after reading through their contributing guides. Meanwhile, for a temporary fix, I will start working on the `retry_timeout` option in octokit. What do you think?

**Comment by tansaku** [comment]
@praveendhawan I'd say start on a temporary fix on our system if you can.  I'm not quite following how retry_timeout will help the issue in octokit - but if you're feeling confident you can see a way forward follow your instinct :-)

**Comment by praveendhawan** [comment]
@tansaku thanks, guess then I will start working on it. 👍

**Comment by praveendhawan** [comment]
@tansaku seems like the issue was not with octokit, but the code written [GithubCommitsJob
.get_contributor_stats](https://github.com/AgileVentures/WebsiteOne/blob/e36d7fdc8fe4a6479fee61d68648b8ddc40a3482/app/jobs/github_commits_job.rb#L57)

We are doing a loop untill we get contributors.

**Comment by tansaku** [comment]
@praveendhawan interesting - so we can fix that then?

**Comment by praveendhawan** [comment]
@tansaku yes, I will now make a failing test and start working  on fixing it.

**Comment by praveendhawan** [comment]
@tansaku sorry I mistakenly pressed `close and comment` button.

**Comment by tansaku** [comment]
no worries @praveendhawan - really great progress! :-)
