### ISSUE TITLE
Fix "regex_dos" issue in app/controllers/event_instances_controller.rb

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1795]
Request value used in regex

https://codeclimate.com/github/AgileVentures/WebsiteOne/app/controllers/event_instances_controller.rb#issue_599b64a9f9585400010001a2

**Comment by alexander-kh** [comment]
Essentially,
```ruby
  def local_request?
    request.env['HTTP_ORIGIN'] =~ /#{request.env['HTTP_HOST']}/
  end
```
returns offset or nil, and to eliminate the issue, I think, we can redefine the method this way:
```ruby
  def local_request?
    request.env['HTTP_ORIGIN'].include?(request.env['HTTP_HOST'])
  end
```
I'll create the pull request to test.
