### ISSUE TITLE
REST interface for event_instances

### ISSUE THREAD

**Issue by alexander-kh** [AgileVentures/WebsiteOne#1799]
Thoughts and suggestions on the subject.

@tansaku [wrote](https://github.com/AgileVentures/WebsiteOne/pull/1793#issuecomment-324696608):
> I'd love to completely sort out the REST interface for event_instances

[and](https://github.com/AgileVentures/WebsiteOne/pull/1770#issuecomment-322657504)
> In the first instance we could deploy the feature without any role-based authorization, but not link to it, so only those who new the link could do the edit. That might seem obtuse, but this is a heavy load bearing portion of the system, which is frustratingly not very RESTful (ideally all updates would take place through a single, coherent update method, and creation would take place via a create method but there are lots of dependencies)

Let's elaborate the general concept.

We have events and event instances as resources.
AgileVentures navigation:

| UI | URI | controller#action | instances on a page |
| --- | --- | --- | --- |
| Upcoming events | /events | events#index |
| Past scrums | /scrums | scrums#index* | latest 20 |
| Past events | /hangouts | event_instances#index | 30 per page |
| Create events | /events/new| events#new |

\* scrums#index:
```ruby
  def index
    @scrums = EventInstance.where(category: 'Scrum').
      last(20).sort {|a, b| b.created_at <=> a.created_at}
  end
```

**Categories of events**

At the present time, all events are divided into two categories:
* Scrums
* PairProgramming

Perhaps makes sense to separate meetings from scrums and add the distinct category for Mob Programming sessions:
* Meetings
* MobProgramming

**Actions with event_instances**

New users can review upcoming events and watch previous meetings (to get to know the process).

Team members may track project-related events and review missed meetings.
We can consider `description` attribute to add agenda, summary, and notes before and after the meeting.
Permissions to edit and delete event_instance can be provided to the event creator and project team members only.

**Routing**

* index
`/event_instances` as `/meetings`
We can display a list of the event_instances and add the filter by categories and projects.
General 'Meetings' category can be replaced with more specific ones:
  * Planning
  * Design Sprint
  * Marketing Meeting
  * Client Meeting
  * Community Talk

* new
Creation of the new event instances is the work of the `Event` model.

* show
/event_instances/id
`id` can be constructed from the event name and timestamp

* edit
/event_instances/id/edit

**New navigation**

| UI | URI | controller#action | instances on a page |
| --- | --- | --- | --- |
| Upcoming events* | /events | events#index |
| Past meetings | /meetings | event_instances#index | 30 per page (filterable by categories and project) |
| Create events | /events/new| events#new |

\* Can be replaced by 'Upcoming meetings' (event_instances#upcoming_meetings) to make the structure more coherent.
It will also allow adding agenda (default is the `description` of the associated event).

All suggestions are very welcome. The task is complex, and it has to be solved together.

**Comment by tansaku** [comment]
good discussion to start @alexander-kh - will have some input soon ...
