### ISSUE TITLE
Revise undertested helper modules

### ISSUE THREAD

**Issue by alexander-kh** [AgileVentures/WebsiteOne#1804]
## The goals are:

* remove unused helpers and methods
* add missing tests for the used methods

## Current state:

| app/helpers/ | test coverage, % | notes |
| --- | --- | --- |
| registrations_helper.rb | 66.67 |
| form_helper.rb | 66.67 |
| documents_helper.rb | 76.92 |
| event_helper.rb | 89.58 | issue #854 |
| youtube_helper.rb | 93.75 |
| application_helper.rb | 95.77 |

**Comment by tansaku** [comment]
I think the danger of refactoring in this project is that I don't have great confidence in the acceptance tests to be fully covering the operation of the app.

Refactoring is safest when one really trusts the tests.  It might be good to talk about refactoring priorities in a weekly meeting at some point

**Comment by tansaku** [comment]
@alexander-kh hope I haven't put you off working through these - I see you've got kind of an EPIC here - we've merged #854 right?  Did you want to knock off these other ones?  Or at least create tickets for them?
