### ISSUE TITLE
only show active projects in project dropdown on volunteers page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1811]
at the moment we are seeing every project that ever existed in the volunteers page dropdown:

<img width="523" alt="screenshot 2017-09-06 12 14 01" src="https://user-images.githubusercontent.com/30216/30109131-27005244-92fd-11e7-967d-30b266f4d91e.png">

we could make make this easier to navigate if we made it only active projects like we've done on the main project page ...

**Comment by aonomike** [comment]
What's the route for the volunteers page?
