### ISSUE TITLE
Notify project creator when new people join project

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1813]
**As a** project organizer/creator, 
 
**I want to** be notified when new people join my project within the AV site, 
 
**so that** I can reach out and personally welcome them.

**Comment by tansaku** [comment]
@federico Simple,
@tansaku Medium,
@praveendhawan Simple

**Comment by federico** [comment]
hello!

can you not tag me? thank you :)

**Comment by tansaku** [comment]
Oops sorry - we have a mismatch in user names from slack to GitHub :-/

**Comment by tansaku** [comment]
voted in on sprint 51
