### ISSUE TITLE
Several hours after event goes live, it still shows as live even though long over

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1820]
User complained about staleness of event when they did not reload page.

We could use the length of time of the event to approximate when it is likely to have ended.

**Comment by tansaku** [comment]
here is the existing eventcountdown functionality from the non-front page popup: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/assets/javascripts/global-modules/event_countdown.js

**Comment by tansaku** [comment]
here is the non-js thing that is on the home page: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/views/layouts/_event_link.html.erb
