### ISSUE TITLE
remove mentive from sponsors and replace with mooqita

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1821]
we are turning over one sponsor ...

**Comment by tansaku** [comment]
![logo slogan mooqita org height 200px](https://user-images.githubusercontent.com/30216/30803285-f6f67c5c-a1e0-11e7-97c8-effc197197cb.png)

**Comment by sigu** [comment]
Tansaku I can get comfortable with this one, assign to me :simple_smile:
