### ISSUE TITLE
confusion over which link to press during slack notifications of hangouts/youtube

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1921]
Got a report that the similarity between the hangout and youtube links in the slack notifications is confusing:

![](https://dl.dropbox.com/s/ppcdhsby8w9spr6/Screenshot%202017-10-19%2012.30.41.png?dl=0)

perhaps we could remove the title from the youtube "link/stream" and add something about "teleconference" to the hangout/jitsy link ...

**Comment by willnwhite** [comment]
Yes, and "(just listen)" to the youtube link.

**Comment by willnwhite** [comment]
Or "(listen only)".

**Comment by tansaku** [comment]
trick is that the ""Kent Beck" Scrum and Pair Hookup - All Welcome :-) Discuss Any Project, Ask Any Question, Or Just Listen In :-)" is the title of the event - almost need a way to select tag lines for different events ...

**Comment by tansaku** [comment]
```
@brentvardy Simple,
@tansaku Simple,
@yosef_benny_w No-opinion
```
