### ISSUE TITLE
start hangout on air button not working?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1927]
The start hangout on air button on individual events pages is no longer supported, and is producing talkgadget links that don't appear to work.

**Comment by tansaku** [comment]
We're updated the instructions for starting hangouts via the youtube live interface https://github.com/AgileVentures/AgileVentures/blob/master/RUNNING_A_STANDUP.md and are also working on a jitsi solution.

Perhaps we can patch up the button, or possibly even remove it ...?

**Comment by tansaku** [comment]
what would be great would be to link instructions on doing all this into the event pages themselves ...

**Comment by willnwhite** [comment]
I've verified my Youtube account with my mobile phone number. On clicking the link to YT in https://github.com/AgileVentures/AgileVentures/blob/master/RUNNING_A_STANDUP.md I get 
![screen shot 2017-10-23 at 16 58 05](https://user-images.githubusercontent.com/8081877/31899476-93881ede-b813-11e7-8a3c-d17421e788cb.png)

**Comment by tansaku** [comment]
@willnwhite can you try https://www.youtube.com/my_live_events ?

**Comment by tansaku** [comment]
see also https://support.google.com/youtube/answer/2474026?hl=en-GB

**Comment by tansaku** [comment]
I note the google hangout start button is really not working, in that although it starts a hangout - everyone ends up in their own separate space - we need to remove it and replace with info about how to start from youtube live

**Comment by tansaku** [comment]
```
@lara-t Simple,
@federico Simple,
@sigu Simple
```
