### ISSUE TITLE
Adjust Cucumber Scenario to explicitly tweak the `updated_at` variable

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1939]
#1809 was an annoying bug that I think we've finally fixed, and we now have a cuke scenario that covers its two forms.  However to catch the issues with `updated_at` I changed the `updated_at` value in the background data and so in principle that could have knock on effects on the other scenarios in the feature.

Also, it would probably be better to make explicit mention in the bug fix scenario that we're trying to avoid more recent updates to an event cause it to hang around when it's a new day and we want to be starting fresh ...

This is the bug fix scenario:

https://github.com/AgileVentures/WebsiteOne/blob/develop/features/hangouts/edit_hangout_url.feature#L41

and this is where updated_at was changed:

https://github.com/AgileVentures/WebsiteOne/blob/develop/features/hangouts/edit_hangout_url.feature#L18

The main thing for this would be to identify if we had a good existing step to use to modify the updated_at on an event instance or if we need to write a new one ...

**Comment by Mujadded** [comment]
Can i try this ?
