### ISSUE TITLE
RSVPing AV events

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#1957]
Not only does it encourage attendance, but it also informs the host if they need to cancel the event.

**Comment by tansaku** [comment]
UI to allow users to register plan to attend event, cancel if necessary - for specific upcoming next event in case of repeating events

**Comment by tansaku** [comment]
1. data model to support storing the information
2. interface to allow users to update info
  - website
  - slack
  - email

do we need an invitation feature?  

perhaps we should agree on user experience and maybe test it first?

Or perhaps export to google calendar is better?

**Comment by tansaku** [comment]
should we outsource event handling to google calendar?

**Comment by tansaku** [comment]
@mariam and I were just discussing having the event creator attending by default and starting with the ability for them to indicate they can't make it:  

```
Event  (next upcoming event instance), created by 'Federico'

  Planning to attend
    - Federico (host)  [can't make it]
    - [attend this event]
    - [attend every event]

[invite]
```

**Comment by tansaku** [comment]
@FedericoEsparza - @maryam21 and I were discussing how the RSVP functionality could include a sort of postponement by automatically marking the event creator as going to attend, and then having a button for the creator to indicate they couldn't make it, does that sound good? would be great to talk through some mockups of the functionality with you.

**Comment by tansaku** [comment]
@maryam21 - spoke to @FedericoEsparza and he likes the idea so good to proceed :-)
