### ISSUE TITLE
Add sponsor-sponsee relationship

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1960]
Add change to model to accommodate accurate representation of when a user sponsors another.

**Comment by tansaku** [comment]
```
@federico Medium,
@tansaku Simple,
@lara-t Simple,
@brentvardy Simple,
@mtc2013 Medium
```

Sam and Federico reviewed in wso meeting and agreed "medium" since it will require `sponsor_id` field to be added to subscription table
