### ISSUE TITLE
List of participants and duration of event not shown

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1967]
![av-past-events](https://user-images.githubusercontent.com/5248170/32849871-b4555e5e-ca30-11e7-938d-b8455534aca8.gif)

## Expected Behavior
List of participants and duration of event should show in the [Past Events](https://www.agileventures.org/hangouts) page 

## Current Behavior
It is NOT showing

## Possible Solution
It depends, of course, how the event data is stored and fetched. 

## Steps to Reproduce (for bugs)
Just follow the link. I did not run the acceptance tests but it should be pretty straightforward to replicate this bug if the structure of the data is known.

## Context
The effect of this bug could potentially be that users looking for past events deem them as irrelevant since no one took part in the hangout and that it is said to have lasted for less than one minute. 

## Your Environment
Not relevant

**Comment by tansaku** [comment]
thanks for reporting this @tochman - unfortunately since google retired their API there is no way to get the information on participants and duration automatically

We are looking at switching to Jitsi which does have an API, but need to roll our own jitsi server to avoid performance issues  ...

**Comment by tochman** [comment]
I suggest removing the elements where this information is supposed to be shown.
