### ISSUE TITLE
Previous Scrums modal contains no embedded recording

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#1968]
![av-past-scrums](https://user-images.githubusercontent.com/5248170/32849799-87cab834-ca30-11e7-8b54-17c49f231025.gif)

## Expected Behavior
The modal should show an embedded YouTube player

## Current Behavior
Not showing the player. See screen recording

## Possible Solution
Embed the player with the link to recording

## Steps to Reproduce (for bugs)
Visit production site

## Context
This is a UX problem. The timeline of Previous Scrums was originally created for users who miss a scrum but want to stay in the loop to have a chance to watch the recording. 

## Your Environment
not relevant

**Comment by tansaku** [comment]
thanks for reporting @tochman we seem to be having some systematic js issues on production only

the functionality in question is present on staging:

![](https://dl.dropbox.com/s/qbho5xxjqzbajyy/Screenshot%202017-11-15%2017.45.11.png?dl=0)

**Comment by tansaku** [comment]
we are experiencing js failures like this in various parts of the site including event calendar popups - but so far only in production and not on staging develop or local machines ... we are looking into this

**Comment by tansaku** [comment]
we are getting errors in the js console:

![](https://dl.dropbox.com/s/lhss998onk3vsp5/Screenshot%202017-11-15%2017.48.05.png?dl=0)

**Comment by tansaku** [comment]
on production that we don't get on staging or anywhere else ...

**Comment by tansaku** [comment]
the problem seems to be occurring at this point in the code https://github.com/AgileVentures/WebsiteOne/blob/develop/app/assets/javascripts/application.js#L87 which is @yggie 's custom code for handling turbolinks ... but why would this fail on production and not on staging ...?

**Comment by tansaku** [comment]
looks like the start of the error message is in the google analytics code ...

**Comment by tansaku** [comment]
disabling google analytics does not seem to help ...
