### ISSUE TITLE
Better representation of upgrading subscription

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1977]
Right now if a person is subscribed for a month or two as Premium and then upgrades to Premium Mob, then their subscription record type will be changed to premium mob rather than creating a new subscription for them and ending the old one.

So it will appear as they though had Premium Mob from the start.  Not ideal.

**Comment by tansaku** [comment]
voting 

```
@federico Medium,
@tansaku Medium,
@billfero Hard,
@mtc2013 Medium,
@benblanchard Medium,
@gael No-opinion,
@willwhite No-opinion
```
