### ISSUE TITLE
Some of the emails for users in the subscription.json api are nil

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#1981]
This may pose a problem when trying to figure out who they are on slack in the automated premium model.

**Comment by mtc2013** [comment]
From @tansaku:

irb(main):024:0> Subscription.order(:id).each{|s| puts s.inspect if s.user.nil? } ; nil
#<Premium id: 3, type: "Premium", started_at: "2016-10-25 16:46:56", ended_at: nil, user_id: nil, plan_id: 1>
#<Premium id: 5, type: "Premium", started_at: "2016-10-25 16:46:56", ended_at: nil, user_id: 47, plan_id: 1>
#<Premium id: 20, type: "Premium", started_at: "2016-10-25 16:46:56", ended_at: nil, user_id: nil, plan_id: 2>
#<PremiumF2F id: 32, type: "PremiumF2F", started_at: "2017-01-03 18:00:24", ended_at: nil, user_id: nil, plan_id: 3>
#<Subscription id: 39, type: nil, started_at: "2017-02-07 17:28:43", ended_at: nil, user_id: 3590, plan_id: 1>
#<Subscription id: 40, type: nil, started_at: "2017-02-28 02:00:22", ended_at: nil, user_id: nil, plan_id: 2>
#<Subscription id: 44, type: nil, started_at: "2017-04-25 08:41:15", ended_at: nil, user_id: nil, plan_id: 1>
#<Subscription id: 58, type: nil, started_at: "2016-11-10 11:11:00", ended_at: nil, user_id: nil, plan_id: 1>

**Comment by tansaku** [comment]
1. handle deleted users <-- @mtc2013
2. handle hanging subscriptions with nil users <-- @tansaku
