### ISSUE TITLE
Google sign up not working?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1989]
One user reported an error trying that method

**Comment by tansaku** [comment]
user in question confirms they saw this error:

![](https://dl.dropbox.com/s/vj1c7er18cpi4ho/Screenshot%202017-11-27%2010.43.04.png?dl=0)

**Comment by tansaku** [comment]
I can confirm that I cannot currently login with google auth ...

**Comment by tansaku** [comment]
I just tried updating the production secret - didn't help - something else going on here I think ...

**Comment by tansaku** [comment]
maybe something needs to change in: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/controllers/authentications_controller.rb

**Comment by nisevi** [comment]
@tansaku closing this since its already fixed :+1:
