### ISSUE TITLE
trying to log in with google when have already signed up with email leads to error - should automatically associate with account

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2010]
## Expected Behavior

When signing in with google or github we should add connection to any existing account with the same email.

## Current Behavior

currently login is blocked saying "Email is taken"

## Possible Solution

see functionality on user edit page where different google and github connections can be made to the same account

## Steps to Reproduce (for bugs)

1. ensure you have an account with an email that you also have on google or github
2. then login with a method you never used before
3. see the error message

## Context

We should allow folks to login and sign up as easily as possible.  rather than blocking them we should try to connect accounts and do login with existing accounts if they accidentally re-sign up

**Comment by Danielshow** [comment]
Hey @tansaku, is this issue still open. I can work on it

**Comment by tansaku** [comment]
@Danielshow this is an old one - maybe try replicating it to see if it's still an issue?  If it is then you're welcome to work on it :-)
