### ISSUE TITLE
have missing tabs show users how to add themselves to projects, add skills etc.

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2117]
tabs on user page don't appear in many cases - would be great to show them and offer advice about how to get connected ...

**Comment by nisevi** [comment]
One example it could be my profile, where I have joined `LocalSupport` and `WebsiteOne`

### WebsiteOne
![image](https://user-images.githubusercontent.com/3024789/35266573-f752f652-0023-11e8-927a-7ffdcc658d9b.png)

### LocalSupport
![image](https://user-images.githubusercontent.com/3024789/35266597-04db9874-0024-11e8-981b-c22a8f507b5b.png)

### My profile
![image](https://user-images.githubusercontent.com/3024789/35266535-e0ccef3c-0023-11e8-979f-13c6e4964df5.png)

As you can see even if I have joined those two project, the tab `activity`:

![image](https://user-images.githubusercontent.com/3024789/35266692-4d11643e-0024-11e8-8a99-36098aed5e77.png)

It doesn't appear.
