### ISSUE TITLE
Add CSS styling to FAQs and other detail elements so cursor is a pointer

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#2207]
![](https://dl.dropbox.com/s/z1jl7cws49gqeea/Screenshot%202018-03-08%2018.38.22.png)
 
Currently many of these throughout the static pages [(e.g. agileventures.org/premium_mob)](https://www.agileventures.org/premium_mob) show a text i-beam when hovering the cursor, making it less inviting to show the dropdown summary by clicking, especially for the NON-FAQS.
 
![](https://dl.dropbox.com/s/ykaw67h89wmr75f/Screenshot%202018-03-08%2018.38.54.png)
 
**_Possible solution:_**
 
Add:
`details {
    cursor: pointer;
}` 
to the css. However, may need Edit access, from @tansaku, to the Mercury Editor, which is on the way out.

**Comment by AbiSadhasivam** [comment]
I am willing to take this up!

**Comment by tansaku** [comment]
thanks @AbiSadhasivam - I'm not sure that even with access to the mercury editor that this styling will be allowed, although maybe ...

we've just assigned Stu to this, and @nisevi 's working on a new editor framework which will give us back full control of our full js and css ...
