### ISSUE TITLE
scrums being saved are defaulting to wrong project

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2272]
Updating a scrum to change the time is causing the wrong project (e.g. AV setup scripts) to be assigned to the project - we need to respect scrums with no project affiliation ...

**Comment by aonomike** [comment]
Any details of proposed solution?

**Comment by tansaku** [comment]
@mattwr18 sounds like an approach - but perhaps let's start with a test that replicates the bug just to be sure of what we're dealing with here - I may have mis-analyzed it ...

**Comment by aonomike** [comment]
What does "Updating a scrum" mean? does it mean "updating an event"?

**Comment by aonomike** [comment]
There is this scenario in `create_events.feature` 
```Scenario: New event defaults to cs169 project when it exists```
Could this be the reason creating "scrums being saved are defaulting to wrong project"?

**Comment by tansaku** [comment]
@aonomike that could be related - I think we do want "new events" to default to cs169, but existing events being edited shouldn't

To pin this down we should write a test that catches the bug, i.e. starts with an existing event with no project and then edits it (not changing the project) and check that the project remains unset ...
