### ISSUE TITLE
allow payment of premium in crypto

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2286]
@moddedgamer asked about this.  Looks like Stripe doesn't support bitcoin payments, but I wonder if we should integrate with something like https://www.coinpayments.net/

**Comment by tansaku** [comment]
ah, coinbase now has a solution: https://commerce.coinbase.com/

**Comment by Hess3000** [comment]
I think I'll take this one

**Comment by tansaku** [comment]
@Hess3000 - we did create a coinbase commerce account - although they don't support subscriptions, just one off payments ... :-/

**Comment by tansaku** [comment]
check out https://commerce.coinbase.com/charges/XPTAVPDN

**Comment by tansaku** [comment]
might be worth looking at https://pumapay.io/ or just even doing it with publishing our own address

**Comment by Hess3000** [comment]
@tansaku I think you get different addresses for different currencies, unless Coinbase give you a single address? Perhaps I could log in to your Coinbase account?

**Comment by tansaku** [comment]
@Hess3000 I assume there is an address for each currency ...

**Comment by Hess3000** [comment]
@tansaku hmm the initial plan was to list each of the address given on the coinbase link https://commerce.coinbase.com/charges/XPTAVPDN but the addresses seem to change on each new transaction...

**Comment by tansaku** [comment]
@Hess3000 ah interesting - maybe best to forget about Coinbase commerce and just go with a custom button that pops up a crypto address ... I guess the key thing we need is some sort of hook so that if the payment completes then our site is notified to confirm a person's upgrade etc.

**Comment by tansaku** [comment]
@Hess3000 we might want to look at some ruby/rails gems for crypto payments e.g. 

* https://github.com/Sailias/bitcoin_payable
* https://github.com/Sailias/cryptocoin_payable
* https://github.com/Salet/coinpayments
