### ISSUE TITLE
link static pages to place you need to go to edit them

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2296]
i.e. the correct file on AgileVentures/AgileVentures repo

**Comment by tansaku** [comment]
could be nice if this was even just an edit button? or better to have text and hyperlink

**Comment by tansaku** [comment]
@Hess3000 you were asking about making these dynamic - I think so - e.g. a page about-us should point to https://github.com/AgileVentures/AgileVentures/edit/master/ABOUT_US.md - we should be able to infer the location from upcasing and swapping hypens with underscores ...

**Comment by Hess3000** [comment]
Thanks, lucky you mentioned the path - I was looking at the actual about-us view page in the Websiteone repo!
