### ISSUE TITLE
updating event details destroys original event creator info

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2301]
it would be nice to retain info about who created an event, and who modified subsequently and display both on event show page

**Comment by tansaku** [comment]
![](https://dl.dropbox.com/s/iw46p9ufcmctw4l/Screenshot%202018-04-19%2016.10.12.png?dl=0)

**Comment by tansaku** [comment]
hi @NickSchimek - how are things going with this - any progress?

**Comment by NickSchimek** [comment]
I had to take some time off and haven't started yet. Give me a couple days to get caught up

**Comment by NickSchimek** [comment]
@tansaku Is this what you have in mind?

![image](https://user-images.githubusercontent.com/19519317/39610167-66d29b94-4f03-11e8-8560-c16eb16ec2c3.png)

**Comment by NickSchimek** [comment]
Would you also like 'created at' and 'updated at' dates as well?

**Comment by tansaku** [comment]
@NickSchimek looks great - yeah, created and updated dates would be great!
