### ISSUE TITLE
new content model does not embed images

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2303]
compare https://github.com/AgileVentures/AgileVentures/blob/master/HOW_TO_STREAM_A_JITSY.md and https://www.agileventures.org/how-to-stream-a-jitsy

**Comment by nisevi** [comment]
@tansaku you need to use the address where the image is being hosted by github, something like:

https://github.com/AgileVentures/AgileVentures/blob/master/HEAT_MAP.md

**Comment by nisevi** [comment]
@tansaku I fixed that one https://www.agileventures.org/how-to-stream-a-jitsy :+1:
