### ISSUE TITLE
emails for project joins are missing user name

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2321]
![](https://dl.dropbox.com/s/x8zzna2omnxxm6b/Screenshot%202018-04-30%2009.48.30.png?dl=0)

and we need functionality to allow project managers to say they don't want to get these emails.

@maryam21 could you look into the bug? thanks :-)

**Comment by maryam21** [comment]
I am guessing it's probably because it was set to use first_name and last_name and it just happened that this user didn't have those fields since they are not required.

**Comment by tansaku** [comment]
no worries - perhaps we can have email included by default?

**Comment by maryam21** [comment]
That's what taught about.
