### ISSUE TITLE
time dependency error in tests?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2330]
getting this today on 1st of month:

```
  1) DocumentsHelper#metadata should return metadata of the latest version of the document
     Failure/Error: expect(helper.metadata).to eq('Created about 2 months ago by User')
     
       expected: "Created about 2 months ago by User"
            got: "Created 2 months ago by User"
     
       (compared using ==)
     # ./spec/helpers/documents_helper_spec.rb:18:in `block (3 levels) in <top (required)>'
```

**Comment by Hess3000** [comment]
If the expectation can be either 'Created about 2 months ago by User' or 'Created 2 months ago by User' then we could just include both cases in the rspec expectation:

include('Created', '2 months ago by User') - instead of - expect('Created about 2 months ago)

**Comment by nisevi** [comment]
I fixed this one here https://github.com/AgileVentures/WebsiteOne/pull/2331
