### ISSUE TITLE
Remove mercury from documents.

### ISSUE THREAD

**Issue by nisevi** [AgileVentures/WebsiteOne#2339]
This is the last step we need to do to remove mercury definitely from AV :rocket: 

![image](https://user-images.githubusercontent.com/3024789/39567693-2120a0ac-4ec0-11e8-9c72-a9ba1917779b.png)

Currently as it can be seeing in the image `title` and `body` attributes of a document are being edited by using mercury. This functionality is what we need to remove.

**Comment by nisevi** [comment]
@tansaku before starting to work in this issue we need to merge the changes of this PR https://github.com/AgileVentures/WebsiteOne/pull/2302

**Comment by mattwr18** [comment]
@nisevi We are sprinting this week on WSO, what still needs to be done on this one?
