### ISSUE TITLE
Undefined method `/' for nil:NilClass

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#2364]
**Airbrake error:** [#5420](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/2211929454355675420)
**Airbrake project:** websiteone-production

**Error type:** `ActionView::Template::Error`
**Error message:** `` undefined method `/' for nil:NilClass ``
**Where:** `<no information>`
**Occurred at:** May 10, 2018 21:08:58 UTC
**First seen at:** May 10, 2018 21:08:58 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** `<no information>`
**File:** `/PROJECT_ROOT/app/views/subscriptions/new.html.erb`

**Backtrace:**
```
/PROJECT_ROOT/app/views/subscriptions/new.html.erb:6:in _app_views_subscriptions_new_html_erb__3186731136485773338_69892713457220
/GEM_ROOT/gems/actionview-5.1.6/lib/action_view/template.rb:157:in block in render
/GEM_ROOT/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in block in instrument
/GEM_ROOT/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in instrument
...
Caused by NoMethodError: undefined method `/' for nil:NilClass
```

**Comment by tansaku** [comment]
this is coming from https://www.agileventures.org/subscriptions/new which used to work ...

**Comment by mtc2013** [comment]
@tansaku in regards that bug, it seems liek theres a plan in the database "honorary premium" with nil price
nil/100.0 would give that error i think
could change it to price of 0

i suppose that if the following line from the controler

```Plan.find_by(third_party_identifier: params[:plan]) || default_plan
params[:plan] is blank its nil for some reason now?
```

that would create the issue because the third_party_identifier for said plan is nil

**Comment by tansaku** [comment]
funny because on the console, the default plan comes back as the standard premium one:

```rb
Plan.find_by(third_party_identifier: 'premium')
=> #<Plan id: 1, name: "Premium", free_trial_length_days: 7, third_party_identifier: "premium", amount: 1000, created_at: "2017-01-18 10:58:08", updated_at: "2017-01-18 10:58:08", category: nil>
```

**Comment by tansaku** [comment]
okay, fixed that by ensuring that honorary had a non-nil third_party_id ...

**Comment by tansaku** [comment]
weirdness ...

**Comment by nisevi** [comment]
It may be related to this one https://github.com/AgileVentures/WebsiteOne/issues/2234

**Comment by NickSchimek** [comment]
Oops, inadvertently referenced this issue. Although now that I'm here is this still an issue?

**Comment by tansaku** [comment]
thanks @NickSchimek - I think we'll close it
