### ISSUE TITLE
Projects index page redesign - past tab

### ISSUE THREAD

**Issue by bleena** [AgileVentures/WebsiteOne#2468]
As a user 
When I'm on the Projects' Page
I would like to see past projects displayed visually on the "past" tab. The page should be infinitely scrollable so that I can view more projects than displayed  by default on the past tab.
On the tab, the following would be useful for each project:
1. Project info
a. An image representing the project - it could be what the project is doing, or the client logo or something that gives more information.
b. Beneath each project image, it's high level overview, with number of members who contributed, duration of the project, and skills/tech stack used would be helpful.

**I don't know if client testimonials/success/impact can be shared?**

Wireframe: https://projects.invisionapp.com/share/J2MUJHLU35P OR 
https://drive.google.com/open?id=1x7p7ImoqAOJlLyk5jawL_Oa_6m5bRxSN.

**Comment by tansaku** [comment]
@bleena an alternative to pagination is infinite scroll - I know at least one user who prefers pagination, but I prefer infinite scroll ... @mattwr18 what do you think?

**Comment by mattwr18** [comment]
@leena I saw that you put up these stories, they look great! We are pairing on this today and they will help us take steps forward. :) 
@tansaku, to be honest I wasn't familiar with infinite scroll, but had a quick read up about it and it seems cool. For the learning experience, I would lean towards implementing the infinite scroll then.

**Comment by bleena** [comment]
I agree with you, not sure why I thought pagination would be better. I will update the wireframes when I get home. 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 16, 2018 at 1:50, Sam Joseph<notifications@github.com> wrote:   
@bleena an alternative to pagination is infinite scroll - I know at least one user who prefers pagination, but I prefer infinite scroll ... @mattwr18 what do you think?
