### ISSUE TITLE
consolidate name of URL for premium plans to something sensible

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2489]
just created https://www.agileventures.org/membership-plans to have a link without the word pricing in it.

on the site in the navbar we have the word "Premium" which links to this.  Would be good to delete https://github.com/AgileVentures/AgileVentures/blob/master/PRICING.md and standardize all on some consistent name

**Comment by aonomike** [comment]
@tansaku @mattwr18 the file https://github.com/AgileVentures/AgileVentures/blob/master/PRICING.md doesn't seem to exist in the branch I created from the develop branch. How do you advise for it to be deleted?

**Comment by tansaku** [comment]
hi @aonomike - so their isn't a develop branch in https://github.com/AgileVentures/AgileVentures it's just on master, and note that it's a different repo from  https://github.com/AgileVentures/WebsiteOne

I think what needs to be done here are a couple of things 

1) find all references to the url /pricing in WebsiteOne and replace them with something like /membership_plans

2) and then also in https://github.com/AgileVentures/AgileVentures/  rename https://github.com/AgileVentures/AgileVentures/blob/master/PRICING.md to https://github.com/AgileVentures/AgileVentures/blob/master/MEMBERSHIP_PLANS.md

this is because the static pages in WebsiteOne are pulled dynamically from the https://github.com/AgileVentures/AgileVentures/  repo - does that make any sense?

**Comment by mattwr18** [comment]
That makes sense @tansaku... we are gonna pair on it tomorrow. Hadn't even noticed that it was a different repo :p 
Although we were able to create a new `StaticPage.friendly` from `rails console` and were just going to copy the body of `Pricing` to the newly created `Membership Plans` friendly. 

Interestingly, @aonomike only had one friendly in his `rails console` while I had `32`! 
Any reason that might be the case? He was using the command while in the Docker instance...

**Comment by tansaku** [comment]
StaticPages are versioned using acts_as_versioned ... might be the reason ...
