### ISSUE TITLE
Slack id for project not updating properly

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2522]
## Expected Behavior

Expect a link to the slack channel when we update

## Current Behavior

Says project updated, when slack name/id is added but there is no change.  Checking on DB we can see that the field is still nil:

```
irb(main):001:0> Project.find_by slug: 'localsupport'
=> #<Project id: 3, title: "LocalSupport", description: "VAH's Local Support site is at  www.harrowcn.org.u...", status: "Active", created_at: "2014-02-01 17:04:13", updated_at: "2018-08-07 01:44:17", user_id: 3, slug: "localsupport", github_url: "https://github.com/AgileVentures/LocalSupport/", pivotaltracker_url: "https://www.pivotaltracker.com/n/projects/742821", pitch: "<div id=\"file\" class=\"instapaper_body md\" data-pat...", commit_count: 3763, image_url: "", last_github_update: "2018-08-06 06:19:05", slack_channel_name: nil, tag_list: nil>
```
![](https://dl.dropbox.com/s/5vex0ccogduv94p/Screenshot%202018-08-06%2007.59.19.png?dl=0)

Trailing the logs we see the params come through as expected:

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"....", "project"=>{"title"=>"LocalSupport", "image_url"=>"", "description"=>"VAH's Local Support site is at  www.harrowcn.org.uk", "status"=>"Active", "source_repositories_attributes"=>{"0"=>{"url"=>"https://github.com/AgileVentures/LocalSupport/", "_destroy"=>"false", "id"=>"87"}}, "pivotaltracker_url"=>"https://www.pivotaltracker.com/n/projects/742821", "slack_channel_name"=>"C0KK907B5"}, "commit"=>"Submit", "id"=>"localsupport"}
```

## Possible Solution

Hmm, not sure - I seem to be able to directly edit the project and set the `slack_channel_name` from the rails console ...

`slack_channel_name` appears in the permitted params:

```rb
  def project_params
    params.require(:project).permit(:title, :description, :pitch, :created, :status, :user_id, :github_url, :pivotaltracker_url, :pivotaltracker_id, :slack_channel_name, :image_url, source_repositories_attributes: [:id, :url, :_destroy])
  end
```

I'm able to update other fields correctly ... and in fact I was able to unset and reset via the interface - that's super-weird ...

and just worked straight out of the box for websiteone ... hmmm

## Steps to Reproduce (for bugs)

1. edit https://www.agileventures.org/projects/localsupport
2. add C0KK907B5 as slack channel name
3. save
4. see that project link is not updated

**Comment by NickSchimek** [comment]
This seems to have fixed itself. It is now working smoothly. Please re-open if anyone still sees this issue.
