### ISSUE TITLE
'agileventures.org' Events (Event Edit Confirmation & Gitter Notifications)

### ISSUE THREAD

**Issue by idfubar** [AgileVentures/WebsiteOne#2531]
## Expected Behavior

Instructions should be followable (ideally to the letter - with a screenshot that corresponds to the current design).  When editing an event, e.g. to add a Hangouts link (*per the directions under the 'Pair Programming On Air' tab of the CS169 course*), control should not forward to a '500' error page.  Further, Gitter chat notifications generated as a result should be confirmed to originate from the intended account (i.e. '@HangoutsNotifier' v/s '@tansaku').

## Current Behavior

The directions (which are detailed & include a screenshot) state, under step 8: "Copy and paste the URL from the address bar of the hangout into the "Edit event details" section of the AgileVentures event." - but doing so will result in the browser being forward to the 'agileventures.org' error page (with a '500' error message), presumably due to the length of the URL, and despite the event being successfully updated.  The notifier will successfully provide a link at the time when the event page is successfully updated - originating from '@tansaku'.

## Possible Solution

Instructions should be revised to reflect the current design(s) (i.e. no orange button, links copied from within Hangouts - rather than the browser, & a warning about the 'youtube.com' 24-hour waiting period required to "go live" for the first time).  Further, the design can be revised/improved to allow a longer URL field & to allow the notifier to be selected as needed (e.g. by an admin page/setting).

## Steps to Reproduce (for bugs)

1. Create a recurring event (e.g. Category = 'PairProgramming', For='All', Project='CS169', Repeats='weekly'
2. From the event page select 'Event Actions'->'Edit hangout link' & paste the URL provided by the browser for the Hangout (in the address bar and/or window "frame"); observe the '500' error.
3. Confirm the notification for the event is generated & originates from '@tansaku'.
4. Return to the event page & confirm the URL has been stored.

## Context

CS169.1x has a 'Submit Test Hangout on Air Recording' assignment during Week 1; the issue was encountered in the process of following the aforementioned directions step-by-step.  Careful review of the subsequent output (i.e. Gitter chat notification) suggests a change was made to the notifier within the last two months; the URL length issue could have been latent for some time.

## Your Environment

* Version used: CS169.1X ('2T2018')
* Environment name and version (e.g. Chrome 39): Safari 11.1.2
* Operating System and version (desktop or mobile): OS X (10.11.6)

**Comment by tansaku** [comment]
I think at some point we must have had a HangoutNotifier app (or user account), and that token expired - I can't seem to access that via my developer account - @NickSchimek pointed out the token was failing and I just updated to my personal one to get things working again.

Not sure what the best solution is there

And then separately we're encountering some kind of increase in the URL length of hangouts ...?  I guess in AV we are using youtube live where the url length is not an issue?

**Comment by idfubar** [comment]
Yes, as long the URL is copied from within the Hangout (rather than from the browser) the length will not trigger an error... but, given that the directions were written the other way, the error triggered from the longer URL seems a defect of some kind (though the precious thing, of course, is the epistemological currency - which is least impacted by new/congruent directions)...

PS:  Configurable could be best, e.g. your personal one for official class events and/or 'agileventures.org' premium events & '@HangoutsNotifier' for user-generated events (which tend not to be periodic)...
