### ISSUE TITLE
Hidden user unable to reset their password

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2585]
had an email:

> Hi I cannot reset my password I gt an error message site cannot be reached. Safari & Chrome

Have found the user is in the system, but is hidden - that shouldn't stop them resetting the password - have asked them for more details of the error

Should run some password reseting tests ...

**Comment by NickSchimek** [comment]
Can you elaborate on what a hidden user is?

**Comment by tansaku** [comment]
there's a field `display_profile` in the user model that determines whether a user will be displayed in the list of users or not, but actually I'm now pretty sure that's not the problem.

The user in question forwarded me the password reset emails and it looks like we're forwarding to this URL: https://agileventures.org/users/password/edit

and the problem is that while pasting agileventures.org in a browser will auto redirect to www.agileventures.org - prefixing it with https:// prevents it from working.  This is a known issue but I hadn't realised it had broken our password reset.  Or is was and I had forgotten - see #2405

**Comment by tansaku** [comment]
I did previously ask our hoster (gandi) about this:

> I just noticed that while our agileventures.org domain redirects to www.agileventures.org (as intended), that if someone tries https://agileventures.org/scrums that we get a site not reached error.

> http://agileventures.org/scrums works, as it redirects to https://www.agileventures.org/scrums

> Do you know how we can ensure that URLs like https://agileventures.org/ and https://agileventures.org/scrums will work ?

and they replied:

> Our Web Forwarding service does not support HTTPS. You'll want to point your domain's DNS directly to heorku rather than using our Web Forwarding service.

**Comment by tansaku** [comment]
I guess I need to remove the forwarding we have on gandi:

![](https://dl.dropbox.com/s/2yen1ueqc8c9ivm/Screenshot%202018-08-24%2009.52.53.png?dl=0)

**Comment by tansaku** [comment]
it looks like we already have the www extension pointing to heroku dns

![]https://dl.dropbox.com/s/29262n7tqq3zrxe/Screenshot%202018-08-24%2009.53.43.png?dl=0()

**Comment by tansaku** [comment]
this is probably what we need to change ...

![](https://dl.dropbox.com/s/1ev1zrjdnk8xdcw/Screenshot%202018-08-24%2009.56.48.png?dl=0)

since this is the root (I think) and it's currently pointing to gandi ...  but it's not immediately clear that there's a solution since others are struggling with the issue: https://stackoverflow.com/a/39646701/316729

**Comment by tansaku** [comment]
here's our current heroku domain setup:
```
$ heroku domains -r production
=== websiteone-production Heroku Domain
websiteone-production.herokuapp.com

=== websiteone-production Custom Domains
Domain Name            DNS Record Type  DNS Target
─────────────────────  ───────────────  ───────────────────────────────────
agileventures.org      ALIAS or ANAME   agileventures.org.herokudns.com
www.agileventures.org  CNAME            www.agileventures.org.herokudns.com
```

**Comment by tansaku** [comment]
I think we're actually sort of stuck since Gandi doesn't support the ALIAS method for DNS that would allow us to point the root at a URL and heroku doesn't have a fixed IP address we can put in the root A record.  The simpler fix for the password reset is to ensure that our rails app prefixes all urls with www ...

**Comment by tansaku** [comment]
and there's choices there too: https://stackoverflow.com/questions/32461029/add-www-to-url-when-its-not-present-on-ruby-on-rails

**Comment by tansaku** [comment]
ah - although on further investigation I think I find a quick fix here: https://github.com/AgileVentures/WebsiteOne/blob/develop/config/settings/production.yml#L42
