### ISSUE TITLE
Refactor search_by_language class method to a scope

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2612]
Scopes are more flexible than class methods (and lazier)

**Comment by vs77bb** [comment]
@tansaku Mind adding an acceptance criteria here, before I fund on Gitcoin? Hope your Hacktober is going well 🎃

**Comment by tansaku** [comment]
thanks @vs77bb - the acceptance criteria for this task is replacing the search_by_language method with a scope and thall the tests still passing
