### ISSUE TITLE
Rack::Timeout::Request::TimeoutException 

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2616]
@aonomike got the following issue:

![](https://dl.dropbox.com/s/200e9x1mk6rx211/Screenshot%202018-09-04%2010.51.50.png?dl=0)

**Comment by tansaku** [comment]
I think a possible solution might be adding this to .env:

```
RACK_TIMEOUT_SERVICE_TIMEOUT=200000000
```

the default RACK_TIMEOUT_SERVICE_TIMEOUT is super low - and is something that one can run into on slower computers, particularly if one is using virtualization like docker

**Comment by aonomike** [comment]
I added `RACK_TIMEOUT_SERVICE_TIMEOUT=200000000` to the .env and now page loads after running running `./docker/start.sh` 
The .env file is however gitignored so I cant push changes up
thanks @tansaku

**Comment by diraulo** [comment]
This is actually documented [here](https://github.com/AgileVentures/WebsiteOne/blob/develop/docker/README.md) see example env file

**Comment by tansaku** [comment]
no worries @aonomike - no need to push changes to .env file, but we might review whether it would be better to put it in git - I'm not sure how secret most of the items are, and might be better to have the default ones in the repo - @mattwr18 what do you think?

**Comment by aonomike** [comment]
Thanks for pointing that out @diraulo, maybe we should add the error that is expected to occur if the `RACK_TIMEOUT_SERVICE_TIMEOUT` is not set as in the documentation as maybe a known issue? @tansaku yes, the default ones should be in the repo just to have the application run out of the box. @mattwr18 can weigh in as well, but we spent some time figuring this out...
