### ISSUE TITLE
Faraday gem - Fixnum deprecation warning

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#2621]
Currently seeing the following deprecation warning in test output.
```
gems/faraday-0.9.2/lib/faraday/request/retry.rb:30: warning: constant ::Fixnum is deprecated
```

**Comment by NickSchimek** [comment]
@tansaku I looked into this briefly and the `twitter` gem needs to be updated so that a newer version of faraday can be used. And if a new version of faraday can be used then the `stripe` gem will be able to update to a newer version too. At first look it seems we may have to do small incremental updates.

**Comment by tansaku** [comment]
thanks for looking into this @NickSchimek :-)

**Comment by NickSchimek** [comment]
I removed the `twitter` gem and updated the `stripe` gem to version `3.4` without issue which allows us to update the `faraday` gem. Obviously twitter tests are failing after removing the `twitter` gem. It was mentioned to remove the associated code so I will proceed with that.  
For reference. The failing rspec tests are:
```
rspec ./spec/services/twitter_service_spec.rb:144 # TwitterService creates a valid twitter client object
rspec ./spec/services/twitter_service_spec.rb:148 # TwitterService configures the client object
rspec ./spec/services/twitter_service_spec.rb:157 # TwitterService sends a post request to the twitter api
rspec ./spec/services/twitter_service_spec.rb:131 # TwitterService with tweet notification setting enabled allows the tweet
```
And failing cucumber tests are:
```
cucumber features/twitter.feature:18 # Scenario: Event going live without valid live stream will have youtube link tweeted later when live
cucumber features/twitter.feature:27 # Scenario: Event going live without valid live stream still causes hangout link to be tweeted
cucumber features/twitter.feature:32 # Scenario: Event going live with valid livestream causes tweets of hangout link and youtube link to be sent
```
