### ISSUE TITLE
premium member just encountered error trying to update card details

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2631]
![screen shot 2018-09-10 at 14 18](https://user-images.githubusercontent.com/30216/45348232-018cbf80-b5a6-11e8-9201-d5b24ae3671f.png)

**Comment by mattwr18** [comment]
@tansaku Any idea how we can reproduce this? Or an idea on a way forward with this ticket?
It is labeled as high-priority, but if I am not mistaken the premium member was subsequently able to update their cards. 

Also, we have tests in place, any idea if they are ever intermittently failing?
