### ISSUE TITLE
ability to navigate from projects to events

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2656]
it would be nice to be able to find events associated with a project from the project pages themselves

**Comment by aonomike** [comment]
@tansaku any more pointers on how to go about this?

**Comment by tansaku** [comment]
@aonomike so this would involve updating the project view page.  I think that we should be able to get a list of events from the project instance via:

```rb
@project.events
```
and then we could loop through and display them - or if there are two many, just link to a search for events associated with that project

There's also showing past events, i.e. event_instances which could be handled similarly ...
