### ISSUE TITLE
better support for pausing premium subscriptions

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2662]
a few folks have asked to be able to pause and restart subscriptions - this is fiddly for me and difficult for us in that part of premium is having access to slack channels etc.  Whether we want to expose the UI to users or not, it would be convenient for an admin user to be able to set pauses and other changes to happen at a certain time ... although stripe does not support this that I can see  ... anyway, something to think about ...

**Comment by tansaku** [comment]
ooh, seems like I can dynamically edit trial length in the stripe interface - thus allowing up front management of pauses and plan swaps for premium members ...

**Comment by mattwr18** [comment]
@tansaku is this a closed issue or something we can do to move it forward? automate?
