### ISSUE TITLE
Better spacing between embedded video and video links

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2682]
On events show page, there is an embedded video player with youtube links below, but the spacing is off... Look at profile page's example of better css?
![screenshot at 2018-10-10 19 17 59](https://user-images.githubusercontent.com/26943915/46769339-db039680-ccc1-11e8-8db2-311e606de32c.png)

**Comment by leniquenoralez** [comment]
I can work on this 👍🏽
