### ISSUE TITLE
It's time div on event description page

### ISSUE THREAD

**Issue by dkuku** [AgileVentures/WebsiteOne#2689]
## Current Behavior

On the bottom of event description page, there's a div with orange border with the text

>  It's time! Please start the event.

![2018-10-15-102725_1920x1080_scrot](https://user-images.githubusercontent.com/904179/46942374-1ce76080-d065-11e8-8dec-f9cbaa7086c0.png)

## Expected Behavior

This div looks like a button, I think it should be hidden until really it's time.

## Possible Solution

We can add a view helper or hide it by default using js or gray it out.

**Comment by mattwr18** [comment]
hey @dkuku, we actually have an issue for this https://github.com/AgileVentures/WebsiteOne/issues/2664
Is it something you would be interested in working on?
