### ISSUE TITLE
Check that github api sensitive data is filtered out

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2690]
Need to configure vcr to filter this sensitive data

related to #2642, #2693

**Comment by mattwr18** [comment]
Information on how to configure VCR can be found here:
https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data

Some examples of how we have configured to filter out other sensitive data can be found here:
https://github.com/AgileVentures/WebsiteOne/blob/develop/features/support/vcr.rb#L13

Take a look at the Cassettes under `features/fixtures/cassettes/Update_github_*` first

**Comment by tansaku** [comment]
assigned to @georgy5 and @dkuku - we've invited you to AV WSO github team - once you accept we can add you as official assignees
