### ISSUE TITLE
Make rubocop happy

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2695]
Could we actually make rubocop happy or is that too big of a task?
Would it be a good learning experience?

**Comment by mattwr18** [comment]
![screenshot at 2018-10-15 17 18 40](https://user-images.githubusercontent.com/26943915/46976001-92235780-d09e-11e8-95b9-81d1037d0f7c.png)

**Comment by NARKOZ** [comment]
We can auto fix offenses where possible with `rubocop -a` and generate todo for others with `--auto-gen-config` option.

**Comment by mattlindsey** [comment]
`434 files inspected, 167 offenses detected`  as of today
