### ISSUE TITLE
Programming language filter not finding all Elixir projects

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#2725]
An injustice.

New programming language filter (which is a great feature!) not finding all Elixir projects:
![elixir projects](https://dl.dropbox.com/s/1g93r08ziuci8z6/Screenshot%202018-10-17%2015.43.37.png)
 
PhoenixOne isn't showing up.
 
![PhoenixOne project](https://dl.dropbox.com/s/30h5i28z38b1rqz/Screenshot%202018-10-17%2015.18.44.png)

**Comment by mattwr18** [comment]
![Screenshot at 2018-10-17 18:44:38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0ffc32a47b6b0012fec340/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c679177f3e7854ee7a27c5b270e5162f5b5c575cb053181d1ba6acda6fb4bc2e758c0e09efd8685b27c53518aaba8a1cbf01ee228a48d3b0ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c48c150f749e64854ac123171ab.png)

Apparently, PhoenixOne doesn't use Elixir @FedericoEsparza ???

**Comment by FedericoEsparza** [comment]
@mattwr18 Right. https://github.com/AgileVentures/PhoenixOne is mainly user stories in Gherkin and links to screenshots of Balsamiq.
 
The AV.org/PhoenixOne project has more github repos, though.

**Comment by mattwr18** [comment]
Could you share where we could find the repo that we can pull in Elixir from?

**Comment by FedericoEsparza** [comment]
@mattwr18 https://github.com/championer-org/championer_one
https://github.com/AgileVentures/sing_for_needs

**Comment by mattwr18** [comment]
I've heard of both of those great projects!! I can see that championer_one for example is the second github url registered for phoenix one... Maybe there is a way we can refactor the way the languages are being brought in which checks if there is more than one github url for a given project and to pull in the languages for all the registered github urls?

**Comment by mattwr18** [comment]
Or a way for project managers to manually add languages their projects use?

**Comment by FedericoEsparza** [comment]
@mattwr18 Adding languages would work, but perhaps allowing multiple languages would be more important (or as important). 
 
Given that many projects use more than one language, I think they should be discoverable via more than one selection.

**Comment by mattwr18** [comment]
hey @FedericoEsparza support for adding more than one language is most certainly supported... I think the issue is that the information is being pulled in from the wrong repo/ only one repo? So, if you search for HTML, for example you can find PhoenixOne... 
So, after further research, the repo that is being used to pull in the information on PhoenixOne is this one https://github.com/AgileVentures/sfn-client... so if you search for HTML, CSS, or JavaScript, you will find PhoenixOne.
It's not immediately clear to me why this repo is being chosen, but I do notice that the primary GitHub url is being set to the PhoenixOne Waffle board

**Comment by FedericoEsparza** [comment]
@mattwr18 Thanks for looking into this. I'll remove the waffle board links for now and update the primary repo with `championer_one` to see what that does. 

I just remembered that I added the Waffle board links because there was no field for additional issue trackers (I just created a ticket to fix that #2732 ).
 
At the time I added them, I think the view hadn't been updated to actually display the additional repos, so I didn't notice that the github icons would be misleading.

**Comment by tansaku** [comment]
@dkuku you said simple - @aonomike @mattwr18 you both said medium - room for discussion perhaps?

**Comment by dkuku** [comment]
@tansaku @anomike @mattwr18  I haven't looked how it is implemented but as I understand from the discussion the data of the programming language is pulled from github (which is not always right on the programming language used) and we have functionality use multiple languages then manual edit by the maintainer looks lake a reasonable option and easy to implement in rails.

**Comment by mattwr18** [comment]
@dkuku I believe it uses only the primary gihub repo, and I agree that project managers should definitely be able to say which languages their project uses would probably be a simple yet effective solution.
