### ISSUE TITLE
Add support for posting hangout/youtube links to nhs-wiki slack channel

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2765]
Currently, we need to manually add Hangouts/Youtube links to the nhs-wiki private channel on Slack.

We can add nhs-wiki channel's id to the CHANNELS hash in SlackService(soon to be HangoutNotificationService/YoutubeNotificationService)

Would need to make sure it doesn't post to other public channels as well similar to how we do for cs169? 

Relevant code can be found in app/services/slack_service.rb

**Comment by tansaku** [comment]
very different here, @mattwr18 said simple and I said medium and @aonomike said hard .... :-)
