### ISSUE TITLE
ensure that new members events are posted to slack #new_members channel

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2802]
currently there is no way to get automated posts to the #new_members channel - currently we hard code to post to the channels of the project that an event is associated with ... could create a "New Members" project?  Or some sort of over-ride to have events associated with slack channels independently of events ...

**Comment by tansaku** [comment]
@mattwr18 you said simple vs @aonomike and myself thinking medium so perhaps some discussion needed?

**Comment by tansaku** [comment]
Currently individual events will generate slack notifications if they are associated with certain projects.  For example, the new members event is associated with the av-community project, so when someone sets the hangout/youtube values for the event (taking it live) certain slack channels are pinged:

![](https://dl.dropbox.com/s/idiqqumcjsuvmm2/Screenshot%202018-12-13%2016.52.41.png?dl=0)

**Comment by tansaku** [comment]
this currently all relies on the hangout_notification_service.rb file:

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/services/hangout_notification_service.rb

at the moment you can see in this file how all the project <---> slack channel mappings are hard coded in the file

What we'd really like is for these project <--> slack channel mappings to be looked up dynamically off the project slack field.  In the best case we'd set it up so each project could maintain multiple slack channel ids (a has_many relation), and then in the project interface each project admin could select which slack channels would be pinged.

A short cut might be to allow events to have specific slack channel ids, i.e. just add a single slack_channel_id field to the events model and adjust the hangout_notification_service so that is also pings any channel specified on the event ..

**Comment by ElisaRmz** [comment]
What happens with the GITTER_ROOMS?
Should I do the same as with the slack channels?

**Comment by tansaku** [comment]
@ElisaRmz the GITTER_ROOMS are only for those events that are associated with the cs169 project - that functionality should remain as it is - no need to change or enhance that.   The critical support we need is the ability to dynamically set which slack channels an event will ping.

**Comment by ElisaRmz** [comment]
I have decided to remove the slack channel mappings and put them in the DB before adding the new notifications.
Take a look to #2975
