### ISSUE TITLE
Blocked on creating new projects

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2857]
## Expected Behavior

Should be able to create a new project
![screenshot at 2018-11-18 15 52 39](https://user-images.githubusercontent.com/26943915/48676198-7eaa5700-eb4a-11e8-9ccc-ee43a1c82412.png)

## Current Behavior

Getting a 500 Internal Server Error

**Comment by mattwr18** [comment]
This issue only comes up when adding an image url

**Comment by NickSchimek** [comment]
@mattwr18 I did some debugging and I have information for why this is occurring. When running locally I'm getting an invalid method error: `uniq!` This method is in ActiveRecord, and after any validations are done ActiveRecord runs the following block of here: https://github.com/rails/rails/blob/7550f0a016ee6647aaa76c0c0ae30bebc3867288/activerecord/lib/active_record/autosave_association.rb#L463

the value `attribute` should be an array, however in our codebase we're assigning error messages directly as a string in the ImageUrlValidator here: https://github.com/AgileVentures/WebsiteOne/blame/develop/lib/validators/image_url_validator.rb#L14 and here: https://github.com/AgileVentures/WebsiteOne/blame/develop/lib/validators/image_url_validator.rb#L18

It says this why changed for the rails 5 upgrade, however looking at the rails documentation it doesn't seem to have changed the way we add error messages to validations so I am unsure why this change was made. perhaps @tansaku knows. Either way we should be able to revert those two lines back to the way they were.

**Comment by NickSchimek** [comment]
ImageUrlValidator could be updated to something like this according to Rails docs https://guides.rubyonrails.org/active_record_validations.html#validates-with
```
record.errors[:base] << "This person is evil"
```
