### ISSUE TITLE
improve the 500 error page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2883]
## Expected Behavior

When there's a 500 error page the admins should be notified and the page served to the user should be apologetic and user terminology they understand - possibly even including  a form to send an email (or just a mailto link) to encourage them to ask for help 

## Current Behavior

looks like this:

![](https://dl.dropbox.com/s/23xouye06c0jzyz/Screenshot%202018-11-27%2017.10.19.png?dl=0)

## Possible Solution

see expected behaviour - just edit this file to make it more user friendly: 

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/views/static_pages/internal_error.html.erb

**Comment by tansaku** [comment]
@aonomike you voted medium, while @mattwr18 and @faith voted simple - maybe something to discuss?

**Comment by tansaku** [comment]
@ElisaRmz great that you're working on this - how's everything going?

**Comment by mattwr18** [comment]
here is a cool site I found @ElisaRmz, if you'd like to get creative https://rigor.com/blog/2012/07/15-awesome-fail-pages
