### ISSUE TITLE
Deprecation warning in tests. 

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#2924]
## Description
Seeing the following deprecation warning when running cucumber tests.

DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "LOWER(title)". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from search at /home/runner/WebsiteOne/app/models/project.rb:39)

Tasks: - Update the following query method.
- [ ] https://github.com/AgileVentures/WebsiteOne/blob/develop/app/models/project.rb#L39

**Comment by clementkng** [comment]
Hi @NickSchimek can I take this? I'm relatively new to Ruby/Rails so I'm interested in exploring and experimenting w/ different parts of the codebase.

**Comment by NickSchimek** [comment]
of course! go for it.
