### ISSUE TITLE
Add validation for repeat_ends for the Event model

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#2926]
## Description
When an event is created there are a couple different options based on the type of event, however in either case whether its a recurring event or a non-recurring event `repeat_ends` should be set regardless. 

When an event is created through the UI there are no issues and repeat_ends is set accordingly. It's set to `true` for non-recurring events and repeating events with an end date. It is set to `false` for repeating events without an end date.

### Steps to fix:
- [ ] Add validation for repeat_ends field
- [ ] Update any tests (if any) that break

**Comment by Danielshow** [comment]
hey @NickSchimek, I can work on this.

**Comment by NickSchimek** [comment]
Thanks @Danielshow Go for it! Let me know if there are any questions.

**Comment by Danielshow** [comment]
Done  @NickSchimek, I have raised a PR for this
