### ISSUE TITLE
Link https://imgur.com/upload in /projects/:id/edit

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#2941]
Link https://imgur.com/upload in /projects/:id/edit
 
It'd be nice to either link to a Markdown step-by-step guide, or the actual upload link:
 
<img width="928" alt="screen shot 2018-12-12 at 11 10 11 pm" src="https://user-images.githubusercontent.com/11988089/49930727-cf337c80-fe8a-11e8-9aed-602e00d6044a.png">
 
Copy the link:
 
<img width="769" alt="screen shot 2018-12-12 at 11 14 16 pm" src="https://user-images.githubusercontent.com/11988089/49930825-0570fc00-fe8b-11e8-88cd-6badaf8a6bb9.png">
 
Paste the link. It'd be nice to have the `https://imgur.com/upload` link where I highlighted a blank space:

<img width="971" alt="screen shot 2018-12-12 at 11 15 11 pm" src="https://user-images.githubusercontent.com/11988089/49930863-1ae62600-fe8b-11e8-9b2a-4f3613cd3daf.png">

Notice the required `i` subdomain AND `.png` extension required changes. Otherwise the image won't display on AV (500 error):

<img width="740" alt="screen shot 2018-12-12 at 11 23 44 pm" src="https://user-images.githubusercontent.com/11988089/49930878-26395180-fe8b-11e8-935a-f2e36767a259.png">

**Comment by clementkng** [comment]
@FedericoEsparza So just to be clear, is the point of this to provide a step-by-step markdown guide to detail how to upload a picture for the project or make it simpler than it currently is by linking an imgur upload link to the current edit page?

**Comment by FedericoEsparza** [comment]
@clementkng The latter, at least. Both would be nice.

A middle ground would be the link plus a few words of instructions next to it, for example:

_**You can upload an image at [imgur.com/upload ](https://imgur.com/upload )**_

**Comment by clementkng** [comment]
@FedericoEsparza If I go for the middle ground, what I'd like to try is maybe changing the `Image Url` text entry field into a text entry field and button, like something labelled `Upload a Project Image`. On hover, the entry box would specify that pasting a link from imgur requires the `i` subdomain and the `.PNG` extension, while the button would redirect to imgur.com/upload and then populate the entry field w/ the correct URL once an image is uploaded. Does that sound like that makes sense from a UX-perspective?

**Comment by clementkng** [comment]
@FedericoEsparza Based on the current image url validation [code](https://github.com/AgileVentures/WebsiteOne/blob/60d9dc87c9d53d8d0bad2efc00c4b78f23e4114e/lib/validators/image_url_validator.rb#L31), it seems that there are a number of domains still allowed other than imgur.com, and it doesn't make sense to enforce the `i` subdomain requirement for all of them. Would you want to allow only imgur images to be loaded, programmatically enforce the requirement for imgur images only, or just raise a message to the user telling them they need the `i` subdomain if they use `imgur` images?

**Comment by FedericoEsparza** [comment]
@clementkng We probably don't want to force people to only use imgur, if we don't have to. Having it as a recommended upload link, keeps users from being completely lost, however.

Sorry for overlooking your July 8th inquiry.
