### ISSUE TITLE
Users api endpoint not working in production, but works in development

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#2947]
It's not working in production either at our endpoint on dokku/azure websiteone-develop or in heroku production https://www.agileventures.org/api/v1/users
## Expected Behavior

That it works in production
## Current Behavior

Currently it returns a 404 page not found
## Steps to Reproduce (for bugs)

1. visit https://www.agileventures.org/api/v1/users
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):
![screenshot at 2018-12-17 18 58 09](https://user-images.githubusercontent.com/26943915/50115307-1c6a7200-022e-11e9-93b7-a0ee1b441268.png)

**Comment by mattwr18** [comment]
I have gotten it to work on https://develop.websiteone.agileventures.org/api/v1/users by limiting the request to 50 users. 

Will rack-timeouts affect get requests made through axios @tansaku @Kachulio1

**Comment by tansaku** [comment]
@mattwr18 not sure

I wonder why this isn't working in production ... maybe the code didn't deploy correctly ...

![](https://dl.dropbox.com/s/xnodycxrwh4dx1g/Screenshot%202018-12-18%2009.09.20.png?dl=0)

staging and production both have commit ids that should include that functionality.  Sensible - works on develop?  what could be interfering on prod ...?

**Comment by mattwr18** [comment]
@tansaku, I think I proved that it is not working because on staging and production, we have rack-timeout, which times out before the request has time to complete.

**Comment by mattwr18** [comment]
closing this as it doesn't seem to be an issue anymore
