### ISSUE TITLE
project page layout weirdness

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2953]
## Expected Behavior

That the project panes in the project page should be in a regular layout

## Current Behavior

sometimes they appear to have missing panes:

![](https://dl.dropbox.com/s/bjf3x85oecro7vd/Screenshot%202018-12-19%2009.56.02.png?dl=0)

## Steps to Reproduce (for bugs)

1. Go to project page https://www.agileventures.org/projects
2. scroll down
3. try different zooms

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

in firefox 63.0.3 and chrome 70

**Comment by tansaku** [comment]
@mattwr18 @javpet some tweaks needed to the CSS maybe?

**Comment by javpet** [comment]
Yeah I see that the issue is with this lovely 33.3% width given to the list items. Maybe just overwriting Bootstrap's width-value for this one might be a quick fix.
