### ISSUE TITLE
Remove destroy action in projects controller

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#2968]
## Description
The Destroy action in the Projects controller is empty. We currently do not allow user's to destroy projects. This should be removed along with the corresponding route.

This is done when the following tasks are completed...
- [ ] Update the `config/routes` to remove the DELETE route from the Projects resource.
- [ ] Remove the destroy action in the Projects controller.
- [ ] If a view template exists then remove that too.

**Comment by Danielshow** [comment]
Hey @NickSchimek, this has not been fixed.  I can pick it up

**Comment by NickSchimek** [comment]
Yep, go for it! Thanks!

**Comment by Danielshow** [comment]
Done @NickSchimek
