### ISSUE TITLE
remove this code climate silliness

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2977]
![](https://dl.dropbox.com/s/j0ej0vek4br7mac/Screenshot%202019-01-02%2016.10.01.png?dl=0)

this is valid ruby, should not be flagged

**Comment by tansaku** [comment]
found in https://codeclimate.com/github/AgileVentures/WebsiteOne/pull/2955

**Comment by clementkng** [comment]
Hi @tansaku, I'm not sure if this is still a valid issue. I wasn't able to find it in the original link nor the issues [link](https://codeclimate.com/github/AgileVentures/WebsiteOne/issues) for the entire project.

**Comment by tansaku** [comment]
@clementkng codeclimate does not seem to provide reliable linking of things unfortunately - it may be that this is not an issue, or it may be something we can clean up by looking at the codeclimate rubocop rules ... certainly not a huge priority ...
