### ISSUE TITLE
subscription controller name refactoring

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#3002]
we noticed that some of the variable names in the subscription code are a bit confusing - check out the subscriptions controller:

```rb
  def new
    @upgrade_user = params[:user_id]
    @sponsorship = @upgrade_user && current_user.try(:id) != @upgrade_user
    @plan = detect_plan_before_payment
  end

  def create
    @user = detect_user
    @plan = detect_plan_after_payment
    @sponsored_user = sponsored_user?
```

here the `@upgrade_user` contains a slug that is only present in the case of sponsorship, so would be better named maybe `sponsee_slug`

`@user` is in fact an actual user, but only present in the case of sponsorship, so would be better as `@sponsee` and `@sponsored_user` is a boolean - could be confused for a user - maybe better to rename as `is_sponsorship` - similarly for the method name

maybe some of these methods/vars that are specific to the views, should be moved from the controller to the view helper ...

**Comment by assignment6** [comment]
Can I work on this?

**Comment by clementkng** [comment]
Hi @tansaku @mattwr18 could I try taking this PR? I'm still relatively new to Rails, but would like to practice while improving the code quality of this project 😄

**Comment by tansaku** [comment]
@clementkng sure thing :-)

**Comment by snpd25** [comment]
@tansaku , Can I work on this issue?

**Comment by aonomike** [comment]
Hi @snpd25 sure thing, you can organize a pairing session just incase? also you can join our slack at [agileventures](https://agileventures.org/) incase you havent?
