### ISSUE TITLE
Fix UX for user profile card details button

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne#3008]
Currently, we have a link to edit your profile, then a update card details button, followed by another link to set status
This is not a good UX experience
## Expected Behavior

Have the button, either before or after the links, not sandwiched by them, also should the button design be the same as the profile upgrade to premium* button

![screenshot at 2019-01-18 12 46 58](https://user-images.githubusercontent.com/26943915/51393575-2a5a2e00-1b1f-11e9-8fb7-efbae29cd235.png)

**Comment by clementkng** [comment]
Hello @mattwr18, could I try this issue?

**Comment by clementkng** [comment]
Hello @mattwr18, could I try this issue?

**Comment by clementkng** [comment]
Is there a way to set up a credit card in a test local build (assuming that's what causes the `Update Card Details` button to appear)?

**Comment by mattwr18** [comment]
hey @clementkng that would be great!
you shouldn't need to set up a credit card
you might try checking out the seed data to see if you can log in as a premium user
it should be `premium@premi.um` I believe

**Comment by clementkng** [comment]
@mattwr18 Is there a consensus on whether the `Updated Card Details` button design should match the `Upgrade to Premium *` button? Also, should the "Premium Member" text be sandwiched between the buttons or placed somewhere else?

**Comment by mattwr18** [comment]
I think there is no consensus, you can feel free to make the change you think makes sense and upload a screen shot and we can give you a `PR` review. Thanks... sorry for the delayed response

**Comment by clementkng** [comment]
Will do. Also, I've noticed that there are files that are led off by underscores i.e. `_summary.html.erb`. Are these generated files/should we modify them to get desired behavior?

**Comment by mattwr18** [comment]
These are what are called partials in Rails
https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials

I think you will need to make changes to this file, yes... 
Have a look because there are certain people who can see this button and certain people who can't, as you noticed. If you move the button to a spot outside the logic that decides who can and can't see it, you will show it to everyone.
