### ISSUE TITLE
[Airbrake] [Production] param is missing or the value is empty: host_id

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#3143]
**Airbrake error:** [#5810](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/2458343825489785810)
**Airbrake project:** websiteone-production

**Error type:** `ActionController::ParameterMissing`
**Error message:** `` param is missing or the value is empty: host_id ``
**Where:** `<no information>`
**Occurred at:** Apr 15, 2019 20:50:20 UTC
**First seen at:** Apr 15, 2019 20:50:20 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** `<no information>`
**File:** `/GEM_ROOT/gems/actionpack-5.2.2.1/lib/action_controller/metal/strong_parameters.rb`

**Backtrace:**
```
/GEM_ROOT/gems/actionpack-5.2.2.1/lib/action_controller/metal/strong_parameters.rb:443:in require
/PROJECT_ROOT/app/controllers/event_instances_controller.rb:110:in check_and_transform_params
/PROJECT_ROOT/app/controllers/event_instances_controller.rb:8:in update
/GEM_ROOT/gems/actionpack-5.2.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in send_action
```

**Comment by NickSchimek** [comment]
@tansaku @mattwr18 

I'm able to recreate this error by issuing the curl command `curl -X PUT localhost:3000/hangouts/id`
where id is an arbitrary number. 

To prevent this error I'd suggest authenticating the user on `update` too.
