### ISSUE TITLE
Transfer project ownership

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#3161]
@tansaku and @mattwr18  I would to request the following feature. What do you think?

As an event/project owner, I would like the ability to transfer the ownership of an event to someone else. 
Currently as the event creator I have the ability to select wether or not I will be at the events, however there is no way for me to state wether or not I will be at the event when I am not the original creator of an event that I am currently running.
<img width="883" alt="Screenshot 2019-04-26 17 24 40" src="https://user-images.githubusercontent.com/19519317/56842257-75838b80-6848-11e9-8022-11f9b8cb2932.png">

**Comment by tansaku** [comment]
this is a great feature suggestion @NickSchimek !
