### ISSUE TITLE
Persist empty string when repeat ends is never

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#3215]
## Description
If a user sets `repeat ends` to `on` and selects an `end date` in the UI, and then changes the `repeats ends` to `never` the frontend-end still sends the `end date`, and it is persisted when it shouldn't be.

## Expected Behavior

The expected behavior is that when a recurring event never ends then it shouldn't have a repeat ends date persisted.

## Current Behavior

here is a screen cap of the params being passed when changed on the UI.
<img width="230" alt="Screenshot 2019-05-29 12 09 19" src="https://user-images.githubusercontent.com/19519317/58647540-aa0dbb80-82bc-11e9-8b97-d25fc08f9806.png">

## Possible Solution

I think this should be changed in the front-end so that when never is selected it sends an empty string or whatever the current default is (nil?).

## Steps to Reproduce (for bugs)

1. set repeats ends to on
2. set a date
3. set repeat ends to never
4. submit

**Comment by Danielshow** [comment]
I will start working on this @NickSchimek

**Comment by Danielshow** [comment]
Raised a PR for this
