### ISSUE TITLE
Update stripe to use two factor authentication

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne#3338]
Stripe says very soon they will not be accepting payments via banks if two factor authentication is not used by the users. This requires us to update our stripe authentication process so that it uses two factor authentication or face the consequences of loosing some payments as soon as September 14. [See link](https://stripe.com/gb/guides/strong-customer-authentication)

## Expected Behavior

Users making payment using stripe to use user authentication

## Current Behavior

Users making payment through stripe do not use two factor authentication
## Possible Solution

Research on how this can be implemented, if there is documentation from stripe
Implement the findings from the research

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by NickSchimek** [comment]
It doesn't seem like this will impact recurring payments. It states:

> Recurring direct debits on the other hand are considered “merchant-initiated” and will not require strong authentication.

It further states that: 

> For online card payments, these requirements will apply to transactions where both the business and the cardholder’s bank are located in the European Economic Area (EEA). 

Will continue to read more and learn more about the new policy. 

Considering we're concerned about recurring payments it seems that it won't have to big of an impact on AV. Either way it would be good to implement 2FA across the board.

**Comment by aonomike** [comment]
Thanks @NickSchimek for pointing these out. 

I have found [this resource](https://stripe.com/docs/payments/payment-intents/migration) which can guide the development of this.

**Comment by faithngetich** [comment]
@aonomike @NickSchimek I'd love to help out with this ticket.

**Comment by NickSchimek** [comment]
Here are the meeting notes from today that took place with Michael, Mike, Cire, and myself. 

Going forward for any new members signing up via Stripe, in order to be in compliance with the new [SCA](https://stripe.com/docs/strong-customer-authentication) requirements will need to update our stripe protocol to use the new PaymentsIntent API which will require changes to both the server side and client side. 

Planning the migration:

1. [Identify payment flow](https://stripe.com/docs/strong-customer-authentication/migration#step-1):   Recurring payments ✔️
2. [Determine integration path](https://stripe.com/docs/strong-customer-authentication/migration#step-2):  For Recurring payments

    - [ ]     Mandate Collection: In your checkout flow, add some consent text
                > State that by completing checkout, the customer consents to your initiation of payment 
                > on their behalf. State the anticipated frequency of payments. Explain how the amount of 
                > the payments will be determine. 
                    - May need confirmation with @tansaku on exact wordage to use.
    - [ ]     Strong authentication of the first transaction.
                > Merchants are required to authenticate the customer when the mandate is set up. This 
                > can either be done by the first payment with the card or when saving the card to a 
                > customer without making an initial payment.
    - [x]      Flagging subsequent transactions. - This is handled by stripe

3. [Implement the new integration path](https://stripe.com/docs/strong-customer-authentication/migration#step-3)
    - [ ] User the [Payments Intent API](https://stripe.com/docs/payments/payment-intents)
            - Server side: Follow the [Migration guide](https://stripe.com/docs/payments/payment-intents/migration)
            - Client side implementation: [stripe.js](https://stripe.com/docs/payments/payment-intents/web)
4. [Test dynamic authentication](https://stripe.com/docs/strong-customer-authentication/migration#step-4): 
     - [ ] [Implement testing](https://stripe.com/docs/testing#regulatory-cards)

**Comment by NickSchimek** [comment]
We scoured the source code and could not find any place where we are actually implementing the ChargeAPI therefore there is no need to update to the IntentsAPI. We do create a Stripe::Customer and pass the card information off to Stripe for them to take care.

According to this there are no changes for us to make:
<img width="759" alt="Screenshot 2019-09-19 10 33 05" src="https://user-images.githubusercontent.com/19519317/65267481-ee220780-dac9-11e9-82cb-acace936101a.png">

As we do pass a stripe token with a method to customer.
<img width="753" alt="Screenshot 2019-09-19 10 41 47" src="https://user-images.githubusercontent.com/19519317/65267568-21649680-daca-11e9-84e9-5612d2856222.png">

If there is anything that needs to be done then it seems it is handled by Stripe, as we are currently not implementing the ChargeAPI. 

Perhaps @tansaku can verify this. It seems like everything is configured in the Customer [dashboard](https://dashboard.stripe.com)

**Comment by NickSchimek** [comment]
It was determined that nothing was needed to be done on our end.
