### ISSUE TITLE
Allow authorized user to C/U/D and to assign other authorized users

### ISSUE THREAD

**Issue by NickSchimek** [AgileVentures/WebsiteOne#3554]
## Description

Currently anyone can create/update/destroy projects. Allowing any member to do this has its pros and cons; however the cons are outweighing the benefits pros. There are seeing projects being created that are advertisements.

### Task
Option 1 (authorize)
- Assign site admin role to a developer
- Only allow people with that role to CUD project
- Only allow site admins to add project admins and other site admins
- Provide ability to seed site admin

Option 2
- Remove the route, controller actions, and any other associated code for the creation, update, and deletion of projects.
- Update tests accordingly

**Comment by riccardo-giomi** [comment]
There is an old issue to remove the destroy action which was actually solved; issue: #2968, merged PR: #3228. Shouldn't that issue be closed?
