### ISSUE TITLE
**Review and improve end-to-end tests**

### ISSUE THREAD

**Issue by ethanstrominger** [AgileVentures/WebsiteOne#3585]
As they are now the cucumber end-to-end tests are  flaky and prone to false positives. They are also extremely slow.

**Comment by mattlindsey** [comment]
First step should be eliminate following errors, most of which seem to be changes made to membership email text without fixing the corresponding cucumber tests:

Failing Scenarios:
cucumber features/premium/charge_activity.feature:37 # Scenario: Sign up for premium f2f membership
cucumber features/premium/charge_activity.feature:46 # Scenario: Sign up for premium plus membership
cucumber features/premium/credit_card.feature:15 # Scenario: User decides to change card details
cucumber features/premium/credit_card.feature:22 # Scenario: User changes card details, but encounters error
cucumber features/premium/credit_card.feature:34 # Scenario: User without existing card wants to add one
cucumber features/premium/credit_card.feature:41 # Scenario: User without existing card wants to add one but encounters an error
cucumber features/premium/sponsor_other_member.feature:19 # Scenario: User upgrades another user from free tier to premium via card
cucumber features/premium/sponsor_other_member.feature:48 # Scenario: non logged in user upgrades another user from free tier to premium
cucumber features/premium/subscribe_self_to_nonprofit_basic.feature:12 # Scenario: Sign up for nonprofitbasic  support
cucumber features/premium/subscribe_self_to_premium.feature:14 # Scenario: Pay by card
cucumber features/premium/subscribe_self_to_premium.feature:23 # Scenario: Logged in user has sponsor set to self
cucumber features/premium/subscribe_self_to_premium.feature:33 # Scenario: Pay by card (with free trial month)
cucumber features/premium/subscribe_self_to_premium.feature:54 # Scenario: Pay by card, but encounter error
cucumber features/premium/subscribe_self_to_premium.feature:72 # Scenario: Pay by card, and default to Premium
cucumber features/premium/subscribe_self_to_premium_mob.feature:13 # Scenario: Pay by card
cucumber features/premium/subscribe_self_to_premium_mob.feature:23 # Scenario: Pay by PayPal
cucumber features/premium/subscribe_self_to_premium_mob.feature:33 # Scenario: Pay by card, but encounter error
cucumber features/premium/upgrade_membership.feature:36 # Scenario: User upgrades to premium from free tier
cucumber features/users/omniauth.feature:22 # Scenario: Try to log in with invalid credentials
cucumber features/users/omniauth.feature:28 # Scenario: Try to log in with invalid credentials

414 scenarios (20 failed, 394 passed)
3213 steps (20 failed, 31 skipped, 3162 passed)

**Comment by mattlindsey** [comment]
Update: I ran all of the above failing feature files individually and they passed, so indeed there is flakiness.
