### ISSUE TITLE
Events: Subscribe to AgileVentures calendar

### ISSUE THREAD

**Issue by ethanstrominger** [AgileVentures/WebsiteOne#3590]

**Comment by mattlindsey** [comment]
Note that subscription is available now but currently a little hard to do.  You must copy the calendar link 'http://agileventures.org/calendar' and paste it into your calendar app as a 'subscription.'   Ideally WebsiteOne would ask which calendar app you use (google, iCal, etc.) then automatically (when you click the button) subscribe you.  Other sites do this well.

**Comment by mattlindsey** [comment]
To automatically subscribe, we can just change the protocol of the link to 'webcal': https://stackoverflow.com/questions/59843615/how-to-automatically-update-ical-events-rails-daily
