### ISSUE TITLE
Heroku stack end-of-life

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3639]
As of November 2, 2020 we are no longer getting security updates or are able to build.

**Comment by aonomike** [comment]
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by mattlindsey** [comment]
Appears we need to upgrade ruby.  I will add a PR for that: 
2.7.2, Rubygems: 3.1.4

remote:  !
remote:  !     The Ruby version you are trying to install does not exist on this stack.
remote:  !
remote:  !     You are trying to install ruby-2.5.1 on heroku-20.
remote:  !
remote:  !     Ruby ruby-2.5.1 is present on the following stacks:
remote:  !
remote:  !     - cedar-14
remote:  !     - heroku-16
remote:  !     - heroku-18
remote:  !
remote:  !     Heroku recommends you use the latest supported Ruby version listed here:
remote:  !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
remote:  !
remote:  !     For more information on syntax for declaring a Ruby version see:
remote:  !     https://devcenter.heroku.com/articles/ruby-versions
remote:  !

**Comment by mattlindsey** [comment]
Upgraded staging to cedar-18, but when we tried to push the develop branch to it we get errors on precompiling the assets:
```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        Yarn executable was not detected in the system.
remote:        Download Yarn at https://yarnpkg.com/en/docs/install
remote:        /tmp/build_cec5bc86/bin/rake: No such file or directory - java
remote:        rake aborted!
remote:        YUI::Compressor::RuntimeError: Command 'java -jar /tmp/build_cec5bc86/vendor/bundle/ruby/2.6.0/gems/yui-compressor-0.12.0/lib/yui/../yuicompressor-2.4.8.jar --type css --charset utf-8 /tmp/yui_compress20201130-3679-1elilba' returned non-zero exit status
remote:        /tmp/build_cec5bc86/vendor/bundle/ruby/2.6.0/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:106:in `block in compress'
```

The staging branch builds fine on cedar-18, but it doesn't include any updates since October 2019.  
Thus we may have to back out changes done since then unless we can figure out the error above.

**Comment by mattlindsey** [comment]
Fixed it!  Just remove YUI compressor from Gemfile and config/environments/production.rb.

**Comment by mattlindsey** [comment]
The PR for this is still failing the cucumber tests.  It may be because we are using Poltergiest for headless testing, which is old and doesn't support new javascript syntax.   
So I tried upgrading to chrome headless (chromedriver, https://thoughtbot.com/blog/headless-feature-specs-with-chrome), but then I get even more feature failures!
