### ISSUE TITLE
Research the best way to handle legacy db data columns now being converted to json

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#3818]
The migrations in the pr here involve converting a text column to json:  https://github.com/AgileVentures/WebsiteOne/pull/3817

The two columns are exclusions and participants.  We probably have production data in a text format that isn't json on participants from hangout legacy data.  Not sure about exclusions for events.

**Comment by mattlindsey** [comment]
It’s possible the data gets ‘converted’ by the change_colum in the migraton (”json USING CAST(exclusions AS json)) and may not be lost.  So we need to test on production data somehow.

There are a few possible solutions here: https://stackoverflow.com/questions/17075173/rails-migrations-change-column-with-type-conversion

**Comment by mattlindsey** [comment]
Database was lost, so we no longer need to do this.
