### ISSUE TITLE
Upgrade to rails 7

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3819]
Upgrade to rails 7.

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by Florence-Njeri** [comment]
@mattlindsey I'd love to help with the Rails upgrade

**Comment by mattlindsey** [comment]
Hi @Florence-Njeri.  That's great! Let me know if you have questions about the setup. We have a chat on slack that I can send you a link for.

**Comment by Florence-Njeri** [comment]
Hi Matt,

I’m currently setting up the developer environment and I require access to
the .env file content. I’d also appreciate it if you sent me the slack
invite.

Best regards,
Florence Njeri.

**Comment by mattlindsey** [comment]
Great.  I think you can get an invite here: https://agileventures.slack.com/messages/websiteone and I can give the the .env file there.
Matt

**Comment by Florence-Njeri** [comment]
There are only the register/login options. The register options limit me to
use these domains:

   - agileventures.org
   - berkeley.edu
   - binghamton.edu

**Comment by mattlindsey** [comment]
@Florence-Njeri . Oh, sorry. Usually you would get an email, but can probably use this: https://join.slack.com/t/agileventures/shared_invite/zt-1587bzqk7-Y8ACcBKmwi0SWbI3Iu78eg

**Comment by mattlindsey** [comment]
@Florence-Njeri.  Someone just posted this, which looks good: https://github.com/railslink/resources/wiki/Rails:-Upgrade-process
We recently upgraded to latest rail 6, so maybe 7 won't be too painful.

**Comment by Florence-Njeri** [comment]
Thanks, I'll check it out.

**Comment by mattlindsey** [comment]
@Florence-Njeri.  No rush, but are you still working on this?

**Comment by Florence-Njeri** [comment]
Hi Matt,

This task is in progress. Hoping to be done by end of the week.

**Comment by mattlindsey** [comment]
@Florence-Njeri.  Great, thanks.  Don't forget to do 'git pull upstream develop' to get recent updates to the develop branch.

**Comment by mattlindsey** [comment]
I think you can probably go right to version 7.0.4.2
