### ISSUE TITLE
Deploy to Vercel.com

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3830]
Create a test/staging deployment to Vercel.com, which should be free of cost.

Apparently this is best done using Kubernetes like the instructions below.
https://kubernetes-rails.com/

**Comment by edmilsonefs** [comment]
Seems interesting,  there is also [https://fly.io/](https://fly.io/) but I don't know if we could ran what we want 4 free.

**Comment by mattlindsey** [comment]
I'm closing this because Vercel seems to only support rails a backend service.

Maybe one of these will work:
https://github.com/learnk8s/free-kubernetes
