### ISSUE TITLE
Add account confirmation emails for email registrations.

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3896]
Registration by email is currently disabled in production because otherwise hundreds of fake/spam accounts get generated monthly.

Add the requirement to 'confirm' email accounts by clicking on a link in a confirmation email.  The devise gem should have this feature.   Then we can re-enable email account registration on production (in production.yaml).

**Comment by wordhouse66** [comment]
Hello Matt. I would like to take this on if it is ok

**Comment by mattlindsey** [comment]
Closing this because it's probably not a good idea to re-enable email registration without a way to avoid spam accounts.
