### ISSUE TITLE
Log out button styling messed up

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3897]
After you log in and try to 'Log out,' the button is squished due to recent change in the way submits work in our javascript.  So the styling needs to be fixed.

**Comment by RajivRnjan** [comment]
Hello Sir, I want to be fixed the issue. Please assign to me.

**Comment by mattlindsey** [comment]
Hi @RajivRnjan.  Sure!  Let me know if you have any issues setting up the project.

**Comment by RajivRnjan** [comment]
Created a PR, please check

**Comment by mattlindsey** [comment]
Fixed by #3901
