### ISSUE TITLE
Full calendar missing on Events page

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3910]
A calendar used to appear on the Events page, but has recently disappeared.  If we add it back there should be test that would fail if it disappears again.
Also, it might be better to add it back on a separate page with a link from the Events dropdown in the header.  That might be cleaner and less busy.

It can be seen on this PR from last year:
https://github.com/AgileVentures/WebsiteOne/pull/3843

**Comment by lokeshk88** [comment]
Please explain what the issue in ur screenshorts .
