### ISSUE TITLE
User's index visual improvements for long nicknames

### ISSUE THREAD

**Issue by cluk3** [AgileVentures/WebsiteOne#744]
As you can see in this screenshot:
 ![now_chrome](https://cloud.githubusercontent.com/assets/6255324/12295267/57e62500-ba00-11e5-9b5b-5f690d2a329a.png) 

long nicknames are breaking the layout in large screen.
You can easily fix this setting: `.media-body { 
display: block;
max-width: 100%;
} `
Here is the result on chrome:
![after_chrome](https://cloud.githubusercontent.com/assets/6255324/12295603/5b587880-ba02-11e5-8ac2-e5ef550976f8.png)

You can also visualize the whole nickname changing the .index-summary class:
`.index-summary { overflow: auto; word-wrap: break-word }`
and here is the result:
![last_chrome](https://cloud.githubusercontent.com/assets/6255324/12295639/9a2d612e-ba02-11e5-8ec2-d7a493f58394.png)

I would make a pull request but i don't really know which .css i should change :sweat_smile:

**Comment by tochman** [comment]
Hi @cluk3 Great initiative. It is probably https://github.com/AgileVentures/WebsiteOne/blob/develop/app/assets/stylesheets/global/users.scss
Do open a chore at the projects Pivotal Tracker https://www.pivotaltracker.com/s/projects/982890

**Comment by tansaku** [comment]
@tochman will @cluk3 be able to open an issue on the pivotal tracker?  I don't think non-members can add items ...

**Comment by freeranger** [comment]
PT is now a moot point so @cluk3 if you're still around then you could take a branch and make the change.
@tansaku - Do you prefer the ... style or the word-wrap style?
Note to whoever does this: overflow-wrap is the "new" word-wrap so you might want to look at using that as well (for forwards and backwards compatability)
http://www.w3.org/TR/css3-text/#overflow-wrap-property

**Comment by tansaku** [comment]
not sure about style - would need to look at screen shots

**Comment by freeranger** [comment]
@tansaku if you look further up the thread, @cluk3 did an excellent job of providing examples of both ;)
First screenshot is what you have now, second is with the ellipsis and the third screenshot shows the wrapped style 
Note: there is another wrapped style which can hyphenate the word but that might make you think the hypen is part of the name...

**Comment by freeranger** [comment]
@tansaku @diraulo any preference for the style we go for? (See screen shots).
I could pick this up...

**Comment by tansaku** [comment]
I think break word looks ugly @freeranger

**Comment by freeranger** [comment]
@tansaku - Ok so go with this one:

![image](https://cloud.githubusercontent.com/assets/1401069/13807698/61e5e550-eb5a-11e5-8400-c45358158d88.png)


and tooltip it up to get the full name?

**Comment by tansaku** [comment]
yeah :-)
