### ISSUE TITLE
Do we need the @channel tag for every pairing in pairing_notifications channel

### ISSUE THREAD

**Issue by dalupus** [AgileVentures/WebsiteOne#746]
I realize the idea it to get notified of every pairing, but you get that with or without the channel tag.  The channel tag just marks the new message more forcefully.  I think the channel is a good idea, and gives a good sense of the amount of pairing going on, however many may drop the channel because of the channel tag since it does a forceful notification of every single chat.

**Comment by tansaku** [comment]
good point @dalupus - I wonder if if would make more sense to switch to the @here tag ...? which is slightly less forceful ...

**Comment by tansaku** [comment]
if someone wanted to look into changing this, it is the https://github.com/AgileVentures/agile-bot project that handles this functionality I think

**Comment by diraulo** [comment]
@sampritipanda do you want to have a go at this? Perhaps have a pairing session with someone to get them familiar with the bot's code too :-).

I'd be interested if I can be available at a reasonable time for you.

**Comment by tansaku** [comment]
@sampritipanda @diraulo you might want to check out https://api.slack.com/docs/formatting - there are quite a lot of options for formatting messages from slack bots that I think we haven't taken advantage of yet, e.g. with URLs

**Comment by sampritipanda** [comment]
@tansaku Could you give me an example of something that we could improve with that?

**Comment by tansaku** [comment]
well instead of displaying the entire URL we could be displaying a "click here to join hangout" or "click here to watch the live stream" hyperlink

**Comment by tansaku** [comment]
let's have the @here tag in the pairing and scrum events going to general and project channels as a start

**Comment by tansaku** [comment]
want to move this slack code into ruby
