### ISSUE TITLE
arrows in time selector not appearing on event creation page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#755]
![arrows missing](https://www.dropbox.com/s/m057kqv2fvc82tm/Screenshot%202016-02-03%2016.36.42.png?dl=1)

**Comment by sampritipanda** [comment]
Modifying the icon class from `icon-chevron-up` to `fa fa-chevron-up` seems to fix it on my browser. This can be modified in the `bootstrap-timepicker.js`

**Comment by diraulo** [comment]
That's right @sampritipanda. Font awesome changed their naming convention a while ago. So everywhere we have `icon-*` we should replace with `fa fa-*`
