### ISSUE TITLE
User preference for 'Hire Me' button can be bypassed

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#757]
imported from https://www.pivotaltracker.com/story/show/79861342

As an AG user
In order to not receive messages through the Hire Me button
I would like to have my preference setting respected

Somewhat related to the 'hire me' spam bug #76244298

Currently the controller will receive the hire me form params and send and email even if the user has chosen not to place a hire me button on their profile page.

The users controller needs to be updated to guard against this: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/controllers/users_controller.rb#L16

**Comment by sampritipanda** [comment]
Fixed by #571
