### ISSUE TITLE
Adding hangout recordings to the site is a bit flaky

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#760]
Copied from https://www.pivotaltracker.com/projects/982890/stories/112965677

The Refugee Tech project initiation meeting does not appear on the project page:
http://www.agileventures.org/projects/refugee_tech#video
I understand from @tansaku that this feature can be a bit flaky anyway so perhaps there is an intermittent bug lurking there....

The second meeting today again does not appear, so unless it is operator error, there is something dodgy in general or maybe specifically with this project?

**Comment by tansaku** [comment]
is this related to #796

**Comment by freeranger** [comment]
Yes. I thought I'd linked them when I saw @thomaso had added his.
If you still think it's a bit flaky anyway then I guess keep this open, otherwise just bin it off as is partly "operator error" and partly the problem solved by the other issue

**Comment by mtc2013** [comment]
@thomaso says this is fixed... Close perhaps?

**Comment by tansaku** [comment]
now we have events associated with projects, this shouldn't be an issue in future, but feel free to re-open if it occurs again
