### ISSUE TITLE
Multiple source repository

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#761]
As a user
When my project has more then 1 repository
I would like the ability to define them in the project page

Copied from https://www.pivotaltracker.com/projects/982890/stories/108643006

**Comment by tansaku** [comment]
will require new repo model in db - will affect statistics, but for simplicity let's have stats default to first or main repo and open separate ticket for updating stats

**Comment by tansaku** [comment]
here was the vote:

```
@federico Simple,
@tansaku Medium,
@praveendhawan Simple
```
