### ISSUE TITLE
[EPIC] Project list sort order

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#763]
As a user
When I am on the Projects page
I would like to see the projects in an order that makes sense.

Currently they seem to be in a random order - is it most active? Longest running?  
At the moment it just seems random - I would like the order to be obvious (if most active then show me some activity indicator so it is obvious) or indeed let me sort them however I want

**Comment by freeranger** [comment]
I understand now that this is, in theory, ordered by github commits.
An ordering like that is not useful IMO for several reasons:
- It does not help the visibility of new projects trying to attract members - unless the PM has access to hack the database and put in an artificial count, their project will be at the bottom of the list, and thus effectively invisible, for a long time.
- It does not reflect "active" projects - a mature project with a great many commits could stay at the top for a very long time even though nobody is working on it anymore...so what purpose does it serve being at or near the top?.  

Picking a project at random in the top 10, the "Look up" project appears at #7 at the moment, but has had no commits in at least a year.  Having said that, it has had more commits than "Project Unify", yet Unify is above it in the list due to artificial inflation...one would assume because the current commit based ordering is not useful enough to attract new members.

As a pure _directory_ of projects then A-Z probably makes the most sense, with a separate side bar showing the top _n_ projects by *recent* activity - so the #of github commits this week (or month).
Maybe new projects even get a special boost and a "New" tag for a period of time (a couple of weeks?) to improve their visibility and chances of attracting new members

**Comment by tansaku** [comment]
thinking to try to adjust to most recently active projects in first instance

**Comment by weedySeaDragon** [comment]
I just discovered AgileVentures today and was trying to browse through projects. I immediately thought 'there is a lot of possibility for improvement'!  Not exactly sure if this is the right or best place for me to post this.  I'll throw it out here and wait for feedback.

Here's my experience:

## New User Wants to Find a Project to Work On

As someone new to AgileVentures

I want to browse through/explore Projects to find ones I'm interested in

And so I want to filter and sort based on things like:

- recent activity (how active/stale is the project)?
- domain (what is the topic/focus of the project?)
- technologies used (do I have the skills to contribute or are they using skills I want to learn?)

**Comment by tansaku** [comment]
This is a great place for the suggestion @weedyseadragon and we'd love to make those sorts of changes.

Are you familiar with the Ruby on Rails stack?

**Comment by weedySeaDragon** [comment]
Yup, I am.  Happy to help out.  I just finished cloning the project to my desktop and also saw #797.  Seems like these are ideas to work on as well as finishing up #797. I see #1089 EPIC that lists both of these tasks & others.  Is there anyplace where they're prioritized?  Discussions about what to address first?

**Comment by tansaku** [comment]
@weedySeaDragon are you in our slack instance? we have a #websiteone channel where we discuss things, and scrums in google hangouts as well - you should get an invite to our slack instance if you create an account at http://agileventures.org

**Comment by weedySeaDragon** [comment]
Some misc. thoughts to add to this:

Is it that we need to **expose the project attributes (data)** so that they can be shown to the user and used in the UI (for sorting, filtering, etc)?  Some project attributes are available from github (languages used, commits & other coding status), some attributes are available from the agile project management (PM) tool.  

_Is it true that all projects will use github_? Is it OK to start with that assumption and adjust later?

_Is the following true:_  Since some projects might use Pivotal and some might use a different agile PM tool, use an Adapter between the project & the agile PM tool to keep a clear separation between them.  (more of a service/layered design)

**Comment by tansaku** [comment]
all projects use github ATM, would be nice to support other platforms, but I don't think we have the resources to support that unless we get some demand.

an adapter for management tools is a good idea, but it's not clear how much tracker integration is a motivation for people to work with projects.

I think exposing the project attributes better is probably the best way to go - grabbing the language elements from the github api or similar ...

**Comment by tansaku** [comment]
@mattlindsey has broken on #1430 as an aspect of this epic

**Comment by mattlindsey** [comment]
Closing this since Project list has been simplified and hopefully is good now. :)
