### ISSUE TITLE
Post story point votes into slack

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#766]
As a user
when I vote on a story
the story link and vote should be automatically posted to slack

This could be per person voting or perhaps once all votes are in and the points assigned to the story then a summary is posted to slack?
The voting would take place inside the PM tool (in chat?) or perhaps some external tool used by all projects (planningpoker?  similar functionality added to WSO?) if there is no way to support the "popular" PM tools like Pivotal, waffle, JIRA....

**Comment by tansaku** [comment]
this would be nice - particularly an async version

maybe migrate this idea to AV issues?

**Comment by freeranger** [comment]
Depends - if you were going with the "add planning poker-like functionality to WSO" then it isa WSO one issue rather than an AV one :)

**Comment by tansaku** [comment]
feels like this should be in a microservice rather than adding explicitly to our WSO monolith - btw great podcast on microservices: https://devchat.tv/ruby-rogues/242-rr-migrating-a-monolith-to-microservices-via-an-evolutionary-path-with-mike-gehard

**Comment by tansaku** [comment]
I think we're doing this with the AsyncVoter project now
