### ISSUE TITLE
links in the event descriptions are not hyperlinked

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#769]
e.g.  http://www.agileventures.org/events/local-support-retrospective

![absence of hyperlink](https://www.dropbox.com/s/u1htpwi12r61qw3/Screenshot%202016-02-05%2017.16.40.png?dl=1)

**Comment by tochman** [comment]
We can write our own method to extract URL's from a string or use a gem. `rails_autolink` used to be part of Rails but is now  a separate gem: https://github.com/tenderlove/rails_autolink
