### ISSUE TITLE
get mention of which slack chat room to go to on every project page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#770]
Seems like people don't generally know how to get to the right chat rooms for a project

**Comment by freeranger** [comment]
That is very true!
It would be good if the "connected on" box on every project page had links to, where applicable:
- the repo(s)
- the PM tool
- the CI build(s) (showing the red/green status next to the link)
- the slack channel(s)
- the deployed prod site
- other deployed instances - Dev/uat

**Comment by tansaku** [comment]
would be awesome if there was a live feed of slack chat on each project page ...

**Comment by tansaku** [comment]
would be great to have the slack api give a list of project channels to connect project to chat room: 

![](https://www.dropbox.com/s/n2yuef4wa8u3f3f/Screenshot%202016-09-02%2017.54.03.png?dl=1)

**Comment by diraulo** [comment]
There's a method to get list of channel from the slack API https://api.slack.com/methods/channels.list

**Comment by mattlindsey** [comment]
I think I'll work on this ticket.

**Comment by mattlindsey** [comment]
@tansaku:  @mtc2013  and I discussed 2 ways of approaching this:  1) Fetch list of rooms every time project page is visited 2) Fetch list of rooms once a day in rake job and load a table.

Which method sounds best? Or is there another way?  We don't have memcached or redis running, do we?

**Comment by tansaku** [comment]
@mattlindsey the rake task sounds like a good way to go if performance is bad ... however simplicity suggests we shouldn't prematurely optimize - we only hit the API on the project edit page right? and then we could make that an ajax task triggered on opening the dropdown to select the slack chat room ... even that's a premature optimization - I think hitting it from the project edit page is reasonable.

We don't have memcached or redis set up for WSO (we do for others) and that feels like another moving part to avoid - although I could be wrong there - perhaps I'm too database-centric

However we're probably on good lines if we go for simplest first and then see about performance optimizations later ...

**Comment by tansaku** [comment]
@mattlindsey should we throw this back into "ready"?
