### ISSUE TITLE
tests failing locally for me on OSX Yosemite

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#777]
```
(::) failed steps (::)

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:27:in `Then I should see hangout button'

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:103:in `Then I should see hangout button'

Failing Scenarios:
cucumber features/hangout.feature:25 # Scenario: Create a hangout for a scrum event
cucumber features/hangout.feature:100 # Scenario: Display hangout button on a project's page
```

**Comment by tochman** [comment]
Yes, these scenarios fail locally but works on Semaphore. I tried unsuccessfully to debug this problem.

**Comment by tansaku** [comment]
looking at the step definition:

```ruby
Then /^I should see hangout button$/ do
  src = page.find(:css, '#liveHOA-placeholder iframe')['src']
  expect(src).to match /talkgadget.google.com/
end
```

this reminds me of some timing issues we've had in LocalSupport.  There's a new thing in Capybara that `expect(page).to have_css` will wait for javascript operations to complete.

```
Then /^I should see hangout button$/ do
  expect(page).to have_css('#liveHOA-placeholder iframe')
  src = page.find(:css, '#liveHOA-placeholder iframe')['src']
  expect(src).to match /talkgadget.google.com/
end
```

I did try that but it didn't fix it.  I wonder if the issue here is that there is a google api hit here that isn't working in the context of capybara-webkit ...

**Comment by tansaku** [comment]
interesting - the test passes in selenium ...

**Comment by tansaku** [comment]
travis supports selenium testing: https://docs.travis-ci.com/user/gui-and-headless-browsers/ as does semaphore apparently: https://semaphoreci.com/docs/supported-stack.html

**Comment by tansaku** [comment]
but switching everything to selenium would be a pain ...
