### ISSUE TITLE
Users confused by "email registration temporarily disabled"

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#778]
got this from a user:

> I used github to sign up but am getting a message indicating that 'email 
> registration is temporarily disabled'.

there have been a couple of others confused by this message I think ...

**Comment by tansaku** [comment]
more from the user:

> I had to clear my cache and relog in using google+ which I would rather not have.
Every time I tried getting in with github it kicked me back to that 'email is temporarily disabled' message and my github icon was not there.
It only appeared after I registered or relogged in using google+

**Comment by tansaku** [comment]
and some more:

> As a result my username is smilovidov which is connected to my email.
I would much rather have it been Smilofactor which is my github name.

> I just removed the google+ authentication and added the github authentication after logging in
and it still is using smilovidov

**Comment by tansaku** [comment]
we should review this carefully ...

**Comment by tansaku** [comment]
@tochman says:

> The issue @smilofactor is having with GH sign-up CAN be related to him not having an public email on GH. In that case Devise is not able to save the User and he gets redirected back to the signup page. It’s a kind of bug because the user is not notified about the reason. But we will not be able to actually register him without a public email address.

**Comment by tansaku** [comment]
Email from another user that I think is related:

> This is what is displayed when I try to sign up -- how do I sign up? Thank you.

> > Sign up
> > Already a member? Sign in
> > Forgot your password?

> > Email Registrations are temporarily disabled.

> > By registering, you understand that we will store and make use the information provided in accordance with our Privacy statement.

**Comment by MassivebutterpapperCodes** [comment]
yea it says "Email registration is temporarily disabled." on www.mantle.gg
