### ISSUE TITLE
Publish meetings as podcasts

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#779]
Is it possible to automate doing this?
The workflow would be:
- Livestream ends and is automatically posted to youtube (which happens now)
- The audio is extracted and published as an audio only podcast into iTunes (possibly others?)
- This video is published as a video podcast into iTunes (possibly others?), though this is perhaps less important since there are already ways to download youtube videos to your device

**Comment by tansaku** [comment]
might be great - does YT not support automatically?

**Comment by tansaku** [comment]
I listen to a lot of podcasts recenlty - would be nice to connect to that world

**Comment by freeranger** [comment]
There are ways to subscribe to the youtube rss feed but that's not quite the same thing.
I'm thinking I want my favourite podcasting app on my mobile device to subscribe and download for offline listening (or even streaming) audio only.

Googling around there are things you the consumer can do to convert video to audio but that's a hassle too and not automatic.  

Today I found this - I have no idea if it will be chargeable but this is exactly the sort of service that would be ideal: http://vaud.io - might be worth contacting them to see what the deal is?

**Comment by tansaku** [comment]
thanks @freeranger - I signed up to be on their invite list - will see if they get back to us.

I can see that podcasts of the scrums would make some sense - would be great to be able to consume them on the iphone/android podcast apps

**Comment by tansaku** [comment]
I wonder if this is something we could manage ourselves; http://lifehacker.com/how-to-turn-youtube-channels-into-subscribable-podcasts-496976976

**Comment by freeranger** [comment]
That would be turning the youtube channel into a video podcast - which was the third point I mentioned.  
The main goal was to turn them into audio podcasts that you can stream (or download) whilst on the move, without eating up your entire data plan.
vaud.io turns your videos into audio - I haven't seen anything else out there that does this, apart from via lot of manual effort, which nobody wants to have to do...

Listening to standups or even pair sessions is surprisingly effective even though you can't see the code - it doesn't seem to matter in the main as you are getting the communication between the pair discussing the issue - the video just lets you see them typing in the answer ;)

**Comment by tansaku** [comment]
I'm chatting with vaud - we'll see if they'll do something for us for free

**Comment by tansaku** [comment]
maybe https://www.reddit.com/r/youtube/comments/3e6lxg/turn_youtube_channels_and_play_lists_into/ --> http://podsync.net/ --> gives me http://podsync.net/2adi <-- @freeranger can you use this?

**Comment by freeranger** [comment]
@tansaku it's certainly a good idea in theory - and it *nearly* works in that I can now subscribe to the "podcast" on my iPhone...but I keep getting told the episodes are temporarily unavailable, try again - which I have done a number of times over the past 12 hours and from an iPad too.
Could be a setup thing?  or a temporary glitch?  Or perhaps this service is unreliable - some of the comments on the reddit link seem to suggest it is a bit up/down....

**Comment by tansaku** [comment]
yeah @freeranger it's a shame - would be nice if there was just a reliable hookup - I have half a mind to start creating a podcast about technology and process for non-profits - if I get more into the podcasting space I might be able to work out a better solution ...

nothing back from vaud since I mentioned we are a charity :-(

**Comment by mattlindsey** [comment]
Closing old issues...
