### ISSUE TITLE
Provide audio only stream of meetings

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#780]
Two aspects to this:
1. While the video is livestreaming
2. After it is finished and published to youtube - is there a way to provide an audio only stream?
 (note this is distinct from the other issue which was about publishing as a podcast)

Another option might just be to identify existing apps that people could use to live stream audio only or stream the audio only after it has been published

**Comment by tansaku** [comment]
related to #779

**Comment by mattlindsey** [comment]
Closing old issues...
