### ISSUE TITLE
Allow users to create events in their local timezone

### ISSUE THREAD

**Issue by dalupus** [AgileVentures/WebsiteOne#782]
As a user 
So that I don’t need to convert my time into UTC
I’d like to enter the event time in my local-time.

**Comment by tansaku** [comment]
may fix #755

**Comment by dalupus** [comment]
javascript to autoselect users local timezone
https://gist.github.com/thisisbrians/4699851

**Comment by dalupus** [comment]
I have started coding this up and now have a timezone selector and something that selects something "close" to the users timezone.  

I am starting to run into issues thinking about daylight savings time.  For instance what if they are not DST now but would be DST on the date in which they want to create the event?  We would need to call back to the server via ajax to generate the new set of offsets.

I can't believe there isn't a solution already for this out there.

**Comment by dalupus** [comment]
I'm not sure we really want to devote all of the time and effort to handle all of these corner cases.  Right now it just grab the GMT offset out of the browser and selects the correct entry in the pulldown list, which is going to be the correct thing to do 99.99% of the time.

**Comment by tansaku** [comment]
that sounds like the right choice @dalupus - please do push up WIP code and screen shots when you have a chance - it's a shortcoming of mine, but I find it difficult to give good feedback unless I'm looking at actual code and interfaces :-)

**Comment by dalupus** [comment]
http://stackoverflow.com/questions/16818180/ruby-rails-how-do-i-change-the-timezone-of-a-time-without-changing-the-time

**Comment by dalupus** [comment]
![screenshot_041316_124311_pm](https://cloud.githubusercontent.com/assets/806458/14501613/4bc95028-0175-11e6-890a-2ee2bfb2ca60.jpg)

**Comment by dalupus** [comment]
It looks like the support for timezones in the UI isn't great around DST and stuff.  So we are thinking to just use a smaller list of this sort and put UTC at the top.  The user can then either enter in UTC or select their own timezone.

Using this method we would not be able to auto magically select the timezone, which might be ok.

**Comment by tansaku** [comment]
just thinking about tests for this:

* check that after validation failures that users selection is maintained ...
* check that correct time is displayed subsequently ...

**Comment by tansaku** [comment]
label needs to be changed too ...

**Comment by tansaku** [comment]
this seems to be where some of the javascript was coming from: https://gist.github.com/thisisbrians/4699851

**Comment by mtc2013** [comment]
https://bitbucket.org/pellepim/jstimezonedetect/
http://stackoverflow.com/questions/6939685/get-client-time-zone-from-browser

**Comment by tansaku** [comment]
* cucumber tests
  * [ ] test that events can be edited and maintain the correct time
  * [ ] test that create event works for daylight savings
* javascript tests
  * [ ] checking jstz interaction works
  * [ ] tests default to UTC when no browser timezone selected

can we have an acceptance that has the implicit selection of timezone?
