### ISSUE TITLE
The Ruby Mine image is out of date

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#787]
In the "Supporters" panel, it is an old RM7 logo, but Jetbrains have rebranded and are on v8 now.
New logo can be downloaded here: https://www.jetbrains.com/company/press/

**Comment by tochman** [comment]
While working on this. Perhaps we could add Craft Academy ad to the supporters panel. Thoughts on that @tansaku ?

**Comment by tansaku** [comment]
totally! I think it's time to drop the makers academy one too

**Comment by tansaku** [comment]
should be a separate pull request though I think

**Comment by freeranger** [comment]
Are you guys trying to creep the scope of my story? Tsk tsk

**Comment by tochman** [comment]
Okay, cool. Also, @freeranger We need to discuss the size of the images. The other ones have  a width of `200 px` give or take. Can you make sure that the new RM image follows that standard?

**Comment by freeranger** [comment]
@tochman See my comment on the PR - this is not allowed by jetbrains.
re: +Craft Academy and -Makers Academy - if you want to create an issue and supply a suitable image then I will do these in a separate PR
