### ISSUE TITLE
Make Learn/Code/Pair/Grow content easier to find

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#788]
The site has some obvious menus - the main menu on every page, and the Projects menu for example.
But not all pages can be navigated to (or not obviously so) from these menus.
I was completely unaware of all the good content here for example:
http://www.agileventures.org/pair

Why?  Because it is "hidden" in the animated "PAIR" image on the front screen. 
When I go to the front page, I see four giant circles - it is not obvious that these do anything.
I hover over one and it does a nice animation and changes the words.  Since I'm only skimming the site, I don't necessarily notice the "Read more" button (which I appreciate is relatively big) because I am not expecting a link inside this image.

So two suggestions:
- make the entire image a link so I get a pointer cursor when I hover so it is obvious that this is a link
- Make the content available via a menu option - it should be easy (and possible) to get to any of the main sections of the site from anywhere - you have a whacking great menu bar at the top of every page, so make use of it!

**Comment by tochman** [comment]
Good feedback @freeranger I was hoping the "Read more..." buttons would provide some guidance. There is a ticket to redo the landing page and the round buttons will probably go.

**Comment by tochman** [comment]
+1 on the menu idea.

**Comment by freeranger** [comment]
Thanks.  I like the round buttons!  But the read more just feels a bit hidden away...

**Comment by tansaku** [comment]
maybe this should be part of a complete re-design

**Comment by mattlindsey** [comment]
Closing old issues...
