### ISSUE TITLE
Phantomjs version error when executing cucumber tests 

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#792]
Trying to run the cucumber tests locally, I get:
`
    Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'. Found versions were {"/usr/local/bin/phantomjs"=>"2.1.1"}. (Cliver::Dependency::VersionMismatch)
      /Users/tony/.rvm/gems/ruby-2.2.2/gems/cliver-0.3.2/lib/cliver/dependency.rb:151:in `raise_version_mismatch!'

Does it have to be a 1.8.x version or can I upgrade to 2.1.1?

**Comment by tansaku** [comment]
now fixed phantomjs 2.1.1
