### ISSUE TITLE
Ability to connect scheduled events to a project

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#796]
```
As an event planner,
In order to connect my event's hangout recording to my project,
I would like to set a project connection in the Event setup interface.
```
Right now, when an event is scheduled and started from the Event#show page, no `project_id` is being assigned to the `EventInstance` instance, thus it is not being shown on the `Videos` tab for the project. I would like that to happen. One idea is that we can allow who ever is planning an event to connect it to a project on the Event#create or #edit

**Comment by tansaku** [comment]
this is interesting as I think we need similar functionality for the edx SaaS pair programming videos to make them all go to gitter, as the current regex is a bit hit and miss

**Comment by tansaku** [comment]
perhaps we could add a project selector to this page: http://www.agileventures.org/events/new ?

**Comment by tochman** [comment]
I agree @tansaku

**Comment by tochman** [comment]
Any updates on this? Has the story been assessed yet?

**Comment by tansaku** [comment]
we've been reviewing it and it is at the top of the ready list indicating its priority

**Comment by tochman** [comment]
I think that a field 'Assign to Project' is the simplest way to go.
