### ISSUE TITLE
Projects index page redesign

### ISSUE THREAD

**Issue by tochman** [AgileVentures/WebsiteOne#797]
Imported from https://www.pivotaltracker.com/story/show/79660056

**Story**
As an agile ventures user
So that I can (find a new | create a new | find my | promote my) project(s)
I would like to see a fully featured projects index view

**Supporting documents**
Feature request on AG: http://agileventures.org/projects/websiteone/documents/project-index-page-ux-proposal
Direct link to wireframes: https://drive.google.com/file/d/0B9FqKjpP8_MUQXBlcWZ2R3JzV2c/edit?usp=sharing

**Tasks:**
- No tab for current users projects
- No search
- No featured project

**Comment by tochman** [comment]
I'd love to take on this feature. It has been voted on as a 3 point story.

**Comment by tochman** [comment]
Spiked UI
![skarmavbild 2016-02-17 kl 09 40 15](https://cloud.githubusercontent.com/assets/5248170/13103964/85d7207a-d55a-11e5-842a-b2f7a1a24211.png)

**Comment by tansaku** [comment]
nice start @tochman

**Comment by tochman** [comment]
Link to my feature branch: https://github.com/tochman/WebsiteOne/tree/projects

**Comment by tansaku** [comment]
thanks @tochman so that was something that was being worked on previously?

**Comment by tochman** [comment]
Just the wireframes. Nobody started this feature. It's been around for a while.

**Comment by tansaku** [comment]
@tochman looks like that was it - want to open a work in progress pull request so it's easy for us to find?

I'd love to get you working from branches on the main repo if I could (so we can collaborate on this), but I realise that may be a step too far outside of your existing comfort zone :-)

**Comment by tochman** [comment]
I would like to back out of this so if anybody else is interested in what I've come up with this is my feature branch: https://github.com/tochman/WebsiteOne/tree/projects

**Comment by tansaku** [comment]
thanks @tochman :-)

**Comment by aleciavogel** [comment]
Hi there! I'd be down to take this on. Do I need to submit a poll for this on the Slack channel before I can begin? 

One other question... am I allowed to install a gem like [haml](https://github.com/haml/haml) for building views? It's a personal preference (and quicker in my experience), but I couldn't find anything about it when I searched the repo.

**Comment by tansaku** [comment]
hi @aleciavogel - great to hear from you - this is a rather old ticket that we've since broken down into different epics - might be good to discuss on the slack channel which is the right ticket to get a vote on

we've always used erb in the past.  I tend to prefer it, but happy to switch to it if it can help us make progress.

we have a weekly team meeting tomorrow at 4:30pm UTC? any chance you could make it?  either way would be great to talk in slack :-)

**Comment by nisevi** [comment]
@tansaku I know this is an old ticket but the way projects are being displayed is pretty cool!! any thoughts about working on it? talking about priorities :+1:

**Comment by tansaku** [comment]
@nisevi yes, would love to improve the projects page :-)  there's need for a round of clearing out old/defunct projects and also working out a design that will allow folks to find projects - what we hear requested alot is being able to search projects by tech stack

**Comment by tansaku** [comment]
@mattwr18 looking forward to the conflicts being fixed on the three column layout
