### ISSUE TITLE
have devs uninstall global phantomjs to ensure everyone is on same version

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#798]
We can use the phantomjs gem to ensure we are all using the same version of phantomjs.

Perhaps we can flag that in our engineering docs

**Comment by freeranger** [comment]
Is it necessary to uninstall a global phantomjs in order to use the gem for WSO?
I'm thinking if you need it for other reasons (other projects are available!) then you won't really want to have to uninstall it for WSO, reinstall for Project Foo, uninstall for WSO again etc..

**Comment by tansaku** [comment]
the idea is that each project should be locked to a particular version which I think doesn't happen if you have a global install.

In reality I don't think it's going to be practical to recommend this.  I got caught out when Thomas removed a setting in features/support/env.rb but the chances of it happening again are small and it's almost certainly not worth inflicting pain on other devs since I'll know how to fix it if it happens again (which is unlikely in itself)

**Comment by freeranger** [comment]
@tansaku it may be that you can have a local install that overrides the global one - needs experimenting methinks.
So perhaps this issue should be something like "endure WSO is locked to a particular version of phantomjs" which seems to be your actual goal here.

**Comment by tansaku** [comment]
right - that's what the new gem does

**Comment by freeranger** [comment]
ahh...got you now.  I thought you were advocating the global uninstall.

**Comment by tansaku** [comment]
well I was, since that ensures that people can't break my setup by deleting certain components from the features/support/env.rb, but it's such a corner case it's not worth it I think.
