### ISSUE TITLE
Ensure consistency on how we present all sponsor links on mobile and tablets

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#803]
We'd like to hide all sponsor links on mobiles and tablets because ...?

**Comment by tochman** [comment]
This is an old story. https://www.pivotaltracker.com/story/show/78407262 We missed some unfortunately.

**Comment by tansaku** [comment]
Aha, thanks @tochman - that's good to know.  As it turns out I can't easily cherry pick the commit for this :-(  That's because db42ad1 contains a variety of things including the sponsor link hiding, i.e. fixed formatting on events/form and display of event actions pulldown on events/show.

I'll take another pass around on this ...

**Comment by tochman** [comment]
Is this still relevant?

**Comment by tansaku** [comment]
not sure - I guess if there are some outstanding ones we have missed - need to take a pass over the site on mobile

**Comment by tochman** [comment]
To get the screenshots using cucumber:

Add this step def:
```ruby
Then(/^open screenshot$/) do
  save_and_open_screenshot
end
```
In WSO you have several hooks to your disposal: `@desktop`, `@tablet`, `@smartphone`
To generate a screenshot from a smartphone, create a new feature file and add a scenario:
```gherkin
@poltergeist @smartphone
Scenario: Generate phone screenshot
  Given I am on a tablet
  And I am on Events index page
  Then open screenshot
``` 
The `@smartphone` hook is set to landscape mode. 

And so on for whatever screenshots you want to generate.
Make sure to exclude the file from version control.

This is the output of the scenario above:

![capybara-201602261014278096372468](https://cloud.githubusercontent.com/assets/5248170/13349466/5309511e-dc7a-11e5-8e2e-bcafbc59f90c.png)

**Comment by tansaku** [comment]
cool thanks @tochman
