### ISSUE TITLE
investigate smoothing the onboarding process

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#807]
improve documentation?  VM image?  C9 template?

**Comment by tansaku** [comment]
@diraulo found https://github.com/thoughtbot/laptop really helpful

**Comment by tansaku** [comment]
Linux/Mac doesn't need VM, but windows do need a VM of some sort

**Comment by diraulo** [comment]
Linux version of the thoughtbot laptop script here https://github.com/diraulo/laptop-script . Last I used it, I was able to setup an ubuntu 14.04 box with it.

**Comment by tansaku** [comment]
@dalupus I was just looking at https://c9.io/community/templates which talks about forking this repo to make a template: https://github.com/c9/templates

**Comment by tansaku** [comment]
I thought I would just try a website install on c9 using a custom template and a direct clone of the WebSiteOne repo:

First issue - need to do `rvm install ruby-2.2.2`

....

**Comment by tansaku** [comment]
@dalupus check out this: https://github.com/AgileVentures/LocalSupport/wiki/C9-install-notes

**Comment by tansaku** [comment]
hmm, might this be solution to db access: https://github.com/Aerogami/guides/wiki/Cloud9-workspace-setup-with-Rails-and-Postgresql

**Comment by tansaku** [comment]
addressed by the new c9 install docs

**Comment by diraulo** [comment]
Closing this for now.
