### ISSUE TITLE
change all references to "scrum" with "standup"

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#809]
I'm definitely grooving to the term standup much more than scrum recently - is everyone happy with standardizing on that?

**Comment by freeranger** [comment]
On the one hand this is "agile" ventures so you might expect people to know what a "scrum" is, but on the other hand if you are unfamiliar with agile practices then "scrum" will be quite alien to you outside of rugby but you could probably reasonably guess what "standup" means.  
In short, yes ;)

**Comment by freeranger** [comment]
Also, do you mean where it is visible on-screen only or do you mean everywhere in the codebase?
e.g. should
`before_filter :get_next_scrum, :store_location, unless: -> { request.xhr? }`
become
`before_filter :get_next_standup, :store_location, unless: -> { request.xhr? }`

**Comment by tansaku** [comment]
personally I'd like to switch the whole codebase over, but we'll have to see if that's practical

**Comment by freeranger** [comment]
@tansaku Could be tricky alright - may be database migrations?  Also are there tags on the youtube videos or something that might be affected?
Is it worth splitting this into two issues - one to change the displayed text, the other to change the nomenclature used in the code base?  They don't have to be done as a single item

**Comment by tansaku** [comment]
I'm a terribly inconsistent person and I'm thinking that maybe we should standardise on 'scrum' ...
