### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#811]
The current README.md file has not been updated in light of recent changes to the project.

- [ ] Point to waffle board and remove PT
- [ ] Fix Broken SemaphoreCI build status images
- [ ] Update Contributing section

**Comment by tansaku** [comment]
apologies @diraulo - I didn't mean to unassign you from this if you were planning to take the lead on it.  That's a waffle/github shortcoming that there's only one person assigned as lead :-(  I maybe prefer Pivotal Tracker in that regard ...

Anyhow, I was just really keen to not just leave my chatter in https://github.com/AgileVentures/WebsiteOne/pull/804#issuecomment-185675146 and show that I'm really committed to updating the README, and to following a particular kind of process, so my sincere apologies if I come across as heavy handed here.

**Comment by tansaku** [comment]
see also #805 ...
