### ISSUE TITLE
Fix vertical alignment of content on Event index page

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#816]
See image below

<img width="860" alt="screenshot 2016-02-18 18 36 14" src="https://cloud.githubusercontent.com/assets/4028374/13150599/1de028d4-d66f-11e5-9d62-d68c4001cf38.png">

**Comment by stefanh13** [comment]
Was thinking of doing my first PR. 
Does this still need to be fixed?
Is this on http://www.agileventures.org/events?
@diraulo

**Comment by diraulo** [comment]
Hey, @stefanh13 thanks for your interest in working on this. Unfortunately, this page has evolved since I posted this issue. It's no longer needed. I'll close this for now

We have our first meeting today after a long break and we'll go over these stories/issues and sort them out. Keep an eye on the #websiteone channel on slack for any updates on this project (I'm assuming you've joined our slack instance if not sign up on agileventures.org and you should receive an invitation to join) 😉
