### ISSUE TITLE
github count commit weirdness

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#819]
Project Unify is ahead of Autograders in the project listings which seems odd when it's based on #commits and project unify has 10 vs autograders 606 - something fishy there ...

**Comment by tochman** [comment]
I manually put my own project in the first 5 spot by overriding the commit count.

**Comment by tansaku** [comment]
did you mean to put a smiley on that @tochman ? :-)

**Comment by tochman** [comment]
"It's not a bug, it's a feature!" :-)

**Comment by tansaku** [comment]
:-)

**Comment by tansaku** [comment]
interesting - so thomas made a one off change to the database, but it didn't get overwritten by subsequent runs of the github commit count task - wonder if that isn't running or perhaps not running how we expect ...

**Comment by diraulo** [comment]
Everytime I check that scheduler it says it ran the command, but it doesn't have some kind of log that shows output of previous run. 

One would expect to have the git_count updated for all projects at every run, but doesn't seem to be the case (If the command gets executed as scheduled). Unless Thomas has a bot that updates the commit count on the unify project after every run :smiling_imp:

**Comment by tansaku** [comment]
@diraulo the output from that process should in principle go to the log - it runs every day at 4:30pm UTC - might be an idea to trail the log at that point
