### ISSUE TITLE
Generate friendly project ids

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#828]
As a project owner
When I rename the project
I would like a new friendly Id to be created for the project
So that I can have consistent "branding" for the project.

Example: Project Unify was originally called Refugee Tech. 
The Project was renamed but the url is still http://www.agileventures.org/projects/refugee_tech

**Comment by tochman** [comment]
I would suggest using a friendly Id method to regenerate the slug on :title change (or is it :name on Project?)
This addition to the model should do it:

def should_generate_new_friendly_id?
    title_changed?
  end

**Comment by tochman** [comment]
FriendlyId's History module adds the ability to store a log of a model's slugs, so that when its friendly id changes, it's still possible to perform finds by the old id.
