### ISSUE TITLE
BUG?: Images added to documents don't respect supplied size

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#834]
I added a doc to Project Unify: http://www.agileventures.org/projects/refugee_tech/documents/presentation-at-gothenburg-university
and I specified a width of 100 for the images, but they are still displaying full size.
Tried this several times, added height too, added alignment, but it has no effect.

I would like images in a document to respect the size limitations supplied when the image is added

**Comment by tansaku** [comment]
hmm, works for me
