### ISSUE TITLE
Event show page "Not Yet live" too prominent?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#839]
![event show page](https://www.dropbox.com/s/o6o1n1voint9hqn/Screenshot%202016-02-25%2012.19.41.png?dl=1)

@dalupus was confused by where to start hangout since eyes drawn to "Not Yet Live" which seems clickable

**Comment by diraulo** [comment]
Perhaps revisit this after new event page redesign is merged in ;-)

**Comment by thejuliaguenther** [comment]
Maybe move to the bottom near the start a hangout on air button?

**Comment by tansaku** [comment]
this is the old interface - no longer used
