### ISSUE TITLE
Events index page should have a link to the related project

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#842]
As noted here: https://github.com/AgileVentures/WebsiteOne/pull/837#issuecomment-189154792

It would be good if upcoming events could show the project, if any, that they relate to - similar to the feature on the Past Events page.

@tansaku believes this will be possible once https://github.com/AgileVentures/WebsiteOne/issues/796 has been done

**Comment by mattlindsey** [comment]
Closing old issues...
