### ISSUE TITLE
Add brakeman and bundler:audit reports to the CI build

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#846]
Related to https://github.com/AgileVentures/WebsiteOne/issues/831 "Epic"

Once https://github.com/AgileVentures/WebsiteOne/issues/844 and https://github.com/AgileVentures/WebsiteOne/issues/845, the audit reports can be added to the CI build (and the default rake target) if desired.

If you do not wish to run bunder-audlt and brakeman as part of your default rake task then you can add them explicitly to run in the CI build by adding the following to a new or existing semaphore build thread:

```
if bundle show brakeman &> /dev/null ; then bundle exec rake brakeman:run ;fi
if bundle show bundler-audit &> /dev/null ; then bundle exec rake bundler:audit ; fi
```

If you want them to be part of the default rake task then you need to add these rake tasks:

```
task default: 'brakeman:run' #Add this if you want brakeman to run as part of your default rake task
task default: 'bundler:audit' # add this if you want bundler audit to run as part of your default 
```

Note: Recommend that this is completed _after_ https://github.com/AgileVentures/WebsiteOne/issues/844 and https://github.com/AgileVentures/WebsiteOne/issues/845 as otherwise the build will start to fail due to the issues they have identified.

**Comment by diraulo** [comment]
Codeclimate now runs both `brakeman` and `bundler-audit` as part of their code analysis... So I will close this issue.
