### ISSUE TITLE
Too much whitespace around menus and titles on mobile devices

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#849]
Example: 
![68747470733a2f2f7777772e64726f70626f782e636f6d2f732f3333366572706c306639697a7268332f53637265656e73686f74253230323031362d30322d323925323030392e30302e34392e706e673f646c3d31](https://cloud.githubusercontent.com/assets/1401069/13391123/791bb868-deca-11e5-83c4-b6d14272cca2.png)

Seems to be a lot of wasted space here:

big gap before the "burger" menu
then an even bigger gap down to the "AgileVentures Events" title.
The title itself might look better in a smaller font so it fits on one line.

Note: The issue is not limited to this page, this is just an example

**Comment by freeranger** [comment]
@tansaku - In terms of just the menus, currently this is what you get:
![image](https://cloud.githubusercontent.com/assets/1401069/13729965/35014598-e939-11e5-8f44-6a0ccb37c354.png)

If you want to keep the dark menu line then you get something like this:

![image](https://cloud.githubusercontent.com/assets/1401069/13730016/df619a28-e93a-11e5-8841-5fe0827a0991.png) 

Which stylistically is the same but it seems to be a waste of an entire line so we could go more like:

![image](https://cloud.githubusercontent.com/assets/1401069/13729963/2647cfd6-e939-11e5-856e-6b59ffb5dd14.png)

One further note is that the login/out buttons do not appear at all on the small screen.
These normally live in the orange strapline rather than the menu per-se.
On mobile devices should we a) make them visible and b) put them on the menu itself?

An iPad screen is neither mobile nor desktop at the moment:
![image](https://cloud.githubusercontent.com/assets/1401069/13730030/86170902-e93b-11e5-83cb-398ad76203fc.png)
so we have the menu, which is fine, but no login/out buttons either....

My own feeling is that the iPad could happily show the desktop menus and login/out, with the burger menu (including login) only showing for the smaller devices.

**Comment by tochman** [comment]
![](https://cloud.githubusercontent.com/assets/1401069/13729963/2647cfd6-e939-11e5-856e-6b59ffb5dd14.png)
I would say that this is the best option apart from the red color.

**Comment by diraulo** [comment]
@freeranger looks like we do have some space to display the login/out links too on iPad view.

**Comment by freeranger** [comment]
Ok I've updated the menu like this:
iPad:
![image](https://cloud.githubusercontent.com/assets/1401069/13794613/acf4f89e-eaf4-11e5-99b4-7098fe404f1b.png)

iPhone closed:
![image](https://cloud.githubusercontent.com/assets/1401069/13794641/dc54f26a-eaf4-11e5-9f37-cdbce21e309f.png)

iPhone open:
![image](https://cloud.githubusercontent.com/assets/1401069/13794633/ca0ccde4-eaf4-11e5-8e0d-dace350f9cd5.png)

**Comment by diraulo** [comment]
looking good @freeranger. Perhaps if you have time later today we could have a look at your issue with deploying to Heroku.

**Comment by freeranger** [comment]
Thanks @diraulo 
Unfortunately I can't pair during the day (UTC) so would only be able to do it in the evenings/weekends
I'll have another go faffing about later and see if anyone is around on slack at the time if I get stuck
