### ISSUE TITLE
UX improvement to do  

### ISSUE THREAD

**Issue by ORCARTS** [AgileVentures/WebsiteOne#857]
Quick testing of some UX stuff . Desktop Navigator
- Check W3C validation - it sounds that ID are duplicate in the events page
- All img element need to have alt attribute which describe the image
- Contraste check - there is a lot of wick foreground/background contrast - http://www.checkmycolours.com
- I would reduce the h2 eventTitle font size to be able to display the entire even title and avoid to click to read it (eg:Saas 169.1X Week 2: HW1/Sinatra instead of Saas 169.1X Week 2:….)
- Event Clickable zone. why only the date and title are clickable , would be better to have the entire box
- There is no sitemap
- I can not navigate using only keyboard. I have no focus visible

Test mobile - Not good on iPhone 4S - OK on iPad air
- Title H1 too big to fit the screen
- Event calendar too small to display properly title and description

**Comment by tansaku** [comment]
thanks so much @ORCARTS - I'll break these out into separate tickets that we can work on separately.

Note that we have pushed some changes to the event index and show page which you can see here: 

http://websiteone-develop.herokuapp.com/

We'll be very interested in any other UX issues you can identify

**Comment by freeranger** [comment]
https://github.com/AgileVentures/WebsiteOne/issues/849 already raised for the mobile issues, though I confess I haven't tested it beyond identifying that *something* needs to be done, so @ORCARTS your input is invaluable - if you'd like to list out some of the problems ther,e that would be great.

**Comment by freeranger** [comment]
https://github.com/AgileVentures/WebsiteOne/issues/803 is also related to mobile UI
I wonder do we need a mobile UI epic to pull them all together?
And possibly one for general UI issues?

**Comment by mattlindsey** [comment]
Closing old issues...
