### ISSUE TITLE
Link checking step not actually checking for links

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#866]
As noted in https://github.com/AgileVentures/WebsiteOne/pull/847, `features/step_definitions/basic_steps.rb:260` is not written correctly.  It does not actually check for a link.  The step definition needs rewriting so that it actually checks for the presence of the link:

```ruby
Then(/^I should( not be able to)? see a link to "([^"]*)" page for ([^"]*) "([^"]*)"$/) do |invisible, action, controller, title|
  page.has_link?(action, href: url_for_title(action: action, controller: controller, title: title))
  unless invisible
    page.should have_text title, visible: false
  end
end
```

I'm not sure about the visibility functionality ... sensibly we might move this to checking for the presence via css e.g. 

```ruby
expect(page). to have_css("a[href=#{link}]")
```

I don't recall if there's a good mechanism for checking the link href and link at the same time ... we should probably analyze carefully the place that this step definition is being used ...

**Comment by tansaku** [comment]
@jinksy @mtc2013 you were right - it looks like I fixed this a while back - apologies

**Comment by mtc2013** [comment]
@tansaku @jinsky i just confirmed that this is working as expect.  Failure is failing for irght reason when I break the app code:

(::) failed steps (::)

expected to find link "hello world" with href "/projects/hello-world" but there were no matches (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:239:in `/^I should( not be able to)? see a link to "([^"]*)" page for ([^"]*) "([^"]*)"$/'
./features/step_definitions/contained_search_steps.rb:41:in `block (2 levels) in <top (required)>'
./features/step_definitions/contained_search_steps.rb:41:in `/^(.*) within the (.*)$/'
features/sidebar.feature:36:in `Then I should see a link to "Show" page for project "hello world" within the sidebar'

Failing Scenarios:
cucumber features/sidebar.feature:33 # Scenario: Sidebar always shows the relevant information

**Comment by Arepo** [comment]
Is this already fixed? If you delete the contents of layouts/_sidebar, the spec explodes in a plausible-looking way.

**Comment by mtc2013** [comment]
@jinksy i think so
