### ISSUE TITLE
front page "click to join" appears before scrum master starts hangout

### ISSUE THREAD

**Issue by alejandrobabio** [AgileVentures/WebsiteOne#872]

**Comment by alejandrobabio** [comment]
Migrated from: https://www.pivotaltracker.com/story/show/91253176

As a user overcoming my huge fear of hangouts
When I join a hangout for the first time
I want to actually meet other people rather than being in a dead hangout from the previous day

**How should it be demonstrated?**
1. Before the scheduled time for the event: Show countdown time
2. After the scheduled time for the next event, if it's live or within 15 minutes:
 - If the event is live: show link "Click to join" with "is live!" legend
 - if the event is not yet live: show link to event with "not yet live ..." legend  + link to Slack channel with text: "see Slack for more info..."
3. After 15 minutes of scheduled time and if no live event,  the event is replaced with the next event, showing countdown time.

Current design is maintained, on root page and other routes.

**Comment by alejandrobabio** [comment]
Done (some previous required tasks):

**Improve HangoutConnection:**
 - Send broadcasting status on change of it
 - Send update message each 2 minutes
 - Use hangout app callbackUrl for update instead of fixed production url
  
**Improve WSO to update event_instance status.**
 - Make work on development / staging / production heroku environments, moving setting to config variables.
 - Receive broadcasting status from hangout, and update event_instance
 - Respond to ```:live?``` with true if status is not ```finished``` and it was updated within 2 minutes.

**Comment by alejandrobabio** [comment]
@tansaku : Some pending task (I'm not sure if these were done):

**Production**: if `ENV['HANGOUTS_APP_ID']= 227702023966` (the actual Yaro app), this must be updated.

First: go to https://code.google.com/apis/console/b/0/?noredirect and:
- select app "WSO HOA Connect - Production" (could be the name), at the blue box click the "enable an manage API", select the "Enabled APIs" tab, click the gauge of "Google+ Hangouts API". then:
- at "Application URL" set value `https://raw.githubusercontent.com/AgileVentures/HangoutConnection/master/public/websiteone.xml`
- at "Application type" set "An Extention".
- set support urls and "Save".
- Then, on the left panel select "Credentials", and there select the "OAuth consent screen" tab. If not completed yet, I guess mail: "agileventures2014@gmail.com", set name, and logo with `https://raw.githubusercontent.com/AgileVentures/WSO-HOAConnect/develop/public/wso-32x32.png`, and save it.

Second: Set these variables:
```
ENV['HANGOUTS_APP_ID']= 135304697558
ENV['SLACK_NOTIFICATIONS_ENABLED']= true
ENV['TWITTER_NOTIFICATIONS_ENABLED'] = true
```
And all should work, if not just rollback `HANGOUTS_APP_ID`.

**Comment by tansaku** [comment]
@alejandrobabio thanks for following on this - will try to get to this ASAP - @diraulo we should review this in kick off today ...

**Comment by tansaku** [comment]
we're looking at this @alejandrobabio - struggling to find the login details for agileventures2014@gmail.com at the moment :-(

**Comment by diraulo** [comment]
@tansaku perhaps @tochman has those credentials?

**Comment by tochman** [comment]
Taken care of :-)

**Comment by diraulo** [comment]
Thanks @tochman. I assume when you say "Taken care of" you mean the settings in the google console?

**Comment by tansaku** [comment]
@diraulo I don't think so - @tochman got me the password for the user - now I need to do the update

**Comment by diraulo** [comment]
Okay, @tansaku. I will let you sort the env variables once you're then done :wink:

**Comment by tansaku** [comment]
@diraulo done - let's see what happens

**Comment by tansaku** [comment]
so it looks to me like last night the MetPlus folks hangout did not ping slack, and I just experimentally opened a EuroAsiaAfrica standup:

![no WSO connection](https://www.dropbox.com/s/mpmojr91aqudaq5/Screenshot%202016-03-11%2009.00.58.png?dl=1)

reloaded and no joy - I would say that this attempt to switch has failed ... :-(

is there some way to check which is our app?

135304697558 (ours?) vs 331105831845 (staging is on this)  227702023966 (yaro?)

**Comment by tansaku** [comment]
135304697558 is definitely the id of the hangout app I was updating ... 

I tried making the app public ...  I also notice there are a lot of other credentials info:

![credential info](https://www.dropbox.com/s/wrzg8gzj46yf3bh/Screenshot%202016-03-11%2009.15.00.png?dl=1)

**Comment by tansaku** [comment]
I reloaded the hangout - I get the following in the developer console:

![developer console output](https://www.dropbox.com/s/4etn4bhpzeavpnx/Screenshot%202016-03-11%2009.17.27.png?dl=1)

The thing I wonder is should all this effort perhaps be better directed into better supporting text standups ...

**Comment by tansaku** [comment]
ah hmm, I restarted the WSO production server and restarted the hangout (after having made the app public) and the connection has worked (I had to give permission to the new one) and briefly I had two apps - I deleted the old one, and the notification came through ...

**Comment by tansaku** [comment]
I think I start to understand the flow here, which is: 

1. we add a hangout button on the event page with starting data set in event_instances/_hangout_button.html.erb (including callback URL to relevant AV site, and ID of Google Hangout plugin)
2. user clicks hangout button which starts hangout which runs the Hangout plugin, which will have access to the starting data set
3. the Hangout plugin is available via this XML https://raw.githubusercontent.com/AgileVentures/HangoutConnection/master/public/websiteone.xml which includes javascript which then fires back to the original AV site specified in the starting data ...
