### ISSUE TITLE
Styling issues on past scrums view

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#873]
![screenshot 2016-03-08 13 29 52](https://cloud.githubusercontent.com/assets/4028374/13600532/fdee0ed4-e531-11e5-8dc3-0d2fe4cbc091.png)

Also, investigate failure to load `scrums.js`

![screenshot 2016-03-08 13 36 50](https://cloud.githubusercontent.com/assets/4028374/13600616/a547c2ba-e532-11e5-9e5b-f82d9855041d.png)

**Comment by tochman** [comment]
Where did the Timeline we had before go?

**Comment by tansaku** [comment]
I think it's just not loading correctly due to the js or possibly css errors @tochman

**Comment by tochman** [comment]
How did thi get past staging?

**Comment by tansaku** [comment]
@tochman I imagine that we didn't check this particular view - which is a miss on our part

Personally I'd very much like to consolidate all three events views into one to reduce the UX and code complexity

**Comment by tansaku** [comment]
the error suggests that the page is trying to load `javascripts/scrums.js` and I see `<%= javascript_include_tag 'scrums' %>` at the top of the scrum controller ... other pages are loading js from `assets/*.js`

**Comment by tansaku** [comment]
although that seems unrelated - I've removed that tag - and scrums.js is being loaded over the assets pathway anyway ..., so I guess there is some CSS issue ... we probably need to identify some point in the past that this worked in order to get to the bottom of this ...

**Comment by tansaku** [comment]
was working in https://github.com/AgileVentures/WebsiteOne/commit/e16b3ed22362eb0293fb02de3e9d6308780b7d0f

**Comment by tansaku** [comment]
working in https://github.com/AgileVentures/WebsiteOne/commit/4bbb655590deb7068e4ac6e1499f220f0dc78552

**Comment by tansaku** [comment]
Git Bisect identifies the problem as here:

```
f1c51dc030a5aa3b74363b903b7fa9c44d710d71 is the first bad commit
commit f1c51dc030a5aa3b74363b903b7fa9c44d710d71
Author: Bryan & Chris <bryan.yap.mh@gmail.com>
Date:   Tue Dec 30 21:00:47 2014 +0000

    Removed hangout management partial, added HOA button, refactored CSS, removed some unused dependencies
    
    https://www.pivotaltracker.com/story/show/85232534
    
    - Removed the hangout management partial from the Event’s show page
    - Add a HOA button beside the Event dropdown
    - Modified hangouts.js to use the small version of the button
    - Moved all third party styles to vendor/assets/stylesheets
    - Removed unused dependencies cubeportfolio and confy
    
    Styled event show page calendar and added link to live hangout
    
    - Styled event show page further, including the next scheduled event and
      re-introduced the live hangout link
    - Updated the Event model to add #recent_hangouts which only returns hangouts
      within a specified time frame (to some extent, avoids returning outdated
      hangouts)
    - Refactored (removed) tests for the Event show page

:040000 040000 f2ef9aa2ce22d759fcbcb227de38a5b83b8a9275 b4e5ce7e180ac56d6b9e49559c33e224b6474b0d M	app
:040000 040000 26caf0af6b741b86e9bbe6f15a1e90d1153eb256 156f29af610d6155260ecfcdd9ca46632eb0d98f M	features
:040000 040000 d27cd26d5d8d88c8cf711c051715e8e1c273f77e 5f42d26783f6bef49c6c2089bd4fc3c9ec02cd64 M	spec
```

**Comment by tansaku** [comment]
okay, so it looks like `@import "timeline";` was removed from `application.scss` back in this commit from 2014, which got merged in as part of that monster legacy merge in February ...
