### ISSUE TITLE
No Github or G+ buttons on sign_up page

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#880]
We seem to have lost Github and G+ buttons on the `sign_up` page

<img width="452" alt="screenshot 2016-03-08 19 54 26" src="https://cloud.githubusercontent.com/assets/4028374/13610795/1bc9903c-e568-11e5-89be-ad8cd146c679.png">

**Comment by mtc2013** [comment]
@diraulo I'm not able to reproduce this locally with the latest develop branch.  Is this staged somewhere?

**Comment by tansaku** [comment]
I get them:

![github and g+ buttons present](https://www.dropbox.com/s/66yn8c697r1eypg/Screenshot%202016-03-08%2018.54.24.png?dl=1)

Perhaps an internet timeout issue on your side @diraulo ?

**Comment by diraulo** [comment]
@tansaku Oops i forgot to mention it was on the develop server
http://websiteone-develop.herokuapp.com/users/sign_up

But it seems to be working now :confused: 
I'm going to close this issue then I guess.

**Comment by diraulo** [comment]
@tansaku @mtc2013: Actually, it does disappear for me after a failed attempt to sign_up using my Github account. I currently don't have a public email address set, and so I should get an error message about that as per #878. But I don't :confused:

**Comment by tansaku** [comment]
mmm, I got the same - rats ...

![lost icons and no appropriate error message](https://www.dropbox.com/s/n82qj5i4im8xjks/Screenshot%202016-03-08%2019.57.10.png?dl=1)

strange the cukes all pass - I wonder what we get on production ...

**Comment by tansaku** [comment]
mmmm, I get exactly the same failure on production:

![failure on production](https://www.dropbox.com/s/m6r3zni171ikm73/Screenshot%202016-03-08%2019.58.12.png?dl=0)

So I think this is an existing bug, and that users were never getting any message at all ... that explains a lot - further explanation needed ...

**Comment by diraulo** [comment]
I was also able to replicate this on production, so it's been there for a while i guess. I had a look at the cukes, there's none for the sign_up page at the moment, That may explain why

**Comment by tansaku** [comment]
there is a cuke for the sign up page:

```cucumber
  @omniauth
  Scenario: User signs up with a GitHub account
    Given I am on the "registration" page
    When I click "GitHub"
    Then I should see "Signed in successfully."

  @omniauth-without-email
  Scenario: User signs up with a GitHub account having no public email (sad path)
    Given I am on the "registration" page
    When I click "GitHub"
    Then I should see "Your Github account needs to have a public email address for sign up"

  @omniauth-without-email
  Scenario: User signs up with a Google+ account having no public email (sad path)
    Given I am on the "registration" page
    When I click "Google+"
    Then I should see "Your Gplus account needs to have a public email address for sign up"
```

in `features/users/create_users.feature`

That's what @mtc2013 and I were working on this afternoon assuming it was representative of what actually happens in the system.

@mtc2013 made a point about how the data being stubbed as coming back from github does not look like the full set we would get back, so that might be one place to start ...  I wonder if we can use @vcr and @puffing-billy with this to ensure that it is an accurate reflection of the sign up process ...
