### ISSUE TITLE
Edit hangout link won't accept hangout url

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#883]
....@tansaku was trying to add https://talkgadget.google.com/hangouts/_/mdbprcxhbzauxmpxq56hqr5lvie?hl=en to http://www.agileventures.org/events/817 but when doing so got:

![blank page](https://www.dropbox.com/s/ru60qohu0xmm44g/Screenshot%202016-03-09%2016.21.03.png?dl=1)

hitting back gives:

![going back](https://www.dropbox.com/s/8ptqdc9vd1z03zm/Screenshot%202016-03-09%2016.21.33.png?dl=1)

and the link is not saved

![not saved](https://www.dropbox.com/s/412u8ma8stxxog2/Screenshot%202016-03-09%2016.22.00.png?dl=1)

**Comment by tansaku** [comment]
worked for me just now - wonder if this is an intermittent issue?

**Comment by mattlindsey** [comment]
Closing old/unconfirmed issues...
