### ISSUE TITLE
Hangout on Air buttons should say "Host Hangout on Air" rather than just "Start"

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#884]
Users should be aware that starting the hangout means they will be acting as host of a Hangout on Air

**Comment by tansaku** [comment]
Seems that we can't easily adjust the text, but we have increased the widget size to revert back to the longer "Start Hangout on Air" text 

See http://stackoverflow.com/questions/35898223/how-can-we-create-a-google-hangout-on-air-button-with-different-text

**Comment by tansaku** [comment]
wondering if we could search css via text content, so we searched the page for a span with "Start Hangout on Air" and edited that dynamically...

**Comment by tansaku** [comment]
however looks like this button is pulled in via in iframe and it looks like we can't easily grab contents with jQuery, so I think give up on this for the moment.   Contents method does not work on it:

```
$('iframe')[0].contents()
VM2124:2 Uncaught TypeError: $(...)[0].contents is not a function(…)
```

**Comment by diraulo** [comment]
reopening this since #885 was just a partial fix

**Comment by mattlindsey** [comment]
Closing old/obsolete issues...
