### ISSUE TITLE
Network Sandboxing of our Cucumber Acceptance tests

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#904]
Currently our Cucumber Acceptance tests are not completely sandboxed; at least not on the client side.

Ideally any tests that are running a headless browser with javascript enabled should be sandboxed from making any live network connections with something like [puffing billy](https://github.com/oesmith/puffing-billy) which will record and save any network activity for subsequent playback.

The server side version of puffing billy is [vcr](https://github.com/vcr/vcr) which records server side network activity for playback.  

The advantage of using vcr and puffing billy is that the recorded files (containing network actiivty that can be played back) are stored in a consistent location and can be easily updated by simply being deleted and having the tests be re-run, which avoids the need to manually edit custom webmock stubs.

The added advantages here should be that our tests run faster (don't have to wait for any network connections) and that they are more reliable (no failures due to failing network connections)

**Comment by tansaku** [comment]
Note that we have an example of a complete cucumber puffing_billy and vcr setup in https://github.com/AgileVentures/LocalSupport many thanks to hard work from @zmagod and @decareano

**Comment by freeranger** [comment]
I'm not sure about the "validity" of _acceptance _tests using mocked anything - for me, the acceptance test should be using the full stack, not only bits of it - otherwise, what are you accepting?

If the server side is flaky then the front end should deal with that gracefully, (which should also be tested).  I'd be concerned that mocking out an unreliable network connection is masking problems with it. 

Mocking out the network certainly has value for certain types of tests - I'm just not sure acceptance tests are the right place for them....

**Comment by tansaku** [comment]
> I'm not sure about the "validity" of _acceptance _tests using mocked anything - for me, the acceptance test should be using the full stack, not only bits of it - otherwise, what are you accepting?

It is testing the full-stack - just not 3rd party apps available over the network.  Allowing your acceptance tests to hit 3rd party apps is very bad netiquette.  It means you are making network requests every time you run your tests and CI and also exposes your acceptance tests to randomness due to network failure.  Very poor practice in my opinion.

I'm not talking about mocking out "our server" side.  If you own both sides of the app (client and server) then that's fine.  What's not fine is hitting 3rd party services (e.g. github, google maps, twitter, facebook) as part of acceptance tests.  Those have to be stubbed via vcr and puffing_billy in my opinion otherwise you're acceptance tests are leaking badly.

**Comment by tansaku** [comment]
I also note that since we switched over in this fashion in LocalSupport our tests are faster and more reliable and are supporting our development practice as opposed to getting in the way of it as they often are in WSO.

**Comment by freeranger** [comment]
Ah right, that's fair enough yes - I thought you wanted to isolate your front end from your back end and still call it "acceptance tests" :)
