### ISSUE TITLE
Members directory - filter by order is broken

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#914]
http://www.agileventures.org/users

![image](https://cloud.githubusercontent.com/assets/1401069/13813668/acd173ac-eb7a-11e5-85f0-3d4b8fb4af9d.png)

The order seems to be very random - the projects should be in some obvious order (e.g. alphabetic?  By activity (and would have to show the activity level).
There are a couple of non-project items listed here which should possibly appear first?  or last?

**Comment by tansaku** [comment]
yeah, we need to go alphabetical with maybe some common ones at top perhaps - we explicitly didn't implement an ordering here in order to move quick on delivering the higher level feature

**Comment by mattlindsey** [comment]
+1
Filtering by projects seems broken now (2020). Maybe just remove it.
