### ISSUE TITLE
Members directory - order of members is random/non-obvious

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#915]
![image](https://cloud.githubusercontent.com/assets/1401069/13813724/081233be-eb7b-11e5-93bb-8e3272a8862f.png)

These are clearly not alphabetic.  It seems confusing to me to see them in what appears to be a random order.
Would like to see them in some obvious order (e.g alphabetic, by commit count/project count/joining date) which is visible on screen

**Comment by tochman** [comment]
It is not obvious but the order is kind of the join date - it's by :id. There are far better ways to display this index though.

**Comment by freeranger** [comment]
I wonder if it might be best to just order this alphabetically - it literally is just a directory of members, and we can have other views for things like "top 10 committers", "top 10 posters" etc.
Also wondering if a map view would be nice, to visualise the truly global nature of the membership.
eg, this from Coursera - as you zoom in, the numbers get split down by country so you get a better idea.
![image](https://cloud.githubusercontent.com/assets/1401069/13821261/c682a096-eb98-11e5-8ae9-9b50c3180ce6.png)

**Comment by tochman** [comment]
Regarding a map. Plz see http://www.agileventures.org/dashboard

**Comment by freeranger** [comment]
Thanks for the link - I wasn't aware of that - shame it's hidden at the bottom of the page - there's good stuff on there!
I've found that before that some good content isn't easily discoverable because it isn't in the "F" pattern (https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/) or indeed isn't linked from any of the main screens at all.

**Comment by tochman** [comment]
How about sorting members by sign_in_count?

**Comment by freeranger** [comment]
I think, as a _directory_, the only order that makes sense (to me) is A-Z - I can't think of another directory that is ordered any other way.
When we look at adding merit badges for members then perhaps we could have a side panel somewhere that shows the top _n_ members ordered by something worthy of merit - total "merit points", or total commits and so on.

**Comment by mattlindsey** [comment]
Closing. Ordering by activity is working now.
