### ISSUE TITLE
Changing your avatar requires a hard refresh to reset it

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#922]
I changed my avatar but the image actually used for my profile both on the menu (and when I went into the account screen) was the old one:
![image](https://cloud.githubusercontent.com/assets/1401069/13849905/e5adec5c-ec4f-11e5-9318-84cd31302fc3.png)

Logging out and back in again did not resolve - I had to Ctrl-Refresh the page

**Comment by diraulo** [comment]
Some users also reported some issues with their gravatar this week in the slack channel

<img width="785" alt="screenshot 2016-03-23 19 37 43" src="https://cloud.githubusercontent.com/assets/4028374/13994754/f12a064a-f12e-11e5-8df4-ffda396a41d1.png">

**Comment by mattlindsey** [comment]
Closing old issues...
