### ISSUE TITLE
[Airbrake] [Production] PG::UndefinedTable: ERROR:  relation "static_pages" does not exist
LINE 5:                WHERE a.attrelid = '"static_pages"'::regclass
                                          ^
:               SELECT a.attname, format_type(a....

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#923]
**Airbrake error:** [#0751](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/1643530915950360751)
**Airbrake project:** websiteone-production

**Error type:** `ActiveRecord::StatementInvalid`
**Error message:** `PG::UndefinedTable: ERROR:  relation "static_pages" does not exist
LINE 5:                WHERE a.attrelid = '"static_pages"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attreli`
**Occurred at:** Mar 17, 2016 15:22:32 UTC
**First seen at:** Mar 17, 2016 15:22:32 UTC
**Occurrences:** 1 (0 since last deploy on Time not available)

**URL:** [http://wso-tracer.herokuapp.com](http://wso-tracer.herokuapp.com)
**File:** `[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in async_exec
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in block in exec_no_cache
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in block in log
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in instrument
```

**Comment by tansaku** [comment]
sorry this is a test from another server
