### ISSUE TITLE
when event edit (on existing event) fails due to repeat end being blank, state about days is lost

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#934]
Need to review maintaining appropriate state across validation failures.

**Comment by tansaku** [comment]
select extra days on existing event

![](https://www.dropbox.com/s/mk4ofl2gi50i51o/Screenshot%202016-04-20%2017.38.19.png?dl=1)

remove any end date - and fail validation

![](https://www.dropbox.com/s/fqjaouotd8xga9a/Screenshot%202016-04-20%2017.39.01.png?dl=1)

then we lose user data on which days were selected

![](https://www.dropbox.com/s/temabuucc8kypc2/Screenshot%202016-04-20%2017.37.54.png?dl=1)

which breaks Raskin's first law of HCI which is that no system shall cause, or through inaction allow, and loss of human entered data

**Comment by tansaku** [comment]
this should wait until we finish timezone fix

**Comment by mtc2013** [comment]
It appears that this may be fixed.

**Comment by mtc2013** [comment]
We may want to wrap this in a test if so.

**Comment by mtc2013** [comment]
This is not fixed on production at least.
