### ISSUE TITLE
Notification on Slack of Hangout creation

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/WebsiteOne#947]
Since about 1 or 2 weeks ago no more notifications are shown in the Slack channels when we create a new PP session or a Standup.

Steps to reproduce the problem:
* Go to website one
* Create a PP session
* Press the notify to slack button

**Comment by tansaku** [comment]
sorry about this @joaopapereira - am looking into it

**Comment by tansaku** [comment]
just testing with LS pairing hangout ... connection status is red - hit in production logs was:

```
2016-04-04T09:29:08.739468+00:00 app[web.1]: Started OPTIONS "/hangouts/331459762127" for 86.145.234.177 at 2016-04-04 09:29:08 +0000
2016-04-04T09:29:08.743238+00:00 app[web.1]: Processing by EventInstancesController#update as */*
2016-04-04T09:29:08.743276+00:00 app[web.1]:   Parameters: {"id"=>"331459762127"}
2016-04-04T09:29:08.802876+00:00 app[web.1]: Filter chain halted as :cors_preflight_check rendered or redirected
2016-04-04T09:29:08.802992+00:00 app[web.1]: Completed 400 Bad Request in 60ms (ActiveRecord: 3.9ms)
2016-04-04T09:29:08.804137+00:00 app[web.1]: source=rack-timeout id=817f4c11-31a2-4e16-ae67-eec4cb94621a wait=5ms timeout=20000ms service=66ms state=completed
2016-04-04T09:29:08.803749+00:00 heroku[router]: at=info method=OPTIONS path="/hangouts/331459762127" host=websiteone-production.herokuapp.com request_id=817f4c11-31a2-4e16-ae67-eec4cb94621a fwd="86.145.234.177" dyno=web.1 connect=0ms service=69ms status=400 bytes=500
```

**Comment by tansaku** [comment]
errors in js console associated with hangout was:

![](https://www.dropbox.com/s/thd9d0u9ybzy15k/Screenshot%202016-04-04%2010.31.31.png?dl=1)

**Comment by tansaku** [comment]
Seems there is some new preflight requirement that we are failing to support:

"Response for preflight has invalid HTTP status code 400"

**Comment by tansaku** [comment]
hmm, so we are set to allow an options request:
```
  match '/hangouts/:id' => 'event_instances#update', :via => [:put, :options], as: 'hangout'
```

**Comment by tansaku** [comment]
so this part of the error is important then?

```
Filter chain halted as :cors_preflight_check rendered or redirected
```

related? 

http://stackoverflow.com/questions/28282582/access-control-allow-origin-rails-project-cross-domain-no-route-matches-optio

I wonder if something changed recently in the way hangouts are talking to our server ...?

**Comment by tansaku** [comment]
we currently have:

```ruby
class EventInstancesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check, except: [:index]

...

  private

  def cors_preflight_check
    head :bad_request and return unless (allowed? || local_request?)

    set_cors_headers
    head :ok and return if request.method == 'OPTIONS'
  end

  def allowed?
    allowed_sites = %w(a-hangout-opensocial.googleusercontent.com)
    origin = request.env['HTTP_ORIGIN']
    allowed_sites.any?{ |url| origin =~ /#{url}/ }
  end

  def local_request?
    request.env['HTTP_ORIGIN'] =~ /#{request.env['HTTP_HOST']}/
  end

  def set_cors_headers
    response.headers['Access-Control-Allow-Origin'] = request.env['HTTP_ORIGIN']
    response.headers['Access-Control-Allow-Methods'] = 'PUT'
  end
```

**Comment by tansaku** [comment]
inspecting saw that http origin was "http://evil.com" in my chrome brower.  Note related SO post: http://stackoverflow.com/questions/27292441/origin-evil-com-in-request-header

**Comment by tansaku** [comment]
So it seems like there are layers of issues here:

1. The Chrome browser plugin [Allow-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) can cause hangout connection to fail to talk to WSO
2. We don't set the project slug for the yt hangout notification which leads to some errors
3. The agile bot is now failing to talk to slack for some reason ... unclear why

**Comment by tansaku** [comment]
note have tested agile bot from console and for some reason API post to slack is not getting through - despite 200 response - see https://github.com/AgileVentures/agile-bot/issues/17 for more details

**Comment by tansaku** [comment]
I think I've fixed the problem 3) above by updating the slack token for agile-bot - see: https://github.com/AgileVentures/agile-bot/issues/18
