### ISSUE TITLE
events index is showing me a combination of GMT and BST timezones

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#953]
![](https://www.dropbox.com/s/t7us72fnk7gefgc/Screenshot%202016-04-06%2012.17.39.png?dl=1)

this is a timezone issue

**Comment by tansaku** [comment]
so some have the UK daylight savings taken into account and others do not ... confusing ...

**Comment by dalupus** [comment]
Looks like some of the underlying dates are wrong

<time data-localized="true" title="February 3, 2016 at 10:15am EDT" data-format="%H:%M" data-local="time" datetime="2016-02-03T15:15:00Z">10:15</time>

Need to look at how those times are built and why they are using the wrong date

**Comment by tansaku** [comment]
```ruby
             <i class="fa fa-calendar"></i><span class="month"><%= instance[:time].strftime('%a, %b %d, %Y') %></span><br/>
              <i class="fa fa-clock-o"></i><span><%= raw local_time(event.start_time, '%H:%M') %>-<%= raw local_time(event.instance_end_time, '%H:%M (%Z)') %></span>
```
problem is in code above, event.start_time -is getting time from several years ago when event sequence stared and that's in different daylight savings ...
