### ISSUE TITLE
send alert when automatic slack invitations are not working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#980]
several people have not got invitations recently ... I wonder if the token has expired ...

**Comment by tansaku** [comment]
I tried updating with the same token we refreshed on agile bot - and restarted the server.

What's tricky here is that slack seems to fail silently when the token expires --> we get a 200 response ... again this may be related to the fact that we are using test/dev tokens rather than having created an app.

Ideally we'd get some notification in slack whenever anyone creates a new account ...

**Comment by tansaku** [comment]
we encountered the problem again recently - we should investigate if slack not has some alternate permanent token: https://agileventures.slack.com/apps/build

**Comment by sampritipanda** [comment]
To generate a "permanent" token, we would need to create a slack app, do a oauth authorization using the admin scope, and obtain a token for the user.

However, according to http://stackoverflow.com/a/38446599/1466095 and slack documentation, it doesn't look like test tokens expire unless you post them publically.

So I think we should be fine using test tokens for the invite functionality. What we could do is add a check if the request fails when inviting.

**Comment by tansaku** [comment]
I think the tokens can expire occasionally - they are not guaranteed to work indefinitely are they ...?

**Comment by tansaku** [comment]
> So I think we should be fine using test tokens for the invite functionality. What we could do is add a check if the request fails when inviting.

yeah, this is the important thing ...

**Comment by tansaku** [comment]
difficult to get an acceptance test in place due to async and lots of setting difference in test ...

having the slack invite on the after_create seems odd

seems odd to have slack invites off in the test settings
